.TH "C:/Users/JulyaMaria/Desktop/Desmo-J/org/apache/commons/math/distribution Directory Reference" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/JulyaMaria/Desktop/Desmo-J/org/apache/commons/math/distribution Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAbstractContinuousDistribution\&.java\fP"
.br
.ti -1c
.RI "file \fBAbstractDistribution\&.java\fP"
.br
.ti -1c
.RI "file \fBAbstractIntegerDistribution\&.java\fP"
.br
.ti -1c
.RI "file \fBBinomialDistribution\&.java\fP"
.br
.ti -1c
.RI "file \fBBinomialDistributionImpl\&.java\fP"
.br
.ti -1c
.RI "file \fBCauchyDistribution\&.java\fP"
.br
.ti -1c
.RI "file \fBCauchyDistributionImpl\&.java\fP"
.br
.ti -1c
.RI "file \fBChiSquaredDistribution\&.java\fP"
.br
.ti -1c
.RI "file \fBChiSquaredDistributionImpl\&.java\fP"
.br
.ti -1c
.RI "file \fBContinuousDistribution\&.java\fP"
.br
.ti -1c
.RI "file \fBDiscreteDistribution\&.java\fP"
.br
.ti -1c
.RI "file \fBDistribution\&.java\fP"
.br
.ti -1c
.RI "file \fBDistributionFactory\&.java\fP"
.br
.ti -1c
.RI "file \fBDistributionFactoryImpl\&.java\fP"
.br
.ti -1c
.RI "file \fBExponentialDistribution\&.java\fP"
.br
.ti -1c
.RI "file \fBExponentialDistributionImpl\&.java\fP"
.br
.ti -1c
.RI "file \fBFDistribution\&.java\fP"
.br
.ti -1c
.RI "file \fBFDistributionImpl\&.java\fP"
.br
.ti -1c
.RI "file \fBGammaDistribution\&.java\fP"
.br
.ti -1c
.RI "file \fBGammaDistributionImpl\&.java\fP"
.br
.ti -1c
.RI "file \fBHypergeometricDistribution\&.java\fP"
.br
.ti -1c
.RI "file \fBHypergeometricDistributionImpl\&.java\fP"
.br
.ti -1c
.RI "file \fBIntegerDistribution\&.java\fP"
.br
.ti -1c
.RI "file \fBNormalDistribution\&.java\fP"
.br
.ti -1c
.RI "file \fBNormalDistributionImpl\&.java\fP"
.br
.ti -1c
.RI "file \fBPascalDistribution\&.java\fP"
.br
.ti -1c
.RI "file \fBPascalDistributionImpl\&.java\fP"
.br
.ti -1c
.RI "file \fBPoissonDistribution\&.java\fP"
.br
.ti -1c
.RI "file \fBPoissonDistributionImpl\&.java\fP"
.br
.ti -1c
.RI "file \fBTDistribution\&.java\fP"
.br
.ti -1c
.RI "file \fBTDistributionImpl\&.java\fP"
.br
.ti -1c
.RI "file \fBWeibullDistribution\&.java\fP"
.br
.ti -1c
.RI "file \fBWeibullDistributionImpl\&.java\fP"
.br
.in -1c
