.TH "C:/Users/JulyaMaria/Desktop/Desmo-J/org/apache/commons/math/util Directory Reference" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/JulyaMaria/Desktop/Desmo-J/org/apache/commons/math/util Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBContinuedFraction\&.java\fP"
.br
.ti -1c
.RI "file \fBDefaultTransformer\&.java\fP"
.br
.ti -1c
.RI "file \fBDoubleArray\&.java\fP"
.br
.ti -1c
.RI "file \fBMathUtils\&.java\fP"
.br
.ti -1c
.RI "file \fBNumberTransformer\&.java\fP"
.br
.ti -1c
.RI "file \fBResizableDoubleArray\&.java\fP"
.br
.ti -1c
.RI "file \fBTransformerMap\&.java\fP"
.br
.in -1c
