.TH "C:/Users/JulyaMaria/Desktop/Desmo-J/desmoj/extensions/visualization2d/animation/core/statistic Directory Reference" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/JulyaMaria/Desktop/Desmo-J/desmoj/extensions/visualization2d/animation/core/statistic Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAccumulateAnimation\&.java\fP"
.br
.ti -1c
.RI "file \fBAggregateAnimation\&.java\fP"
.br
.ti -1c
.RI "file \fBCountAnimation\&.java\fP"
.br
.ti -1c
.RI "file \fBHistogramAnimation\&.java\fP"
.br
.ti -1c
.RI "file \fBTallyAnimation\&.java\fP"
.br
.ti -1c
.RI "file \fBTimeSeriesAnimation\&.java\fP"
.br
.in -1c
