.TH "C:/Users/JulyaMaria/Desktop/Desmo-J/desmoj/extensions/experimentation/ui Directory Reference" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/JulyaMaria/Desktop/Desmo-J/desmoj/extensions/experimentation/ui Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAccessPointTableModel\&.java\fP"
.br
.ti -1c
.RI "file \fBAttributeTableEditor\&.java\fP"
.br
.ti -1c
.RI "file \fBBrowserPanel\&.java\fP"
.br
.ti -1c
.RI "file \fBChart\&.java\fP"
.br
.ti -1c
.RI "file \fBChartOwner\&.java\fP"
.br
.ti -1c
.RI "file \fBChartPanel\&.java\fP"
.br
.ti -1c
.RI "file \fBExperimentStarter\&.java\fP"
.br
.ti -1c
.RI "file \fBExperimentStarterApplet\&.java\fP"
.br
.ti -1c
.RI "file \fBExperimentStarterApplication\&.java\fP"
.br
.ti -1c
.RI "file \fBExperimentStarterGUI\&.java\fP"
.br
.ti -1c
.RI "file \fBGraphicalObserver\&.java\fP"
.br
.ti -1c
.RI "file \fBGraphicalObserverContext\&.java\fP"
.br
.ti -1c
.RI "file \fBHistogramPlotter\&.java\fP"
.br
.ti -1c
.RI "file \fBIGraphicalObserver\&.java\fP"
.br
.ti -1c
.RI "file \fBLoadModelDialog\&.java\fP"
.br
.ti -1c
.RI "file \fBObserverDesktop\&.java\fP"
.br
.ti -1c
.RI "file \fBReportsPanel\&.java\fP"
.br
.ti -1c
.RI "file \fBReportStylerPanel\&.java\fP"
.br
.ti -1c
.RI "file \fBSettingsPanel\&.java\fP"
.br
.ti -1c
.RI "file \fBTimeSeriesPlotter\&.java\fP"
.br
.ti -1c
.RI "file \fBURLTreePanel\&.java\fP"
.br
.in -1c
