.TH "C:/Users/JulyaMaria/Desktop/Desmo-J/desmoj/extensions/grafic/util Directory Reference" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/JulyaMaria/Desktop/Desmo-J/desmoj/extensions/grafic/util Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBHistogramDataSetAdapter\&.java\fP"
.br
.ti -1c
.RI "file \fBPaintPanel\&.java\fP"
.br
.ti -1c
.RI "file \fBPlotter\&.java\fP"
.br
.ti -1c
.RI "file \fBTimeSeriesDataSetAdapter\&.java\fP"
.br
.in -1c
