.TH "C:/Users/JulyaMaria/Desktop/Desmo-J/desmoj/core/statistic Directory Reference" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/JulyaMaria/Desktop/Desmo-J/desmoj/core/statistic Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAccumulate\&.java\fP"
.br
.ti -1c
.RI "file \fBAggregate\&.java\fP"
.br
.ti -1c
.RI "file \fBBoolStatistic\&.java\fP"
.br
.ti -1c
.RI "file \fBConfidenceCalculator\&.java\fP"
.br
.ti -1c
.RI "file \fBCount\&.java\fP"
.br
.ti -1c
.RI "file \fBDataListTally\&.java\fP"
.br
.ti -1c
.RI "file \fBHistogram\&.java\fP"
.br
.ti -1c
.RI "file \fBHistogramAccumulate\&.java\fP"
.br
.ti -1c
.RI "file \fBRegression\&.java\fP"
.br
.ti -1c
.RI "file \fBStatisticObject\&.java\fP"
.br
.ti -1c
.RI "file \fBStatisticObjectSupportingTimeSpans\&.java\fP"
.br
.ti -1c
.RI "file \fBTally\&.java\fP"
.br
.ti -1c
.RI "file \fBTallyRunning\&.java\fP"
.br
.ti -1c
.RI "file \fBTextHistogram\&.java\fP"
.br
.ti -1c
.RI "file \fBTextSupplier\&.java\fP"
.br
.ti -1c
.RI "file \fBTimeSeries\&.java\fP"
.br
.ti -1c
.RI "file \fBValueStatistics\&.java\fP"
.br
.ti -1c
.RI "file \fBValueSupplier\&.java\fP"
.br
.in -1c
