.TH "C:/Users/JulyaMaria/Desktop/Desmo-J/desmoj/extensions/visualization2d/animation Directory Reference" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/JulyaMaria/Desktop/Desmo-J/desmoj/extensions/visualization2d/animation Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcore\fP"
.br
.ti -1c
.RI "directory \fBextensions\fP"
.br
.ti -1c
.RI "directory \fBinternalTools\fP"
.br
.ti -1c
.RI "directory \fBprocessStation\fP"
.br
.ti -1c
.RI "directory \fBtransport\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBackgroundElementAnimation\&.java\fP"
.br
.ti -1c
.RI "file \fBBackgroundLineAnimation\&.java\fP"
.br
.ti -1c
.RI "file \fBCmdGeneration\&.java\fP"
.br
.ti -1c
.RI "file \fBComment\&.java\fP"
.br
.ti -1c
.RI "file \fBForm\&.java\fP"
.br
.ti -1c
.RI "file \fBFormExt\&.java\fP"
.br
.ti -1c
.RI "file \fBPosition\&.java\fP"
.br
.ti -1c
.RI "file \fBPositionExt\&.java\fP"
.br
.in -1c
