.TH "C:/Users/JulyaMaria/Desktop/Desmo-J/desmoj/extensions Directory Reference" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/JulyaMaria/Desktop/Desmo-J/desmoj/extensions Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBapplicationDomains\fP"
.br
.ti -1c
.RI "directory \fBchaining\fP"
.br
.ti -1c
.RI "directory \fBcrossbar\fP"
.br
.ti -1c
.RI "directory \fBdimensions\fP"
.br
.ti -1c
.RI "directory \fBexperimentation\fP"
.br
.ti -1c
.RI "directory \fBgrafic\fP"
.br
.ti -1c
.RI "directory \fBscheduling\fP"
.br
.ti -1c
.RI "directory \fBspace3D\fP"
.br
.ti -1c
.RI "directory \fBvisualEvents\fP"
.br
.ti -1c
.RI "directory \fBvisualization2d\fP"
.br
.ti -1c
.RI "directory \fBvisualization3d\fP"
.br
.ti -1c
.RI "directory \fBxml\fP"
.br
.in -1c
