.TH "C:/Users/JulyaMaria/Desktop/Desmo-J/desmoj/extensions/applicationDomains/production Directory Reference" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/JulyaMaria/Desktop/Desmo-J/desmoj/extensions/applicationDomains/production Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBreport\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCustomerProcess\&.java\fP"
.br
.ti -1c
.RI "file \fBDemandProcess\&.java\fP"
.br
.ti -1c
.RI "file \fBEntrepot\&.java\fP"
.br
.ti -1c
.RI "file \fBMachineProcess\&.java\fP"
.br
.ti -1c
.RI "file \fBPartsList\&.java\fP"
.br
.ti -1c
.RI "file \fBProcessing\&.java\fP"
.br
.ti -1c
.RI "file \fBRestockProcessMS\&.java\fP"
.br
.ti -1c
.RI "file \fBRestockProcessMT\&.java\fP"
.br
.ti -1c
.RI "file \fBRestockProcessQS\&.java\fP"
.br
.ti -1c
.RI "file \fBRestockProcessQT\&.java\fP"
.br
.ti -1c
.RI "file \fBSimpleTransporter\&.java\fP"
.br
.ti -1c
.RI "file \fBTransportation\&.java\fP"
.br
.ti -1c
.RI "file \fBTransporter\&.java\fP"
.br
.ti -1c
.RI "file \fBTransportJunction\&.java\fP"
.br
.ti -1c
.RI "file \fBTransportTerminal\&.java\fP"
.br
.ti -1c
.RI "file \fBWorker\&.java\fP"
.br
.ti -1c
.RI "file \fBWorkStation\&.java\fP"
.br
.in -1c
