.TH "C:/Users/JulyaMaria/Desktop/Desmo-J/org/apache/commons/math Directory Reference" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/JulyaMaria/Desktop/Desmo-J/org/apache/commons/math Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBanalysis\fP"
.br
.ti -1c
.RI "directory \fBdistribution\fP"
.br
.ti -1c
.RI "directory \fBspecial\fP"
.br
.ti -1c
.RI "directory \fButil\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBArgumentOutsideDomainException\&.java\fP"
.br
.ti -1c
.RI "file \fBConvergenceException\&.java\fP"
.br
.ti -1c
.RI "file \fBDimensionMismatchException\&.java\fP"
.br
.ti -1c
.RI "file \fBDuplicateSampleAbscissaException\&.java\fP"
.br
.ti -1c
.RI "file \fBFunctionEvaluationException\&.java\fP"
.br
.ti -1c
.RI "file \fBMathConfigurationException\&.java\fP"
.br
.ti -1c
.RI "file \fBMathException\&.java\fP"
.br
.ti -1c
.RI "file \fBMaxIterationsExceededException\&.java\fP"
.br
.ti -1c
.RI "file \fBMessagesResources_fr\&.java\fP"
.br
.in -1c
