.TH "C:/Users/JulyaMaria/Desktop/Desmo-J/org/apache/commons/math/analysis Directory Reference" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/JulyaMaria/Desktop/Desmo-J/org/apache/commons/math/analysis Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBisectionSolver\&.java\fP"
.br
.ti -1c
.RI "file \fBBrentSolver\&.java\fP"
.br
.ti -1c
.RI "file \fBDifferentiableUnivariateRealFunction\&.java\fP"
.br
.ti -1c
.RI "file \fBDividedDifferenceInterpolator\&.java\fP"
.br
.ti -1c
.RI "file \fBMullerSolver\&.java\fP"
.br
.ti -1c
.RI "file \fBNevilleInterpolator\&.java\fP"
.br
.ti -1c
.RI "file \fBNewtonSolver\&.java\fP"
.br
.ti -1c
.RI "file \fBPolynomialFunction\&.java\fP"
.br
.ti -1c
.RI "file \fBPolynomialFunctionLagrangeForm\&.java\fP"
.br
.ti -1c
.RI "file \fBPolynomialFunctionNewtonForm\&.java\fP"
.br
.ti -1c
.RI "file \fBPolynomialSplineFunction\&.java\fP"
.br
.ti -1c
.RI "file \fBRiddersSolver\&.java\fP"
.br
.ti -1c
.RI "file \fBRombergIntegrator\&.java\fP"
.br
.ti -1c
.RI "file \fBSecantSolver\&.java\fP"
.br
.ti -1c
.RI "file \fBSimpsonIntegrator\&.java\fP"
.br
.ti -1c
.RI "file \fBSplineInterpolator\&.java\fP"
.br
.ti -1c
.RI "file \fBTrapezoidIntegrator\&.java\fP"
.br
.ti -1c
.RI "file \fBUnivariateRealFunction\&.java\fP"
.br
.ti -1c
.RI "file \fBUnivariateRealIntegrator\&.java\fP"
.br
.ti -1c
.RI "file \fBUnivariateRealIntegratorImpl\&.java\fP"
.br
.ti -1c
.RI "file \fBUnivariateRealInterpolator\&.java\fP"
.br
.ti -1c
.RI "file \fBUnivariateRealSolver\&.java\fP"
.br
.ti -1c
.RI "file \fBUnivariateRealSolverFactoryImpl\&.java\fP"
.br
.ti -1c
.RI "file \fBUnivariateRealSolverImpl\&.java\fP"
.br
.ti -1c
.RI "file \fBUnivariateRealSolverUtils\&.java\fP"
.br
.in -1c
