.TH "desmoj.extensions.visualization2d.engine.viewer.InfoPane" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization2d.engine.viewer.InfoPane \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits JTabbedPane, ActionListener, and MouseListener\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBColoredTableCellRenderer\fP"
.br
.ti -1c
.RI "class \fBInfoContent\fP"
.br
.ti -1c
.RI "class \fBTabContent\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInfoPane\fP (\fBViewerPanel\fP viewer)"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "void \fBremoveEntry\fP (int j)"
.br
.ti -1c
.RI "void \fBaddEntity\fP (String entityId, String code)"
.br
.ti -1c
.RI "void \fBaddStatistic\fP (String statisticId, String code, int typ, boolean isInt)"
.br
.ti -1c
.RI "void \fBrefresh\fP ()"
.br
.ti -1c
.RI "void \fBactionPerformed\fP (ActionEvent e)"
.br
.ti -1c
.RI "void \fBmouseClicked\fP (MouseEvent arg0)"
.br
.ti -1c
.RI "void \fBmouseEntered\fP (MouseEvent e)"
.br
.ti -1c
.RI "void \fBmouseExited\fP (MouseEvent arg0)"
.br
.ti -1c
.RI "void \fBmousePressed\fP (MouseEvent e)"
.br
.ti -1c
.RI "void \fBmouseReleased\fP (MouseEvent e)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Internal window in viewer application to show attributes of entities
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
christian.mueller@th-wildau.de For information about subproject: desmoj\&.extensions\&.visualization2d please have a look at: http://www.th-wildau.de/cmueller/Desmo-J/Visualization2d/
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.visualization2d\&.engine\&.viewer\&.InfoPane\&.InfoPane (\fBViewerPanel\fPviewer)"
Internal window in viewer application to show attributes of entities 
.PP
\fBParameters:\fP
.RS 4
\fIroot\fP RootWindow of this InfoPane-Instance 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void desmoj\&.extensions\&.visualization2d\&.engine\&.viewer\&.InfoPane\&.actionPerformed (ActionEvente)"
set its by click invisible, when its empty Listener is set in Constructor of TabContent 
.SS "void desmoj\&.extensions\&.visualization2d\&.engine\&.viewer\&.InfoPane\&.addEntity (StringentityId, Stringcode)"
fuegt neues Entity Objekt in content Liste am Anfang eingefuegt\&. Wird von EntityGrafic actionPerformed aufgerufen 
.PP
\fBParameters:\fP
.RS 4
\fIentityId\fP Id der Entity 
.br
\fIcode\fP Code zur Bezeichnung des Statistic Objects 
.RE
.PP

.SS "void desmoj\&.extensions\&.visualization2d\&.engine\&.viewer\&.InfoPane\&.addStatistic (StringstatisticId, Stringcode, inttyp, booleanisInt)"
fuegt neues Statistic Objekt in content Liste am Anfang eingefuegt\&. Wird von StatisticGrafic actionPerformed aufgerufen 
.PP
\fBParameters:\fP
.RS 4
\fIstatisticId\fP Id des Statistic Objects 
.br
\fIcode\fP Code zur Bezeichnung des Statistic Objects 
.br
\fItyp\fP 
.br
\fIisInt\fP 
.RE
.PP

.SS "void desmoj\&.extensions\&.visualization2d\&.engine\&.viewer\&.InfoPane\&.refresh ()"
Wird aufgerufen vom Viewer Start actionPerformed Dort werden mit reload() alle AnimationsElemente neu erstellt\&. Damit die zuvor ausgewaehlten Statistiken weiterverwendet werden koennen, muessen die Grafikobjekte neu erstellt werden\&. Alle EntityObjekte werden geloescht, das sie veraltet sind\&. 
.SS "void desmoj\&.extensions\&.visualization2d\&.engine\&.viewer\&.InfoPane\&.removeEntry (intj)"
remove entity with given id 
.PP
\fBParameters:\fP
.RS 4
\fIentityId\fP 
.RE
.PP

.SS "void desmoj\&.extensions\&.visualization2d\&.engine\&.viewer\&.InfoPane\&.reset ()"
remove all entities and makes it invisible 

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
