.TH "desmoj.extensions.visualization2d.engine.Constants" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization2d.engine.Constants \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fBFILE_EXTENSION_CMD\fP = '\&.cmds'"
.br
.ti -1c
.RI "static final String \fBFILE_EXTENSION_LOG\fP = '\&.log'"
.br
.ti -1c
.RI "static final String \fBFILE_EXTENSION_LOG_0\fP = '\&.log0'"
.br
.ti -1c
.RI "static final String \fBFILE_PATH\fP = '/desmoj/extensions/visualization2d/engine/viewer/files/'"
.br
.ti -1c
.RI "static final String \fBPACKAGE_PATH\fP = 'desmoj\&.extensions\&.visualization2d\&.engine\&.viewer\&.files\&.'"
.br
.ti -1c
.RI "static final String \fBBUNDLE_NAME\fP = 'bundleViewerLanguage'"
.br
.in -1c
.SH "Detailed Description"
.PP 
These constants are used in 2d animation engine
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
christian.mueller@th-wildau.de For information about subproject: desmoj\&.extensions\&.visualization2d please have a look at: http://www.th-wildau.de/cmueller/Desmo-J/Visualization2d/
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Member Data Documentation"
.PP 
.SS "final String desmoj\&.extensions\&.visualization2d\&.engine\&.Constants\&.BUNDLE_NAME = 'bundleViewerLanguage'\fC [static]\fP"
Resource Bundle in package_path 
.SS "final String desmoj\&.extensions\&.visualization2d\&.engine\&.Constants\&.FILE_EXTENSION_CMD = '\&.cmds'\fC [static]\fP"
File extension of cmds-file 
.SS "final String desmoj\&.extensions\&.visualization2d\&.engine\&.Constants\&.FILE_EXTENSION_LOG = '\&.log'\fC [static]\fP"
File extension from log-file generated from viewer while animation 
.SS "final String desmoj\&.extensions\&.visualization2d\&.engine\&.Constants\&.FILE_EXTENSION_LOG_0 = '\&.log0'\fC [static]\fP"
File extension from log-file generated while cmd-file generation\&. 
.SS "final String desmoj\&.extensions\&.visualization2d\&.engine\&.Constants\&.FILE_PATH = '/desmoj/extensions/visualization2d/engine/viewer/files/'\fC [static]\fP"
File path to viewer\&.file directory 
.SS "final String desmoj\&.extensions\&.visualization2d\&.engine\&.Constants\&.PACKAGE_PATH = 'desmoj\&.extensions\&.visualization2d\&.engine\&.viewer\&.files\&.'\fC [static]\fP"
Package path to viewer\&.file package 

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
