.TH "desmoj.extensions.visualization2d.animation.core.advancedModellingFeatures.CondQueueAnimation" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization2d.animation.core.advancedModellingFeatures.CondQueueAnimation \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits CondQueue, and \fBdesmoj\&.extensions\&.visualization2d\&.animation\&.core\&.simulator\&.ListInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCondQueueAnimation\fP (\fBModelAnimation\fP owner, String name, int sortOrder, int qCapacity, boolean showInReport, boolean showInTrace)"
.br
.ti -1c
.RI "\fBCondQueueAnimation\fP (\fBModelAnimation\fP owner, String name, boolean showInReport, boolean showInTrace)"
.br
.ti -1c
.RI "void \fBcreateAnimation\fP (\fBPosition\fP pos, \fBFormExt\fP form, boolean showInAnimation)"
.br
.ti -1c
.RI "void \fBcreateAnimation\fP (\fBComment\fP comment, \fBPosition\fP pos, \fBFormExt\fP form, boolean showInAnimation)"
.br
.ti -1c
.RI "boolean \fBwaitUntil\fP (Condition cond, \fBSimProcessAnimation\fP e)"
.br
.ti -1c
.RI "String \fBgetInternId\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Animation of a CondQueue
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
christian.mueller@th-wildau.de For information about subproject: desmoj\&.extensions\&.visualization2d please have a look at: http://www.th-wildau.de/cmueller/Desmo-J/Visualization2d/
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&.
.PP
\fBParameters:\fP
.RS 4
\fI<P>\fP 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.advancedModellingFeatures\&.CondQueueAnimation\&.CondQueueAnimation (\fBModelAnimation\fPowner, Stringname, intsortOrder, intqCapacity, booleanshowInReport, booleanshowInTrace)"
Constructor with the same parameters as in CondQueue 
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP used model 
.br
\fIname\fP as in CondQueue 
.br
\fIsortOrder\fP of inout queue possible values: ProcessQueueAnimation\&.FIFO ProcessQueueAnimation\&.LIFO 
.br
\fIqCapacity\fP capacity of input queue 
.br
\fIcapacity\fP No of resources available in resource pool 
.br
\fIshowInReport\fP as in CondQueue 
.br
\fIshowInTrace\fP as in CondQueue 
.RE
.PP

.SS "desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.advancedModellingFeatures\&.CondQueueAnimation\&.CondQueueAnimation (\fBModelAnimation\fPowner, Stringname, booleanshowInReport, booleanshowInTrace)"
Constructor with the same parameters as in CondQueue 
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP used model 
.br
\fIname\fP as in CondQueue 
.br
\fIshowInReport\fP as in CondQueue 
.br
\fIshowInTrace\fP as in CondQueue 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.advancedModellingFeatures\&.CondQueueAnimation\&.createAnimation (\fBPosition\fPpos, \fBFormExt\fPform, booleanshowInAnimation)"
create animation with full parameterization 
.PP
\fBParameters:\fP
.RS 4
\fIpos\fP middle point of animation object 
.br
\fIform\fP form of animation object 
.br
\fIshowInAnimation\fP switch animation on or off 
.RE
.PP

.SS "void desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.advancedModellingFeatures\&.CondQueueAnimation\&.createAnimation (\fBComment\fPcomment, \fBPosition\fPpos, \fBFormExt\fPform, booleanshowInAnimation)"
create animation with full parameterization 
.PP
\fBParameters:\fP
.RS 4
\fIcomment\fP 
.br
\fIpos\fP middle point of animation object 
.br
\fIform\fP form of animation object 
.br
\fIshowInAnimation\fP switch animation on or off 
.RE
.PP

.SS "String desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.advancedModellingFeatures\&.CondQueueAnimation\&.getInternId ()"
gives the internal Id of this animation object\&. 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Implements \fBdesmoj\&.extensions\&.visualization2d\&.animation\&.core\&.simulator\&.ListInterface\fP\&.
.SS "boolean desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.advancedModellingFeatures\&.CondQueueAnimation\&.waitUntil (Conditioncond, \fBSimProcessAnimation\fPe)"
e wird in die CondQueue eingefuegt und wieder entfernt wenn cond erfuellt ist\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcond\fP siehe CondQueue 
.br
\fIe\fP e wird in seinem Ablauf solange unterbrochen bis er wieder aus der Queue entfernt ist\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
