.TH "desmoj.extensions.applicationDomains.harbour.FixedVCtoCBAssignment_Strategy" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.applicationDomains.harbour.FixedVCtoCBAssignment_Strategy \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.core\&.simulator\&.ModelComponent\fP, and \fBdesmoj\&.extensions\&.applicationDomains\&.harbour\&.TransportStrategy\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFixedVCtoCBAssignment_Strategy\fP (\fBModel\fP owner)"
.br
.ti -1c
.RI "\fBTransporterJob\fP[] \fBgetJobs\fP (ProcessQueue transporters, Queue jobs)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBFixedVCtoCBAssignment_Strategy\fP is the strategy that a transporter control uses by the assigning of the jobs to transporters the following way: every transporter (VC) gets the \fC\fBJob\fP\fP that has as origin or destination the crane that transporter is assigned to\&. The \fBFixedVCtoCBAssignment_Strategy\fP implements the method getJobs (ProcessQueue Transporter, Queue Jobs) of the \fCTransportStategy\fP\&. The \fBFixedVCtoCBAssignment_Strategy\fP is derived from ModelComponent\&.
.PP
\fBSee Also:\fP
.RS 4
\fBTransportStrategy\fP 
.PP
\fBTransporterJob\fP 
.PP
\fBT_Control\fP 
.PP
IsJobForVC 
.PP
\fBModelComponent\fP
.RE
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Eugenia Neufeld
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.applicationDomains\&.harbour\&.FixedVCtoCBAssignment_Strategy\&.FixedVCtoCBAssignment_Strategy (\fBModel\fPowner)"
Constructs the \fBFixedVCtoCBAssignment_Strategy\fP that a transporter control uses by the assigning of the jobs to transporters the following way: every transporter (VC) gets the \fC\fBJob\fP\fP that has as origin or destination the crane that transporter is assigned to\&.
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP desmoj\&.Model : The model this \fBFixedVCtoCBAssignment_Strategy\fP is associated to\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBTransporterJob\fP [] desmoj\&.extensions\&.applicationDomains\&.harbour\&.FixedVCtoCBAssignment_Strategy\&.getJobs (ProcessQueuetransporters, Queuejobs)"
This method describes the following way of the assigning the jobs to transporters: every transporter (VC) gets the \fC\fBJob\fP\fP that has as origin or destination the crane that transporter is assigned to\&. This each assignment will be stored in a \fCTranspoterJob\fP\&. All the assignments are used by the transport control\&.
.PP
\fBParameters:\fP
.RS 4
\fIJobs\fP \fCQueue\fP: The queue with the jobs of the transporter control\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fC\fBTransporterJob\fP\fP[] : The pairs of the transporters with the their assigned jobs\&. 
.RE
.PP

.PP
Implements \fBdesmoj\&.extensions\&.applicationDomains\&.harbour\&.TransportStrategy\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
