.TH "desmoj.core.dist.ContDistTriangular" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.core.dist.ContDistTriangular \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.core\&.dist\&.ContDist\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBContDistTriangular\fP (\fBModel\fP owner, String name, double \fBlower\fP, double \fBupper\fP, double \fBpeak\fP, boolean showInReport, boolean showInTrace)"
.br
.ti -1c
.RI "\fBdesmoj\&.core\&.report\&.Reporter\fP \fBcreateReporter\fP ()"
.br
.ti -1c
.RI "double \fBgetLower\fP ()"
.br
.ti -1c
.RI "double \fBgetUpper\fP ()"
.br
.ti -1c
.RI "double \fBgetPeak\fP ()"
.br
.ti -1c
.RI "Double \fBsample\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "double \fBlower\fP"
.br
.ti -1c
.RI "double \fBupper\fP"
.br
.ti -1c
.RI "double \fBpeak\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBDistribution\fP returning triangular distributed double values\&.
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Peter Wueppen 
.PP
.nf
    Licensed under the Apache License, Version 2.0 (the "License"); you
    may not use this file except in compliance with the License. You may
    obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
    implied. See the License for the specific language governing
    permissions and limitations under the License.
.fi
.PP
 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.core\&.dist\&.ContDistTriangular\&.ContDistTriangular (\fBModel\fPowner, Stringname, doublelower, doubleupper, doublepeak, booleanshowInReport, booleanshowInTrace)"
Creates a stream of pseudo random numbers following a triangular distribution\&. The specific lower and upper bounds as well as the most probable value have to be given here at creation time\&.
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP Model : The distribution's owner 
.br
\fIname\fP java\&.lang\&.String : The distribution's name 
.br
\fIlower\fP double : The lowest possibly generated value\&. 
.br
\fIupper\fP double : The highest possibly generated value\&. 
.br
\fIpeak\fP double : The most probable value within the distribution, the peak of the triangle\&. 
.br
\fIshowInReport\fP boolean : Flag for producing reports 
.br
\fIshowInTrace\fP boolean : Flag for producing trace output 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBdesmoj\&.core\&.report\&.Reporter\fP desmoj\&.core\&.dist\&.ContDistTriangular\&.createReporter ()"
Creates the default reporter for the TriangularDist distribution\&.
.PP
\fBReturns:\fP
.RS 4
Reporter : The reporter for the TriangularDist distribution 
.RE
.PP
\fBSee Also:\fP
.RS 4
\fBdesmoj\&.core\&.report\&.ContDistTriangularReporter\fP 
.RE
.PP

.SS "double desmoj\&.core\&.dist\&.ContDistTriangular\&.getLower ()"
Returns the minimum value of this triangular distribution\&.
.PP
\fBReturns:\fP
.RS 4
double : The minimum value of this triangular distribution 
.RE
.PP

.SS "double desmoj\&.core\&.dist\&.ContDistTriangular\&.getPeak ()"
Returns the most likely value of this triangular distribution\&.
.PP
\fBReturns:\fP
.RS 4
double : The most likely value of this triangular distribution 
.RE
.PP

.SS "double desmoj\&.core\&.dist\&.ContDistTriangular\&.getUpper ()"
Returns the maximum value of this triangular distribution\&.
.PP
\fBReturns:\fP
.RS 4
double : The maximum value of this triangular distribution 
.RE
.PP

.SS "Double desmoj\&.core\&.dist\&.ContDistTriangular\&.sample ()"
Returns the next sample from this distribution\&. The value depends upon the seed, the number of values taken from the stream by using this method before and the lower and upper bounds as well as the peak value specified for this distribution\&.
.PP
\fBReturns:\fP
.RS 4
Double : The next triangular distributed sample from this distribution\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "double desmoj\&.core\&.dist\&.ContDistTriangular\&.lower\fC [protected]\fP"
The lowest possible value\&. 
.SS "double desmoj\&.core\&.dist\&.ContDistTriangular\&.peak\fC [protected]\fP"
The peak of the triangle\&. 
.SS "double desmoj\&.core\&.dist\&.ContDistTriangular\&.upper\fC [protected]\fP"
The highest possible value\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
