.TH "desmoj.extensions.experimentation.util.Filename" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.experimentation.util.Filename \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFilename\fP (String name, boolean isDir)"
.br
.ti -1c
.RI "\fBFilename\fP (String name)"
.br
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.ti -1c
.RI "boolean \fBisDirectory\fP ()"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple class representing filenames\&. This class is used in the experiment starter to distinguish strings from filenames which are edited using a file chooser widget\&.
.PP
\fBAuthor:\fP
.RS 4
Nicolas Knaak 
.RE
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.experimentation\&.util\&.Filename\&.Filename (Stringname, booleanisDir)"
Creates a new \fBFilename\fP object
.PP
\fBParameters:\fP
.RS 4
\fIname\fP a valid path or file name 
.br
\fIisDir\fP this flag indicates if the filename specifies a directory 
.RE
.PP

.SS "desmoj\&.extensions\&.experimentation\&.util\&.Filename\&.Filename (Stringname)"
Creates a new \fBFilename\fP that does not refer to a directory\&.
.PP
\fBParameters:\fP
.RS 4
\fIname\fP a valid path or file name 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "String desmoj\&.extensions\&.experimentation\&.util\&.Filename\&.getName ()"

.PP
\fBReturns:\fP
.RS 4
the filename as a string 
.RE
.PP

.SS "boolean desmoj\&.extensions\&.experimentation\&.util\&.Filename\&.isDirectory ()"

.PP
\fBReturns:\fP
.RS 4
true iff this filename specifies a directory 
.RE
.PP

.SS "String desmoj\&.extensions\&.experimentation\&.util\&.Filename\&.toString ()"

.PP
\fBReturns:\fP
.RS 4
the filename as a string 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
