.TH "desmoj.extensions.space3D.IllegalMoveException" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.space3D.IllegalMoveException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.core\&.exception\&.DESMOJException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIllegalMoveException\fP (\fBErrorMessage\fP message)"
.br
.in -1c
.SH "Detailed Description"
.PP 
An \fBIllegalMoveException\fP can be thrown from a move method\&. The reason could be an insufficient length of the track which is shorter than the breaking distance or a maximum speed limit which should be exceeded to reach the destination in time or other reasons why a moving call can't be performed\&. 
.PP
\fBAuthor:\fP
.RS 4
Fred Sun 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.space3D\&.IllegalMoveException\&.IllegalMoveException (\fBErrorMessage\fPmessage)"
Constructs an \fBIllegalMoveException\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fImessage\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
