.TH "desmoj.core.statistic.BoolStatistic" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.core.statistic.BoolStatistic \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.core\&.simulator\&.Reportable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBoolStatistic\fP (\fBModel\fP ownerModel, String name, boolean showInReport, boolean showInTrace)"
.br
.ti -1c
.RI "\fBdesmoj\&.core\&.report\&.Reporter\fP \fBcreateReporter\fP ()"
.br
.ti -1c
.RI "long \fBgetTrueObs\fP ()"
.br
.ti -1c
.RI "double \fBgetTrueRatio\fP ()"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "void \fBupdate\fP (boolean val)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fC\fBBoolStatistic\fP\fP class is providing a statistic analysis about a boolean value\&. Statistics include \fCtrue\fP-ratio and total number of observations\&.
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Soenke Claassen 
.PP
based on DESMO-C from Thomas Schniewind, 1998 
.PP
modified by Ruth Meyer, Johannes Go\*(4bel
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.core\&.statistic\&.BoolStatistic\&.BoolStatistic (\fBModel\fPownerModel, Stringname, booleanshowInReport, booleanshowInTrace)"
Constructor for a \fBBoolStatistic\fP object\&. No connection to a \fC\fBValueSupplier\fP\fP\&.
.PP
\fBParameters:\fP
.RS 4
\fIownerModel\fP Model : The model this \fBBoolStatistic\fP is associated to 
.br
\fIname\fP java\&.lang\&.String : The name of this \fBBoolStatistic\fP object 
.br
\fIshowInReport\fP boolean : Flag for showing the report about \fBBoolStatistic\fP \fBTally\fP\&. 
.br
\fIshowInTrace\fP boolean : Flag for showing the trace output of \fBBoolStatistic\fP \fBTally\fP\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBdesmoj\&.core\&.report\&.Reporter\fP desmoj\&.core\&.statistic\&.BoolStatistic\&.createReporter ()"
Returns a Reporter to produce a report about this \fBBoolStatistic\fP\&.
.PP
\fBReturns:\fP
.RS 4
desmoj\&.report\&.Reporter : The Reporter for this \fBBoolStatistic\fP\&. 
.RE
.PP

.SS "long desmoj\&.core\&.statistic\&.BoolStatistic\&.getTrueObs ()"
Returns the number of \fCtrue\fPs observed so far\&.
.PP
\fBReturns:\fP
.RS 4
long : The number of \fCtrue\fPs observed so far\&. 
.RE
.PP

.SS "double desmoj\&.core\&.statistic\&.BoolStatistic\&.getTrueRatio ()"
Returns the ratio of \fCtrue\fPs per total observations so far\&.
.PP
\fBReturns:\fP
.RS 4
double : The ratio of \fCtrue\fPs per total observations so far\&. 
.RE
.PP

.SS "void desmoj\&.core\&.statistic\&.BoolStatistic\&.reset ()"
Resets this \fC\fBBoolStatistic\fP\fP object by deleting a observations this far\&. 
.SS "void desmoj\&.core\&.statistic\&.BoolStatistic\&.update (booleanval)"
Updates this \fC\fBBoolStatistic\fP\fP object with a boolean double value given as parameter\&.
.PP
\fBParameters:\fP
.RS 4
\fIval\fP boolean : The value with which this \fC\fBBoolStatistic\fP\fP will be updated\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
