.TH "desmoj.core.simulator.ModelParameterManager" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.core.simulator.ModelParameterManager \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBdesmoj\&.core\&.simulator\&.ParameterManager\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBdeclareExperimentParameter\fP (Class<?> type, String name)"
.br
.ti -1c
.RI "void \fBdeclareExperimentParameter\fP (Class<?> type, String name, Object defaultValue)"
.br
.ti -1c
.RI "void \fBdeclareModelParameter\fP (Class<?> type, String name)"
.br
.ti -1c
.RI "void \fBinitializeModelParameter\fP (Class<?> type, String name, Object value)"
.br
.ti -1c
.RI "void \fBassignModelParameter\fP (String name, Object value)"
.br
.ti -1c
.RI "Object \fBgetParameterValue\fP (String name)"
.br
.ti -1c
.RI "Collection< \fBParameter\fP > \fBgetParameters\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface to restrict the functionalities of a parameter-manager to manage model-parameters\&. This Interface should be used as return- type of the \fBModel\fP's methods which return the parameter- manager\&.
.PP
\fBAuthor:\fP
.RS 4
Tim Janz
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Member Function Documentation"
.PP 
.SS "void desmoj\&.core\&.simulator\&.ModelParameterManager\&.assignModelParameter (Stringname, Objectvalue)"
Method to assign a value to a model-parameter declared previously\&.
.PP
\fBParameters:\fP
.RS 4
\fIname\fP the model-parameter's name 
.br
\fIvalue\fP the model-parameter's value 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.core\&.simulator\&.ParameterManager\fP\&.
.SS "void desmoj\&.core\&.simulator\&.ModelParameterManager\&.declareExperimentParameter (Class<?>type, Stringname)"
Method to declare a experiment-parameter\&. The experiment-parameter's declarations are part of the simulation-model\&. The experiment- parameter's assignments are in contrast part of an experiment\&.
.PP
\fBParameters:\fP
.RS 4
\fItype\fP the experiment-parameter's type 
.br
\fIname\fP the experiment-parameter's name 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.core\&.simulator\&.ParameterManager\fP\&.
.SS "void desmoj\&.core\&.simulator\&.ModelParameterManager\&.declareExperimentParameter (Class<?>type, Stringname, ObjectdefaultValue)"
Method to declare a experiment-parameter\&. The experiment-parameter's declarations are part of the simulation-model\&. The experiment- parameter's assignments are in contrast part of an experiment\&. The default value is used, if an experiment dosen't assign a value to this parameter\&.
.PP
\fBParameters:\fP
.RS 4
\fItype\fP the experiment-parameter's type 
.br
\fIname\fP the experiment-parameter's name 
.br
\fIdefaultValue\fP the experiment-parameter's default value 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.core\&.simulator\&.ParameterManager\fP\&.
.SS "void desmoj\&.core\&.simulator\&.ModelParameterManager\&.declareModelParameter (Class<?>type, Stringname)"
Method to declare a model-parameter\&.
.PP
\fBParameters:\fP
.RS 4
\fItype\fP the model-parameter's type 
.br
\fIname\fP the model-parameter's name 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.core\&.simulator\&.ParameterManager\fP\&.
.SS "Collection<\fBParameter\fP> desmoj\&.core\&.simulator\&.ModelParameterManager\&.getParameters ()"
Returns all declared parameters\&.
.PP
\fBReturns:\fP
.RS 4
the parameters 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.core\&.simulator\&.ParameterManager\fP\&.
.SS "Object desmoj\&.core\&.simulator\&.ModelParameterManager\&.getParameterValue (Stringname)"
Returns the value of an experiment- or model-parameter\&. Experiment- and model-parameters are accessible through the model, to be able to use the parameter's values at design-time\&.
.PP
\fBParameters:\fP
.RS 4
\fIname\fP the parameter's name 
.RE
.PP
\fBReturns:\fP
.RS 4
the parameter's value 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.core\&.simulator\&.ParameterManager\fP\&.
.SS "void desmoj\&.core\&.simulator\&.ModelParameterManager\&.initializeModelParameter (Class<?>type, Stringname, Objectvalue)"
Method to initialize (declare and assign) a model-parameter\&.
.PP
\fBParameters:\fP
.RS 4
\fItype\fP the model-parameter's type 
.br
\fIname\fP the model-parameter's name 
.br
\fIvalue\fP the model-parameter's value 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.core\&.simulator\&.ParameterManager\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
