.TH "desmoj.extensions.experimentation.ui.ReportStylerPanel" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.experimentation.ui.ReportStylerPanel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits JPanel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReportStylerPanel\fP ()"
.br
.ti -1c
.RI "void \fBsetReportXSLFile\fP (String filename)"
.br
.ti -1c
.RI "void \fBsetTraceXSLFile\fP (String filename)"
.br
.ti -1c
.RI "void \fBsetReportXMLFile\fP (String filename)"
.br
.ti -1c
.RI "void \fBsetTraceXMLFile\fP (String filename)"
.br
.ti -1c
.RI "void \fBchangeReportParamXSLFile\fP (URL filename)"
.br
.ti -1c
.RI "void \fBchangeTraceParamXSLFile\fP (URL filename)"
.br
.ti -1c
.RI "String \fBloadDialog\fP (String currentFilename)"
.br
.ti -1c
.RI "String \fBsaveDialog\fP (String currentFilename)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBupdateView\fP (String baseFilename, String traceFilename, String reportFilename)"
.br
.ti -1c
.RI "void \fBdeleteXSLFiles\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBReportStylerPanel\fP 
.PP
A JPanel that allows to make selections on which parts of a certain trace or report output shall be shown\&. 
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Gunnar Kiesel, modified by Nicolas Knaak
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.experimentation\&.ui\&.ReportStylerPanel\&.ReportStylerPanel ()"
Creates a new ReportStyler 
.SH "Member Function Documentation"
.PP 
.SS "void desmoj\&.extensions\&.experimentation\&.ui\&.ReportStylerPanel\&.changeReportParamXSLFile (URLfilename)"
replace the report-parameters currently used
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP String: The name of the a new report-parameter XSL file\&. 
.RE
.PP

.SS "void desmoj\&.extensions\&.experimentation\&.ui\&.ReportStylerPanel\&.changeTraceParamXSLFile (URLfilename)"
replace the trace-parameters currently used
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP String: The name of the a new trace-parameter XSL file\&. 
.RE
.PP

.SS "void desmoj\&.extensions\&.experimentation\&.ui\&.ReportStylerPanel\&.deleteXSLFiles ()\fC [protected]\fP"
delete the files copied at the initialisation * 
.SS "void desmoj\&.extensions\&.experimentation\&.ui\&.ReportStylerPanel\&.setReportXMLFile (Stringfilename)"
set the xml-report currently used
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP String: The name of the report-output XML file\&. 
.RE
.PP

.SS "void desmoj\&.extensions\&.experimentation\&.ui\&.ReportStylerPanel\&.setReportXSLFile (Stringfilename)"
set the xsl style sheet to be used for the reports
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP String: The name of the XSL file the report-ouptut is to be formated with\&. 
.RE
.PP

.SS "void desmoj\&.extensions\&.experimentation\&.ui\&.ReportStylerPanel\&.setTraceXMLFile (Stringfilename)"
set the xml-trace currently used
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP String: The name of the trace-output XML file\&. 
.RE
.PP

.SS "void desmoj\&.extensions\&.experimentation\&.ui\&.ReportStylerPanel\&.setTraceXSLFile (Stringfilename)"
set the xsl style sheet to be used for the traces
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP String: The name of the XSL file the trace-ouptut is to be formated with\&. 
.RE
.PP

.SS "void desmoj\&.extensions\&.experimentation\&.ui\&.ReportStylerPanel\&.updateView (StringbaseFilename, StringtraceFilename, StringreportFilename)\fC [protected]\fP"
updates the current view of the Panel with values for baseFilename\&. basefilname gives the path to xml-files without the _trace\&.xml / _report\&.xml endings 

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
