.TH "desmoj.core.simulator.EventTreeList" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.core.simulator.EventTreeList \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.core\&.simulator\&.EventList\fP\&.
.PP
Inherited by \fBdesmoj\&.core\&.simulator\&.RandomizingEventTreeList\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Alternative Implementation of the interface \fC\fBEventList\fP\fP using a tree-based list as a container for the event-notes, yielding both access and removal of event-list entries in O(log n) time\&.
.PP
Disadvantages compared to \fCEventVector\fP include non-thread-safeness (however, discrete Event simulation should never attempt concurrent modifications of the event-list) and the slightly higher memory requirement\&.
.PP
The internal tree-based list is provided by the class \fC\fBorg\&.apache\&.commons\&.collections\&.list\&.TreeList\fP\fP from the Commons Collections package from the Apache Jakarta Commons Project (see http://jakarta.apache.org/commons/index.html)\&. Thus, his product includes software developed by The Apache Software Foundation (http://www.apache.org/)\&. For License see http://www.apache.org/licenses/LICENSE-2.0 (of which a copy can be found in the root directory of this distribtuon)\&.
.PP
\fBSee Also:\fP
.RS 4
\fBorg\&.apache\&.commons\&.collections\&.list\&.TreeList\fP 
.PP
EventVectorList 
.PP
\fBEventNote\fP
.RE
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Tim Lechler, Ruth Meyer, modified by Johannes Göbel
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Member Function Documentation"
.PP 
.SS "String desmoj\&.core\&.simulator\&.EventTreeList\&.toString ()"
Returns a string representing the entries of this tree list in a row\&. The resulting string includes all Event notes in ascending order as they are placed inside the event tree list\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
