.TH "desmoj.extensions.visualization3d.DynamicObject" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization3d.DynamicObject \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
This class contains all elements needed in a scene graph to describe a dynamic object (i\&.e\&. a MovableSpatialObject) in a scene\&.
.PP
A \fBDynamicObject\fP contains several elements: 
.IP "\(bu" 2
a BranchGroup for attach/detach it to/from nodes
.IP "\(bu" 2
a BranchGroup which contains the 3D-model
.IP "\(bu" 2
a TransformGroup which's responsible for the positioning
.IP "\(bu" 2
a TransformGroup which's responsible for the orientation
.IP "\(bu" 2
a \fBMovementPathInterpolator\fP to move the object in time
.IP "\(bu" 2
a Rotation to rotate the object in time
.PP
.PP
\fBAuthor:\fP
.RS 4
Fred Sun 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
