.TH "desmoj.extensions.visualEvents.ControlEventListener" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualEvents.ControlEventListener \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits EventListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract void \fBcontrolEventReceived\fP (\fBControlEvent\fP evt)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is the basic listener interface for all the ControlEvents 
.PP
\fBAuthor:\fP
.RS 4
Fred Sun 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "abstract void desmoj\&.extensions\&.visualEvents\&.ControlEventListener\&.controlEventReceived (\fBControlEvent\fPevt)\fC [pure virtual]\fP"
Invoked when a \fBControlEvent\fP occurred\&. 
.PP
\fBParameters:\fP
.RS 4
\fIevt\fP The occurred \fBControlEvent\fP\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
