.TH "desmoj.core.report.ASCIITableFormatter" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.core.report.ASCIITableFormatter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.core\&.report\&.AbstractTableFormatter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBcloseRow\fP ()"
.br
.ti -1c
.RI "void \fBcloseTable\fP ()"
.br
.ti -1c
.RI "void \fBcloseTableNoTopTag\fP ()"
.br
.ti -1c
.RI "void \fBopenRow\fP ()"
.br
.ti -1c
.RI "void \fBopenTable\fP (String heading)"
.br
.ti -1c
.RI "void \fBwriteCell\fP (String s, int spanning)"
.br
.ti -1c
.RI "void \fBwriteHeading\fP (int i, String s)"
.br
.ti -1c
.RI "void \fBwriteHeadingCell\fP (String s)"
.br
.ti -1c
.RI "void \fBwriteHorizontalRuler\fP ()"
.br
.ti -1c
.RI "void \fBopen\fP (String name)"
.br
.ti -1c
.RI "void \fBclose\fP ()"
.br
.ti -1c
.RI "String \fBgetFileFormat\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A table formatter class for writing simulation output to tab delimited ASCII (e\&.g\&. for import into statistics tools or spreadsheet software)\&.
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Nicolas Knaak
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Member Function Documentation"
.PP 
.SS "void desmoj\&.core\&.report\&.ASCIITableFormatter\&.close ()"
Closes the document by closing open rows and tables and writing the Desmo-J version footer 
.PP
Implements \fBdesmoj\&.core\&.report\&.TableFormatter\fP\&.
.SS "void desmoj\&.core\&.report\&.ASCIITableFormatter\&.closeRow ()"
Writes a newline character
.PP
\fBSee Also:\fP
.RS 4
\fBdesmoj\&.core\&.report\&.TableFormatter::closeRow()\fP 
.RE
.PP

.PP
Implements \fBdesmoj\&.core\&.report\&.TableFormatter\fP\&.
.SS "void desmoj\&.core\&.report\&.ASCIITableFormatter\&.closeTable ()"
Writes 2 newline characters
.PP
\fBSee Also:\fP
.RS 4
\fBdesmoj\&.core\&.report\&.TableFormatter::closeTable()\fP 
.RE
.PP

.PP
Implements \fBdesmoj\&.core\&.report\&.TableFormatter\fP\&.
.SS "void desmoj\&.core\&.report\&.ASCIITableFormatter\&.closeTableNoTopTag ()"
Calls closeTable
.PP
\fBSee Also:\fP
.RS 4
\fBdesmoj\&.core\&.report\&.TableFormatter::closeTableNoTopTag()\fP 
.RE
.PP

.PP
Implements \fBdesmoj\&.core\&.report\&.TableFormatter\fP\&.
.SS "String desmoj\&.core\&.report\&.ASCIITableFormatter\&.getFileFormat ()"

.PP
\fBReturns:\fP
.RS 4
\fC'txt'\fP 
.RE
.PP

.PP
Implements \fBdesmoj\&.core\&.report\&.TableFormatter\fP\&.
.SS "void desmoj\&.core\&.report\&.ASCIITableFormatter\&.open (Stringname)"
Opens the table (without effect for ASCII tables)
.PP
\fBParameters:\fP
.RS 4
\fIname\fP table name (not displayed) 
.RE
.PP

.PP
Implements \fBdesmoj\&.core\&.report\&.TableFormatter\fP\&.
.SS "void desmoj\&.core\&.report\&.ASCIITableFormatter\&.openRow ()"
Only sets rowOpen flag to true
.PP
\fBSee Also:\fP
.RS 4
\fBdesmoj\&.core\&.report\&.TableFormatter::openRow()\fP 
.RE
.PP

.PP
Implements \fBdesmoj\&.core\&.report\&.TableFormatter\fP\&.
.SS "void desmoj\&.core\&.report\&.ASCIITableFormatter\&.openTable (Stringheading)"
Opens the table by writing the heading and a newline character
.PP
\fBParameters:\fP
.RS 4
\fIheading\fP heading to write 
.RE
.PP
\fBSee Also:\fP
.RS 4
\fBdesmoj\&.core\&.report\&.TableFormatter::openTable\fP(java\&.lang\&.String) 
.RE
.PP

.PP
Implements \fBdesmoj\&.core\&.report\&.TableFormatter\fP\&.
.SS "void desmoj\&.core\&.report\&.ASCIITableFormatter\&.writeCell (Strings, intspanning)"
Writes the given string followed by a separator character
.PP
\fBParameters:\fP
.RS 4
\fIs\fP string to write 
.br
\fIspanning\fP number of cells to span (ignored) 
.RE
.PP
\fBSee Also:\fP
.RS 4
\fBdesmoj\&.core\&.report\&.TableFormatter::writeCell\fP(java\&.lang\&.String) 
.RE
.PP

.PP
Implements \fBdesmoj\&.core\&.report\&.TableFormatter\fP\&.
.SS "void desmoj\&.core\&.report\&.ASCIITableFormatter\&.writeHeading (inti, Strings)"
Writes the given heading enclosed in asterisks followed by a newline character\&. The integer parameter's value has no effect on ASCII tables\&.
.PP
\fBParameters:\fP
.RS 4
\fIi\fP heading size (without effect) 
.br
\fIs\fP heading to write 
.RE
.PP
\fBSee Also:\fP
.RS 4
\fBdesmoj\&.core\&.report\&.TableFormatter::writeHeading\fP(int, java\&.lang\&.String) 
.RE
.PP

.PP
Implements \fBdesmoj\&.core\&.report\&.TableFormatter\fP\&.
.SS "void desmoj\&.core\&.report\&.ASCIITableFormatter\&.writeHeadingCell (Strings)"
Writes a heading cell\&. Heading cells are not formatted in a special way in ASCII tables\&.
.PP
\fBParameters:\fP
.RS 4
\fIs\fP heading to write 
.RE
.PP
\fBSee Also:\fP
.RS 4
\fBdesmoj\&.core\&.report\&.TableFormatter::writeHeadingCell\fP(java\&.lang\&.String) 
.RE
.PP

.PP
Implements \fBdesmoj\&.core\&.report\&.TableFormatter\fP\&.
.SS "void desmoj\&.core\&.report\&.ASCIITableFormatter\&.writeHorizontalRuler ()"
Writes a line of asterisks and a newline\&.
.PP
\fBSee Also:\fP
.RS 4
\fBdesmoj\&.core\&.report\&.TableFormatter::writeHorizontalRuler()\fP 
.RE
.PP

.PP
Implements \fBdesmoj\&.core\&.report\&.TableFormatter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
