.TH "desmoj.extensions.visualization2d.engine.command.Command" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization2d.engine.command.Command \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits desmoj\&.extensions\&.visualization2d\&.engine\&.command\&.CommandFrame\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommand\fP (String cmd, String remark, \fBParameter\fP[] parameter)"
.br
.ti -1c
.RI "void \fBexecute\fP (\fBModel\fP model)  throws CommandException, ModelException"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBCommand\fP \fBgetCommandInit\fP (String cmd, long initTime)  throws CommandException"
.br
.ti -1c
.RI "static \fBCommand\fP \fBgetCommandTime\fP (String cmd, long time)  throws CommandException"
.br
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBCommand\fP extends CommandFrame and implements \fBexecute()\fP\&. \fBCommand\fP is the connection to animation\&.model\&.
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
christian.mueller@th-wildau.de For information about subproject: desmoj\&.extensions\&.visualization2d please have a look at: http://www.th-wildau.de/cmueller/Desmo-J/Visualization2d/
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.visualization2d\&.engine\&.command\&.Command\&.Command (Stringcmd, Stringremark, \fBParameter\fP[]parameter)"
Constructor for CommandFrame, used for template generation used by CommandFactory\&.createCommand(cmd, remark, parameter)\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcmd\fP command-name 
.br
\fIremark\fP remark about template 
.br
\fIparameter\fP Array of \fBParameter\fP's where each parameter must have a different type 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void desmoj\&.extensions\&.visualization2d\&.engine\&.command\&.Command\&.execute (\fBModel\fPmodel) throws \fBCommandException\fP, \fBModelException\fP"
This method describes for every command-type, how it's modeled in animation\&.model\&.Model\&. this method must include a case for every command-type\&. 
.SS "static \fBCommand\fP desmoj\&.extensions\&.visualization2d\&.engine\&.command\&.Command\&.getCommandInit (Stringcmd, longinitTime) throws \fBCommandException\fP\fC [static]\fP"
Get a clone of command-template with name cmd for init-phase 
.PP
\fBParameters:\fP
.RS 4
\fIcmd\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
clone of command-template with name 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBCommandException\fP\fP 
.RE
.PP

.SS "static \fBCommand\fP desmoj\&.extensions\&.visualization2d\&.engine\&.command\&.Command\&.getCommandTime (Stringcmd, longtime) throws \fBCommandException\fP\fC [static]\fP"
Get a clone of command-template with name cmd for run-phase time-value 
.PP
\fBParameters:\fP
.RS 4
\fIcmd\fP 
.br
\fItime\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
clone of command-template 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBCommandException\fP\fP 
.RE
.PP

.SS "static void desmoj\&.extensions\&.visualization2d\&.engine\&.command\&.Command\&.main (String[]args)\fC [static]\fP"
only for testing 
.PP
\fBParameters:\fP
.RS 4
\fIargs\fP no args 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
