.TH "desmoj.extensions.applicationDomains.harbour.ChooseBlockYardStrategy" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.applicationDomains.harbour.ChooseBlockYardStrategy \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBdesmoj\&.extensions\&.applicationDomains\&.harbour\&.MostFreePlaceBlockYardStrategy\fP, and \fBdesmoj\&.extensions\&.applicationDomains\&.harbour\&.RandomBlockYardStrategy\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlock\fP \fBgetBlock\fP (\fBBlock\fP[] blocks)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A \fBChooseBlockYardStrategy\fP is an interface and presents the strategy that is used by the \fC\fBYard\fP\fP to find a certain block to store or retrieve a container there\&. The method \fBgetBlock(Block[] blocks)\fP that gives the needed block must be implemented by the user in a class that implements \fBTransportStrategy\fP to define the strategy which will be used by the yard\&. \fBChooseBlockYardStrategy\fP is part of the strategy design pattern as described in [Gamm97] page 333 in which it represents the strategy interface\&.
.PP
\fBSee Also:\fP
.RS 4
\fBBlock\fP 
.PP
\fBYard\fP
.RE
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Eugenia Neufeld
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBBlock\fP desmoj\&.extensions\&.applicationDomains\&.harbour\&.ChooseBlockYardStrategy\&.getBlock (\fBBlock\fP[]blocks)"
Implement this method in a class that implements this interface to define the algorithm of the strategy that finds a certain block and is used by the yard\&.
.PP
\fBParameters:\fP
.RS 4
\fIblocks\fP \fC\fBBlock\fP\fP[] : The array of the blocks\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fC\fBBlock\fP\fP[] : the found block\&. 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.extensions\&.applicationDomains\&.harbour\&.RandomBlockYardStrategy\fP, and \fBdesmoj\&.extensions\&.applicationDomains\&.harbour\&.MostFreePlaceBlockYardStrategy\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
