.TH "desmoj.extensions.chaining.Sink< E extends Entity >" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.chaining.Sink< E extends Entity > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Station< E >, and HasPredecessor< E >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSink\fP (int incomingBufferQueueCapacity, int maxEntitiesToHandle, int parallelHandledEntities, NumericalDist<?> setupTime, NumericalDist<?> serviceTime, NumericalDist<?> recoveryTime, \fBModel\fP owner, String name, boolean showInReport, boolean showInTrace)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBSmartReporter\fP \fBcreateDefaultReporter\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The Sink represents the end of a production line and has no successor\&. The Sink inherits all behavior from the Station except the transport time\&.
.PP
\fBParameters:\fP
.RS 4
\fI<E>\fP The Entitiy which can be handled by the Sink
.RE
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Christian Mentz
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.chaining\&.Sink< E extends \fBEntity\fP >\&.Sink (intincomingBufferQueueCapacity, intmaxEntitiesToHandle, intparallelHandledEntities, NumericalDist<?>setupTime, NumericalDist<?>serviceTime, NumericalDist<?>recoveryTime, \fBModel\fPowner, Stringname, booleanshowInReport, booleanshowInTrace)"
This Constructor sets the given times, initializes the queues and fills the free service capacity queue\&. If a given int is lower than zero the sink assumes that there is no restriction\&. This applies to incomingBufferQueueCapacity, maxEntitiesToHandle, parallelHandledEntities
.PP
\fBParameters:\fP
.RS 4
\fIincomingBufferQueueCapacity\fP the capatiy of the income queue 
.br
\fImaxEntitiesToHandle\fP the number of max entities the station can handle 
.br
\fIparallelHandledEntities\fP the number of max parallel entities a station can handle 
.br
\fIsetupTime\fP the time the station needs to set up 
.br
\fIserviceTime\fP the time the station needs for the service 
.br
\fIrecoveryTime\fP the time the station needs to recover 
.br
\fIowner\fP the model owner 
.br
\fIname\fP the name of the station 
.br
\fIshowInReport\fP should this construct be in the report 
.br
\fIshowInTrace\fP should this construct be in the trace 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
