.TH "desmoj.core.report.SimulationRunReporter" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.core.report.SimulationRunReporter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.core\&.report\&.TableReporter\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSimulationRunReporterProvider\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSimulationRunReporter\fP (\fBModel\fP model)"
.br
.ti -1c
.RI "String[][] \fBgetEntryTable\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "long \fBstartedAtSystemMillis\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A reporter about a simulation run, including information like simulation duration, computation duration and last reset\&.
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Tim Lechler, Johannes Go\*(4bel
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.core\&.report\&.SimulationRunReporter\&.SimulationRunReporter (\fBModel\fPmodel)"
Creates a simulation run reporter for the given model\&.
.PP
\fBParameters:\fP
.RS 4
\fImodel\fP Model : The model to report about\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "String [][] desmoj\&.core\&.report\&.SimulationRunReporter\&.getEntryTable ()\fC [virtual]\fP"
Returns the output of the \fBSimulationRunReporter\fP\&.
.PP
\fBReturns:\fP
.RS 4
String[][] : The simulation data to be written into the report\&. 
.RE
.PP

.PP
Implements \fBdesmoj\&.core\&.report\&.TableReporter\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "long desmoj\&.core\&.report\&.SimulationRunReporter\&.startedAtSystemMillis\fC [protected]\fP"
System time at which the simulation has started 

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
