.TH "desmoj.core.simulator.ExpProgressBar" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.core.simulator.ExpProgressBar \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits JFrame\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExpProgressBar\fP (\fBExperiment\fP experiment)"
.br
.ti -1c
.RI "\fBExperiment\fP \fBgetExperiment\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final int \fBHALF_A_SECOND\fP = 500"
.br
.in -1c
.SH "Detailed Description"
.PP 
The progress bar to display the progress of the experiment\&.
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Soenke Claassen
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&.
.PP
\&.ignore 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.core\&.simulator\&.ExpProgressBar\&.ExpProgressBar (\fBExperiment\fPexperiment)"
Constructs an \fBExpProgressBar\fP for an \fC\fBExperiment\fP\fP to display its progress on the screen\&.
.PP
\fBParameters:\fP
.RS 4
\fIexperiment\fP \fBExperiment\fP : The experiment which progress will be displayed of the progress bar\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBExperiment\fP desmoj\&.core\&.simulator\&.ExpProgressBar\&.getExperiment ()"
Returns the \fC\fBExperiment\fP\fP this progress bar monitors\&.
.PP
\fBReturns:\fP
.RS 4
desmoj\&.Experiment : the \fC\fBExperiment\fP\fP this progress bar monitors\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "final int desmoj\&.core\&.simulator\&.ExpProgressBar\&.HALF_A_SECOND = 500\fC [static]\fP"
A constant defining half a second as 500 milliseconds\&. Every half a second the progress bar will be updated\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
