.TH "desmoj.extensions.experimentation.util.ExperimentParameterReporter" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.experimentation.util.ExperimentParameterReporter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.core\&.report\&.TableReporter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExperimentParameterReporter\fP (ExperimentRunner\&.ReportProvider ep)"
.br
.ti -1c
.RI "String[][] \fBgetEntryTable\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A reporter for the model and experiment parameters of a certain experiment run represented by an experiment runner\&. Returned by experimentRunner\&.getReporter()\&. The groupID of experiment reporters is 10 which makes the appear in the report as one of the last elements\&.
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Nicolas Knaak
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.experimentation\&.util\&.ExperimentParameterReporter\&.ExperimentParameterReporter (ExperimentRunner\&.ReportProviderep)"
Creates a new reporter for experiment runner e
.PP
\fBParameters:\fP
.RS 4
\fIe\fP experiment runner to report 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "String [][] desmoj\&.extensions\&.experimentation\&.util\&.ExperimentParameterReporter\&.getEntryTable ()\fC [virtual]\fP"
Returns the table of entries : entryTable 0 1 0 expParamName[0] expParamVal[0] 1 expParamName[1] expParamVal[1] \&.\&.\&. numExpParams +1 modelParamName[0] modelParamVal[0] +2 modelParamName[1] modelParamVal[1] +numModParams
.PP
\fBReturns:\fP
.RS 4
table of entries (model parameters and experiment settings)\&. 
.RE
.PP

.PP
Implements \fBdesmoj\&.core\&.report\&.TableReporter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
