.TH "desmoj.extensions.visualization2d.engine.model.Container< E >" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization2d.engine.model.Container< E > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Basic\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBContainer\fP (\fBModel\fP model, String id)"
.br
.ti -1c
.RI "\fBModel\fP \fBgetModel\fP ()"
.br
.ti -1c
.RI "\fBGrafic\fP \fBgetGrafic\fP ()"
.br
.ti -1c
.RI "String \fBgetId\fP ()"
.br
.ti -1c
.RI "boolean \fBaddToContainer\fP (String entityId, E value)"
.br
.ti -1c
.RI "boolean \fBremoveFromContainer\fP (String entityId, long time)  throws ModelException"
.br
.ti -1c
.RI "E \fBgetFromContainer\fP (String id)"
.br
.ti -1c
.RI "boolean \fBcontainsInContainer\fP (String entityId)"
.br
.ti -1c
.RI "String[] \fBgetAllContentFromContainer\fP ()"
.br
.ti -1c
.RI "int \fBsizeOfContainer\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "Hashtable< String, E > \fBcontainer\fP"
.br
.ti -1c
.RI "String \fBid\fP"
.br
.ti -1c
.RI "\fBdesmoj\&.extensions\&.visualization2d\&.engine\&.modelGrafic\&.Grafic\fP \fBgrafic\fP"
.br
.ti -1c
.RI "\fBModel\fP \fBmodel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Basis-implementation of an container of entities It's a hashtable\&.
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
christian.mueller@th-wildau.de For information about subproject: desmoj\&.extensions\&.visualization2d please have a look at: http://www.th-wildau.de/cmueller/Desmo-J/Visualization2d/
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&.
.PP
\fBParameters:\fP
.RS 4
\fI<E>\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "boolean desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Container< E >\&.addToContainer (StringentityId, Evalue)"
add an entity value with id entityId in to container 
.PP
\fBParameters:\fP
.RS 4
\fIentityId\fP 
.br
\fIvalue\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
true, when successful 
.RE
.PP

.SS "boolean desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Container< E >\&.containsInContainer (StringentityId)"
check if it contains a entity with entityId 
.PP
\fBParameters:\fP
.RS 4
\fIentityId\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
true, when successful 
.RE
.PP

.SS "String [] desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Container< E >\&.getAllContentFromContainer ()"
get an array with id's of all entities in container 
.PP
\fBReturns:\fP
.RS 4
array with id's 
.RE
.PP

.SS "E desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Container< E >\&.getFromContainer (Stringid)"
get entity with id, which is in container 
.PP
\fBParameters:\fP
.RS 4
\fIid\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
entity 
.RE
.PP

.SS "boolean desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Container< E >\&.removeFromContainer (StringentityId, longtime) throws \fBModelException\fP"
remove entityId from container\&. ???? time is not used ????? 
.PP
\fBParameters:\fP
.RS 4
\fIentityId\fP 
.br
\fItime\fP not used 
.RE
.PP
\fBReturns:\fP
.RS 4
true, when successful 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBModelException\fP\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
