.TH "desmoj.extensions.visualization2d.engine.model.Process" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization2d.engine.model.Process \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Basic\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProcess\fP (\fBModel\fP model, String id, int anz_ResourceEntities, int anz_ProcessEntities, String listId)"
.br
.ti -1c
.RI "\fBModel\fP \fBgetModel\fP ()"
.br
.ti -1c
.RI "String \fBgetId\fP ()"
.br
.ti -1c
.RI "void \fBsetName\fP (String name)"
.br
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.ti -1c
.RI "String \fBgetListId\fP ()"
.br
.ti -1c
.RI "String[] \fBgetProcessEntity\fP ()"
.br
.ti -1c
.RI "void \fBsetProzessEntity\fP (int index, String entityId, long time)  throws ModelException"
.br
.ti -1c
.RI "void \fBunsetProzessEntity\fP (int index, String entityId, long time)  throws ModelException"
.br
.ti -1c
.RI "void \fBsetProzessEntity\fP (String entityId, long time)  throws ModelException"
.br
.ti -1c
.RI "void \fBunsetProzessEntity\fP (String entityId, long time)  throws ModelException"
.br
.ti -1c
.RI "String[] \fBgetResourceEntity\fP ()"
.br
.ti -1c
.RI "void \fBsetResourceEntity\fP (int index, String entityId, long time)  throws ModelException"
.br
.ti -1c
.RI "void \fBunsetResourceEntity\fP (int index, String entityId, long time)  throws ModelException"
.br
.ti -1c
.RI "void \fBsetResourceEntity\fP (String entityId, long time)  throws ModelException"
.br
.ti -1c
.RI "void \fBunsetResourceEntity\fP (String entityId, long time)  throws ModelException"
.br
.ti -1c
.RI "void \fBprintEntries\fP ()"
.br
.ti -1c
.RI "\fBGrafic\fP \fBcreateGrafic\fP (String viewId, int x, int y, String defaultEntityTypeId)"
.br
.ti -1c
.RI "\fBGrafic\fP \fBgetGrafic\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Working-station with a line of resource-entities and a line of processed entities
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
christian.mueller@th-wildau.de For information about subproject: desmoj\&.extensions\&.visualization2d please have a look at: http://www.th-wildau.de/cmueller/Desmo-J/Visualization2d/
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Process\&.Process (\fBModel\fPmodel, Stringid, intanz_ResourceEntities, intanz_ProcessEntities, StringlistId)"

.PP
\fBParameters:\fP
.RS 4
\fImodel\fP used animation\&.model\&.Model 
.br
\fIid\fP processId 
.br
\fIanz_ResourceEntities\fP max possible resource-entities in one time 
.br
\fIanz_ProcessEntities\fP max possible processed-entities in one time 
.br
\fIlistId\fP optional id of a list, which include all processed entities before 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBGrafic\fP desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Process\&.createGrafic (StringviewId, intx, inty, StringdefaultEntityTypeId)"
create a ProcessGrafic 
.PP
\fBParameters:\fP
.RS 4
\fIviewId\fP Id of view 
.br
\fIx\fP middlepoint x-coordinate 
.br
\fIy\fP middlepoint y-coordinate 
.br
\fIdefaultEntityTypeId\fP for sizing 
.RE
.PP
\fBReturns:\fP
.RS 4
ProcessGrafic 
.RE
.PP

.SS "\fBGrafic\fP desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Process\&.getGrafic ()"
get ProcessGrafic, created before 
.PP
Implements \fBdesmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Basic\fP\&.
.SS "String desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Process\&.getId ()"
get id of process-station 
.PP
Implements \fBdesmoj\&.extensions\&.visualization2d\&.engine\&.orga\&.ClassBasic\fP\&.
.SS "String desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Process\&.getListId ()"
get id of list, where are the processed entities are before this may be null 
.PP
\fBReturns:\fP
.RS 4
ListId 
.RE
.PP

.SS "String desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Process\&.getName ()"
get name of process-station 
.PP
Implements \fBdesmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Basic\fP\&.
.SS "String [] desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Process\&.getProcessEntity ()"
get array with id's of all processed entities 
.PP
\fBReturns:\fP
.RS 4
array of processed entities 
.RE
.PP

.SS "String [] desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Process\&.getResourceEntity ()"
get array with id's of all resource-entities 
.PP
\fBReturns:\fP
.RS 4
array of resource-entities 
.RE
.PP

.SS "void desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Process\&.printEntries ()"
makes a control-print on System\&.out 
.SS "void desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Process\&.setName (Stringname)"
set name of process-station 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP 
.RE
.PP

.SS "void desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Process\&.setProzessEntity (intindex, StringentityId, longtime) throws \fBModelException\fP"
set entityId on position index as processed entity 
.PP
\fBParameters:\fP
.RS 4
\fIindex\fP 0 <= index < anz_ProcessEntities 
.br
\fIentityId\fP 
.br
\fItime\fP time of operating 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBModelException\fP\fP 
.RE
.PP

.SS "void desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Process\&.setProzessEntity (StringentityId, longtime) throws \fBModelException\fP"
set entityId on next free position as processed entity This method is normally used 
.PP
\fBParameters:\fP
.RS 4
\fIentityId\fP 
.br
\fItime\fP time of operation 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBModelException\fP\fP 
.RE
.PP

.SS "void desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Process\&.setResourceEntity (intindex, StringentityId, longtime) throws \fBModelException\fP"
set entityId on position index as resource entity 
.PP
\fBParameters:\fP
.RS 4
\fIindex\fP 0 <= index < anz_ResourceEntities 
.br
\fIentityId\fP 
.br
\fItime\fP time of operation 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBModelException\fP\fP 
.RE
.PP

.SS "void desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Process\&.setResourceEntity (StringentityId, longtime) throws \fBModelException\fP"
add resource entity on next free position 
.PP
\fBParameters:\fP
.RS 4
\fIentityId\fP 
.br
\fItime\fP time of operation 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBModelException\fP\fP 
.RE
.PP

.SS "void desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Process\&.unsetProzessEntity (intindex, StringentityId, longtime) throws \fBModelException\fP"
remove entity from position index as processed entity 
.PP
\fBParameters:\fP
.RS 4
\fIindex\fP 0 <= index < anz_ProcessEntities 
.br
\fIentityId\fP 
.br
\fItime\fP time of operating 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBModelException\fP\fP 
.RE
.PP

.SS "void desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Process\&.unsetProzessEntity (StringentityId, longtime) throws \fBModelException\fP"
remove entityId from processed entity This method is normally used\&. 
.PP
\fBParameters:\fP
.RS 4
\fIentityId\fP 
.br
\fItime\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBModelException\fP\fP 
.RE
.PP

.SS "void desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Process\&.unsetResourceEntity (intindex, StringentityId, longtime) throws \fBModelException\fP"
remove entity from position index as resource entity 
.PP
\fBParameters:\fP
.RS 4
\fIindex\fP 0 <= index < anz_ResourceEntities 
.br
\fIentityId\fP 
.br
\fItime\fP time of operation 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBModelException\fP\fP 
.RE
.PP

.SS "void desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Process\&.unsetResourceEntity (StringentityId, longtime) throws \fBModelException\fP"
remove resource entity with entityId 
.PP
\fBParameters:\fP
.RS 4
\fIentityId\fP 
.br
\fItime\fP time of operation 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBModelException\fP\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
