.TH "desmoj.extensions.grafic.util.HistogramDataSetAdapter" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.grafic.util.HistogramDataSetAdapter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits DefaultCategoryDataset\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHistogramDataSetAdapter\fP (\fBHistogram\fP histogram, Locale locale)"
.br
.ti -1c
.RI "\fBHistogramDataSetAdapter\fP (\fBHistogramAccumulate\fP histogram, Locale locale)"
.br
.ti -1c
.RI "TimeUnit \fBgetAccumulateTimeUnit\fP ()"
.br
.ti -1c
.RI "String \fBgetCategoryAxisLabel\fP ()"
.br
.ti -1c
.RI "String \fBgetObservationAxisLabel\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class to convert DesmoJ histogram or histogramAccumulate data into jFreeChart format\&. When in DesmoJ dataset getShowTimeSpansInReport() is set, the data values are interpreted as a timespan in a appropriate time unit\&. 
.PP
\fBAuthor:\fP
.RS 4
Christian 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.grafic\&.util\&.HistogramDataSetAdapter\&.HistogramDataSetAdapter (\fBHistogram\fPhistogram, Localelocale)"
convert a DesmoJ histogram to a org\&.jfree\&.data\&.category\&.DefaultCategoryDataset\&. When histogram\&.getShowTimeSpansInReport() is set, the cell ranges are displayed as timespans\&. 
.PP
\fBParameters:\fP
.RS 4
\fIhistogram\fP 
.RE
.PP

.SS "desmoj\&.extensions\&.grafic\&.util\&.HistogramDataSetAdapter\&.HistogramDataSetAdapter (\fBHistogramAccumulate\fPhistogram, Localelocale)"
convert a DesmoJ histogramAccumulate to a org\&.jfree\&.data\&.category\&.DefaultCategoryDataset\&. When histogram\&.getShowTimeSpansInReport() is set, the cell ranges are displayed as timespans\&. The observation timespan is converted into a double with timeUnit\&. 
.PP
\fBParameters:\fP
.RS 4
\fIhistogram\fP 
.br
\fItimeUnit\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "TimeUnit desmoj\&.extensions\&.grafic\&.util\&.HistogramDataSetAdapter\&.getAccumulateTimeUnit ()"
an appropriate rangeTime Unit of given HistogramAccumulate\&. is determined in constructor in HistogramAccumulate case\&. 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SS "String desmoj\&.extensions\&.grafic\&.util\&.HistogramDataSetAdapter\&.getCategoryAxisLabel ()"
get category axis label 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SS "String desmoj\&.extensions\&.grafic\&.util\&.HistogramDataSetAdapter\&.getObservationAxisLabel ()"
get observation axis label 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
