.TH "desmoj.extensions.space3D.Rotation" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.space3D.Rotation \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRotation\fP (boolean[] axis, double angle, double duration)"
.br
.ti -1c
.RI "double \fBgetAngle\fP ()"
.br
.ti -1c
.RI "boolean[] \fBgetAxis\fP ()"
.br
.ti -1c
.RI "double \fBgetDuration\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBRotation\fP class specifies a rotation with its axis and angle\&.
.PP
\fBAuthor:\fP
.RS 4
Fred Sun 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.space3D\&.Rotation\&.Rotation (boolean[]axis, doubleangle, doubleduration)"
Constructs a \fBRotation\fP object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIaxis\fP A 3 elements boolean array to indicate which about which axis the rotation should be\&. The elements refer to the axis X,Y and Z\&. The combination of more than one axis isn't supported\&. 
.br
\fIangle\fP The angle of the rotation in radians\&. 
.br
\fIduration\fP The duration of this rotation\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "double desmoj\&.extensions\&.space3D\&.Rotation\&.getAngle ()"
Gets the angle of the rotation\&. 
.PP
\fBReturns:\fP
.RS 4
The angle of the rotation in radians\&. 
.RE
.PP

.SS "boolean [] desmoj\&.extensions\&.space3D\&.Rotation\&.getAxis ()"
Gets the axis the rotation is about\&. 
.PP
\fBReturns:\fP
.RS 4
A 3 elements boolean array which associate to the X,Y and Z axis the rotation is about\&. True stands for the rotation about this axis\&. 
.RE
.PP

.SS "double desmoj\&.extensions\&.space3D\&.Rotation\&.getDuration ()"
Gets the duration of this rotation\&. 
.PP
\fBReturns:\fP
.RS 4
the duration in double\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
