.TH "desmoj.extensions.visualization2d.animation.core.simulator.ListInterface" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization2d.animation.core.simulator.ListInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBdesmoj\&.extensions\&.visualization2d\&.animation\&.core\&.advancedModellingFeatures\&.CondQueueAnimation\fP, \fBdesmoj\&.extensions\&.visualization2d\&.animation\&.core\&.simulator\&.ProcessQueueAnimation< P extends SimProcessAnimation >\fP, and \fBdesmoj\&.extensions\&.visualization2d\&.animation\&.core\&.simulator\&.QueueAnimation< P extends EntityAnimation >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBgetInternId\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
