.TH "desmoj.extensions.visualEvents.CreateVisibleObjectEvent" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualEvents.CreateVisibleObjectEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.extensions\&.visualEvents\&.VisualEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCreateVisibleObjectEvent\fP (Object source, String objectName, String type, boolean movable, \fBTimeInstant\fP occurredTime)"
.br
.ti -1c
.RI "String \fBgetVisualModel\fP ()"
.br
.ti -1c
.RI "boolean \fBisMovable\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This event occurs when a SpatialObject (or MovableSpatialObject) is created\&. 
.PP
\fBAuthor:\fP
.RS 4
Fred Sun 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.visualEvents\&.CreateVisibleObjectEvent\&.CreateVisibleObjectEvent (Objectsource, StringobjectName, Stringtype, booleanmovable, \fBTimeInstant\fPoccurredTime)"
Constructs a \fBCreateVisibleObjectEvent\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsource\fP The object on which the event initially occurred\&. 
.br
\fIobjectName\fP The object which is created\&. 
.br
\fItype\fP The type of the SpatialObject to be created\&. 
.br
\fImovable\fP Indicates whether the SpatialObject is a MovableSpatialObject or not\&. 
.br
\fIoccurredTime\fP The TimeInstant when the event occurred\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "String desmoj\&.extensions\&.visualEvents\&.CreateVisibleObjectEvent\&.getVisualModel ()"
Gets the type of the SpatialObject to be created\&. 
.PP
\fBReturns:\fP
.RS 4
The type of the SpatialObject\&. 
.RE
.PP

.SS "boolean desmoj\&.extensions\&.visualEvents\&.CreateVisibleObjectEvent\&.isMovable ()"
Returns true if the SpatialObject to be created is a MovableSpatialObject\&. Else false\&. 
.PP
\fBReturns:\fP
.RS 4
True if the Object is a MovableSpatialObject\&. Else, false\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
