.TH "desmoj.core.dist.ContDistExponential" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.core.dist.ContDistExponential \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.core\&.dist\&.ContDist\fP\&.
.PP
Inherited by \fBdesmoj\&.core\&.dist\&.ContDistErlang\fP, \fBdesmoj\&.core\&.dist\&.ContDistWeibull\fP, and \fBdesmoj\&.core\&.dist\&.RealDistExponential\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBContDistExponential\fP (\fBModel\fP owner, String name, double \fBmean\fP, boolean showInReport, boolean showInTrace)"
.br
.ti -1c
.RI "\fBdesmoj\&.core\&.report\&.Reporter\fP \fBcreateReporter\fP ()"
.br
.ti -1c
.RI "double \fBgetMean\fP ()"
.br
.ti -1c
.RI "Double \fBsample\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "double \fBmean\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Negative-exponentially distributed stream of pseudo random numbers of type double\&.
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Tim Lechler 
.PP
.nf
    Licensed under the Apache License, Version 2.0 (the "License"); you
    may not use this file except in compliance with the License. You may
    obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
    implied. See the License for the specific language governing
    permissions and limitations under the License.
.fi
.PP
 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.core\&.dist\&.ContDistExponential\&.ContDistExponential (\fBModel\fPowner, Stringname, doublemean, booleanshowInReport, booleanshowInTrace)"
Constructs a simple negative-exponentially distributed pseudo random generator with the given value as mean of the distribution\&. Only positive values are allowed\&.
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP Model : The distribution's owner 
.br
\fIname\fP java\&.lang\&.String : The distribution's name 
.br
\fImean\fP double : The mean value for this distribution 
.br
\fIshowInReport\fP boolean : Flag for producing reports 
.br
\fIshowInTrace\fP boolean : Flag for producing trace output 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBdesmoj\&.core\&.report\&.Reporter\fP desmoj\&.core\&.dist\&.ContDistExponential\&.createReporter ()"
Creates the default reporter for the \fBRealDistExponential\fP distribution\&.
.PP
\fBReturns:\fP
.RS 4
Reporter : The reporter for the \fBRealDistExponential\fP distribution 
.RE
.PP
\fBSee Also:\fP
.RS 4
\fBdesmoj\&.core\&.report\&.ContDistExponReporter\fP 
.RE
.PP

.SS "double desmoj\&.core\&.dist\&.ContDistExponential\&.getMean ()"
Returns the mean value of the negative-exponential distribution\&.
.PP
\fBReturns:\fP
.RS 4
double : the mean value of the negative-exponential distribution 
.RE
.PP

.SS "Double desmoj\&.core\&.dist\&.ContDistExponential\&.sample ()"
Returns the next negative exponential pseudo random number\&. The algorithm used is taken from DESMO-C from Thomas Schniewind [Schni98] Volume 2, page 221, file realdist\&.cc\&. It has been adapted to Java and extended to handle antithetic random numbers if antithetic mode is switched on\&.
.PP
\fBReturns:\fP
.RS 4
Double : The next negative exponential pseudo random number 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "double desmoj\&.core\&.dist\&.ContDistExponential\&.mean\fC [protected]\fP"
The mean value of the negative-exponential distribution\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
