.TH "desmoj.core.report.ContDistConstantReporter" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.core.report.ContDistConstantReporter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.core\&.report\&.DistributionReporter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBContDistConstantReporter\fP (\fBdesmoj\&.core\&.simulator\&.Reportable\fP informationSource)"
.br
.ti -1c
.RI "java\&.lang\&.String[] \fBgetEntries\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Reports all information about a ContDistConstant distribution\&.
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Tim Lechler 
.PP
.nf
    Licensed under the Apache License, Version 2.0 (the "License"); you
    may not use this file except in compliance with the License. You may
    obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
    implied. See the License for the specific language governing
    permissions and limitations under the License.
.fi
.PP
 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.core\&.report\&.ContDistConstantReporter\&.ContDistConstantReporter (\fBdesmoj\&.core\&.simulator\&.Reportable\fPinformationSource)"
Creates a new \fBContDistConstantReporter\fP\&.
.PP
\fBParameters:\fP
.RS 4
\fIinformationSource\fP \fBdesmoj\&.core\&.simulator\&.Reportable\fP : The ContDistConstant to report about 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "java\&.lang\&.String [] desmoj\&.core\&.report\&.ContDistConstantReporter\&.getEntries ()\fC [virtual]\fP"
Returns the array of strings containing all information about the ContDistConstant distribution\&.
.PP
\fBReturns:\fP
.RS 4
java\&.lang\&.String[] : The array of Strings containing all information about the ContDistConstant distribution 
.RE
.PP

.PP
Implements \fBdesmoj\&.core\&.report\&.Reporter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
