.TH "desmoj.extensions.chaining.report.FlexReporterBuilder" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.chaining.report.FlexReporterBuilder \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCell\fP"
.br
.ti -1c
.RI "class \fBFlexReporter\fP"
.br
.ti -1c
.RI "class \fBHeadingCell\fP"
.br
.ti -1c
.RI "class \fBRow\fP"
.br
.ti -1c
.RI "interface \fBRowCloseCallback\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFlexReporterBuilder\fP (String groupHeading, int groupId)"
.br
.ti -1c
.RI "\fBFlexReporter\fP \fBbuild\fP ()"
.br
.ti -1c
.RI "\fBFlexReporterBuilder\fP \fBcloseRow\fP ()"
.br
.ti -1c
.RI "\fBRow\fP \fBopenRow\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBFlexReporterBuilder\fP is a helper class for constructing \fBFlexReporter\fPs which are special Reporters whose content (i\&.e\&. the cells that may displayed in multiple rows) is defined dynamically\&.
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Malte Unkrig
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.chaining\&.report\&.FlexReporterBuilder\&.FlexReporterBuilder (StringgroupHeading, intgroupId)"
Constructs a new \fBFlexReporterBuilder\fP with the given group heading and group id\&.
.PP
\fBParameters:\fP
.RS 4
\fIgroupHeading\fP The group heading that will be used when the \fBFlexReporter\fP is built with this builder 
.br
\fIgroupId\fP The group id that will be used when the \fBFlexReporter\fP is built with this builder 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBFlexReporter\fP desmoj\&.extensions\&.chaining\&.report\&.FlexReporterBuilder\&.build ()"
Builds a \fBFlexReporter\fP from all the rows and cells that have been added to this builder
.PP
\fBReturns:\fP
.RS 4
The newly build \fBFlexReporter\fP 
.RE
.PP

.SS "\fBFlexReporterBuilder\fP desmoj\&.extensions\&.chaining\&.report\&.FlexReporterBuilder\&.closeRow ()"
Closes the row currently under construction
.PP
\fBReturns:\fP
.RS 4
The \fBFlexReporterBuilder\fP for chaining 
.RE
.PP

.SS "\fBRow\fP desmoj\&.extensions\&.chaining\&.report\&.FlexReporterBuilder\&.openRow ()"
Opens a new row for constructrion
.PP
\fBReturns:\fP
.RS 4
the new row for chaining 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
