.TH "desmoj.extensions.visualEvents.ControlEvent" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualEvents.ControlEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits EventObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBControlEvent\fP (Object source)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A \fBControlEvent\fP is used to control the simulation from the visualization GUI\&. 
.PP
\fBAuthor:\fP
.RS 4
Fred Sun 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.visualEvents\&.ControlEvent\&.ControlEvent (Objectsource)"
Constructs a \fBControlEvent\fP 
.PP
\fBParameters:\fP
.RS 4
\fIsource\fP The object on which the event initially occurred\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
