.TH "desmoj.core.statistic.DataListTally.DataList.Element" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.core.statistic.DataListTally.DataList.Element \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBElement\fP (double value)"
.br
.ti -1c
.RI "\fBElement\fP \fBgetNext\fP ()"
.br
.ti -1c
.RI "void \fBsetNext\fP (\fBElement\fP next)"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.ti -1c
.RI "double \fBgetValue\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
A List's \fBElement\fP\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.core\&.statistic\&.DataListTally\&.DataList\&.Element\&.Element (doublevalue)"
Constructs a new \fBElement\fP with the given value\&.
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP double : The value of this \fBElement\fP\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBElement\fP desmoj\&.core\&.statistic\&.DataListTally\&.DataList\&.Element\&.getNext ()"
Returns the next \fBElement\fP in the List\&.
.PP
\fBReturns:\fP
.RS 4
the next \fBElement\fP in the list of \fCnull\fP if this is the last \fBElement\fP\&. 
.RE
.PP

.SS "double desmoj\&.core\&.statistic\&.DataListTally\&.DataList\&.Element\&.getValue ()"
Returns the \fBElement\fP's value\&.
.PP
\fBReturns:\fP
.RS 4
the value of this \fBElement\fP\&. 
.RE
.PP

.SS "void desmoj\&.core\&.statistic\&.DataListTally\&.DataList\&.Element\&.setNext (\fBElement\fPnext)"
Sets the next \fBElement\fP in the list\&.
.PP
\fBParameters:\fP
.RS 4
\fInext\fP \fBElement\fP : The \fBElement\fP to be the successor of this \fBElement\fP\&. 
.RE
.PP

.SS "String desmoj\&.core\&.statistic\&.DataListTally\&.DataList\&.Element\&.toString ()"
Returns the \fBElement\fP's value as String\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
