.TH "desmoj.extensions.applicationDomains.harbour.TransporterJob" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.applicationDomains.harbour.TransporterJob \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransporterJob\fP (\fBInternalTransporter\fP t, \fBJob\fP j)"
.br
.ti -1c
.RI "\fBInternalTransporter\fP \fBgetTransporter\fP ()"
.br
.ti -1c
.RI "\fBJob\fP \fBgetJob\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
A \fBTransporterJob\fP represents a job that must be assigned to internal the transporter get it done\&. \fBTransporterJob\fP is using to store the transporter and his job to do by a transport strategy\&.
.PP
\fBSee Also:\fP
.RS 4
\fBTransportStrategy\fP
.RE
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Eugenia Neufeld
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.applicationDomains\&.harbour\&.TransporterJob\&.TransporterJob (\fBInternalTransporter\fPt, \fBJob\fPj)"
Constructs a \fBTransporterJob\fP with the internal transporter and his job\&.
.PP
\fBParameters:\fP
.RS 4
\fIt\fP \fBInternalTransporter\fP : The \fBInternalTransporter\fP\&. 
.br
\fIj\fP \fBJob\fP : The \fBJob\fP\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBJob\fP desmoj\&.extensions\&.applicationDomains\&.harbour\&.TransporterJob\&.getJob ()"
Returns the \fBJob\fP of this \fBTransporterJob\fP\&.
.PP
\fBReturns:\fP
.RS 4
\fC\fBJob\fP\fP: The \fBJob\fP of this \fBTransporterJob\fP\&. 
.RE
.PP

.SS "\fBInternalTransporter\fP desmoj\&.extensions\&.applicationDomains\&.harbour\&.TransporterJob\&.getTransporter ()"
Returns the \fBInternalTransporter\fP of this \fBTransporterJob\fP\&.
.PP
\fBReturns:\fP
.RS 4
\fC\fBInternalTransporter\fP\fP: The \fBInternalTransporter\fP of this \fBTransporterJob\fP\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
