.TH "desmoj.extensions.visualization2d.engine.modelGrafic.ModelGrafic.ZoomEntry" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization2d.engine.modelGrafic.ModelGrafic.ZoomEntry \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBZoomEntry\fP (String viewId, boolean isSelected, double zoomFactor, Point zoomPoint, Rectangle viewRectangle)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "String \fBviewId\fP"
.br
.ti -1c
.RI "boolean \fBisSelected\fP"
.br
.ti -1c
.RI "double \fBzoomFactor\fP"
.br
.ti -1c
.RI "Point \fBzoomPoint\fP"
.br
.ti -1c
.RI "Rectangle \fBviewRectangle\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
