.TH "desmoj.extensions.space3D.SpatialData" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.space3D.SpatialData \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpatialData\fP ()"
.br
.ti -1c
.RI "\fBSpatialData\fP (double[] matrixData)"
.br
.ti -1c
.RI "Matrix4d \fBgetMatrix\fP ()"
.br
.ti -1c
.RI "double \fBgetPosX\fP ()"
.br
.ti -1c
.RI "double \fBgetPosY\fP ()"
.br
.ti -1c
.RI "double \fBgetPosZ\fP ()"
.br
.ti -1c
.RI "void \fBresetRotation\fP ()"
.br
.ti -1c
.RI "void \fBrotX\fP (double angle)"
.br
.ti -1c
.RI "void \fBrotY\fP (double angle)"
.br
.ti -1c
.RI "void \fBrotZ\fP (double angle)"
.br
.ti -1c
.RI "void \fBsetMatrix\fP (Matrix4d matrixData)"
.br
.ti -1c
.RI "void \fBsetPosition\fP (double x, double y, double z)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBSpatialData\fP contains the spatial and physical attributes\&.
.PP
\fBAuthor:\fP
.RS 4
Fred Sun 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.space3D\&.SpatialData\&.SpatialData ()"
Constructs a \fBSpatialData\fP object without specifying the data\&. All data are set to zero\&. 
.SS "desmoj\&.extensions\&.space3D\&.SpatialData\&.SpatialData (double[]matrixData)"
Constructs a \fBSpatialData\fP object\&. 
.PP
\fBParameters:\fP
.RS 4
\fImatrixData\fP The spatial data represented with a double[16] matrix\&. It begins with the first element in the first row, then the second element in the first row etc\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "Matrix4d desmoj\&.extensions\&.space3D\&.SpatialData\&.getMatrix ()"
Returns the matrix in a double[16]\&. The first four elements are represents the first row\&. The next four the second row etc\&. 
.PP
\fBReturns:\fP
.RS 4
The matrix in a double[16]\&. Returns the matrix which contains the spatial data\&. 
.PP
The Matrix4d object\&. 
.RE
.PP

.SS "double desmoj\&.extensions\&.space3D\&.SpatialData\&.getPosX ()"
Returns the x-position\&. 
.PP
\fBReturns:\fP
.RS 4
The x-position 
.RE
.PP

.SS "double desmoj\&.extensions\&.space3D\&.SpatialData\&.getPosY ()"
Returns the y-position\&. 
.PP
\fBReturns:\fP
.RS 4
The y-position 
.RE
.PP

.SS "double desmoj\&.extensions\&.space3D\&.SpatialData\&.getPosZ ()"
Returns the z-position\&. 
.PP
\fBReturns:\fP
.RS 4
The z-position 
.RE
.PP

.SS "void desmoj\&.extensions\&.space3D\&.SpatialData\&.resetRotation ()"
Resets the rotational data 
.SS "void desmoj\&.extensions\&.space3D\&.SpatialData\&.rotX (doubleangle)"
Rotates the spatial attribute counter-clockwise about the x-axis\&. 
.PP
\fBParameters:\fP
.RS 4
\fIangle\fP The angle to rotate in radians\&. 
.RE
.PP

.SS "void desmoj\&.extensions\&.space3D\&.SpatialData\&.rotY (doubleangle)"
Sets the matrix\&. 
.PP
\fBParameters:\fP
.RS 4
\fImatrixData\fP The new data in a double array\&. The first four elements of the array will be the first row, the next four the second etc\&. Rotates the spatial attribute counter-clockwise about the y-axis\&. 
.br
\fIangle\fP The angle to rotate in radians\&. 
.RE
.PP

.SS "void desmoj\&.extensions\&.space3D\&.SpatialData\&.rotZ (doubleangle)"
Rotates the spatial attribute counter-clockwise about the z-axis\&. 
.PP
\fBParameters:\fP
.RS 4
\fIangle\fP The angle to rotate in radians\&. 
.RE
.PP

.SS "void desmoj\&.extensions\&.space3D\&.SpatialData\&.setMatrix (Matrix4dmatrixData)"
Sets the matrix\&. 
.PP
\fBParameters:\fP
.RS 4
\fImatrixData\fP The new matrix in Matrix4d\&. 
.RE
.PP

.SS "void desmoj\&.extensions\&.space3D\&.SpatialData\&.setPosition (doublex, doubley, doublez)"
Sets a new Position\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP x-position 
.br
\fIy\fP y-position 
.br
\fIz\fP z-position 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
