.TH "desmoj.extensions.space3D.ExtendedLength" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.space3D.ExtendedLength \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.extensions\&.dimensions\&.Length\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExtendedLength\fP (double \fBvalue\fP, int \fBunit\fP)"
.br
.ti -1c
.RI "boolean \fBisValidValue\fP (double \fBvalue\fP)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This is an extension of the desmoj\&.extensions\&.dimensions\&.Unit class\&. It overrides the isValidValue method so the negative Values can be accepted\&. (For avoiding the handling with the unit codes more specific setting and getting methods are added\&.)
.PP
\fBAuthor:\fP
.RS 4
Fred Sun 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "boolean desmoj\&.extensions\&.space3D\&.ExtendedLength\&.isValidValue (doublevalue)"
overrides the original isValidValue method from the desmoj\&.extensions\&.dimensions\&.Unit class\&. Now it always returns true, so the negative values can be accepted\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
