.TH "desmoj.core.statistic.DataListTally" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.core.statistic.DataListTally \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.core\&.statistic\&.Tally\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDataList\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataListTally\fP (\fBModel\fP ownerModel, String name, boolean showInReport, boolean showInTrace)"
.br
.ti -1c
.RI "void \fBsetReportDataListHistogram\fP (boolean value)"
.br
.ti -1c
.RI "boolean \fBgetReportDataListHistogram\fP ()"
.br
.ti -1c
.RI "\fBReporter\fP \fBcreateReporter\fP ()"
.br
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.ti -1c
.RI "void \fBupdate\fP (double val)"
.br
.ti -1c
.RI "void \fBupdate\fP (Observable o, Object arg)"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "\fBDataList\fP \fBgetDataListSorted\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fC\fBDataListTally\fP\fP class is providing a statistic analysis about one value\&. The mean value and the standard deviation is calculated on basis of the total number of observations\&. All observed values are stored in a list to be able to calculate quartiles or histograms\&.
.PP
\fBSee Also:\fP
.RS 4
\fBTally\fP 
.RE
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Tim Janz 
.PP
.nf
    Licensed under the Apache License, Version 2.0 (the "License"); you
    may not use this file except in compliance with the License. You may
    obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
    implied. See the License for the specific language governing
    permissions and limitations under the License.
.fi
.PP
 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.core\&.statistic\&.DataListTally\&.DataListTally (\fBModel\fPownerModel, Stringname, booleanshowInReport, booleanshowInTrace)"
Constructor for a \fBDataListTally\fP object\&.
.PP
\fBParameters:\fP
.RS 4
\fIownerModel\fP Model : The model this \fBTally\fP is associated to 
.br
\fIname\fP java\&.lang\&.String : The name of this \fBTally\fP object 
.br
\fIshowInReport\fP boolean : Flag for showing the report about this \fBTally\fP\&. 
.br
\fIshowInTrace\fP boolean : Flag for showing the trace output of this \fBTally\fP\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBReporter\fP desmoj\&.core\&.statistic\&.DataListTally\&.createReporter ()"
Creates a Reporter for this \fBDataListTally\fP\&.
.PP
\fBReturns:\fP
.RS 4
Reporter : The reporter for this \fBDataListTally\fP\&. 
.RE
.PP

.SS "\fBDataList\fP desmoj\&.core\&.statistic\&.DataListTally\&.getDataListSorted ()"
Returns the sorted \fBDataList\fP\&.
.PP
\fBReturns:\fP
.RS 4
the \fBDataList\fP\&. 
.RE
.PP

.SS "boolean desmoj\&.core\&.statistic\&.DataListTally\&.getReportDataListHistogram ()"
Will a histogram-reporter be used to create a report for the \fBDataList\fP?
.PP
\fBReturns:\fP
.RS 4
true if the reporting is enabled, false if not\&. 
.RE
.PP

.SS "void desmoj\&.core\&.statistic\&.DataListTally\&.reset ()"
Resets the \fBDataListTally\fP and its \fBDataList\fP\&. 
.SS "void desmoj\&.core\&.statistic\&.DataListTally\&.setReportDataListHistogram (booleanvalue)"
Should a histogram-reporter be used for the \fBDataList\fP?
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP boolean : true, if the \fBDataList\fP should be reported using a histogram-reporter, false if not\&. 
.RE
.PP

.SS "void desmoj\&.core\&.statistic\&.DataListTally\&.update ()"
Updates this \fC\fBDataListTally\fP\fP object by fetching the actual value of the \fC\fBValueSupplier\fP\fP and processing it\&. The \fC\fBValueSupplier\fP\fP is passed in the constructor of this \fC\fBDataListTally\fP\fP object\&. This \fC\fBupdate()\fP\fP method complies with the one described in DESMO, see [Page91]\&. 
.SS "void desmoj\&.core\&.statistic\&.DataListTally\&.update (doubleval)"
Updates this \fC\fBDataListTally\fP\fP object with the double value given as parameter\&. In some cases it might be more convenient to pass the value this \fC\fBDataListTally\fP\fP will be updated with directly within the \fC\fBupdate(double val)\fP\fP method instead of going via the \fC\fBValueSupplier\fP\fP\&.
.PP
\fBParameters:\fP
.RS 4
\fIval\fP double : The value with which this \fC\fBTally\fP\fP will be updated\&. 
.RE
.PP

.SS "void desmoj\&.core\&.statistic\&.DataListTally\&.update (Observableo, Objectarg)"
Implementation of the virtual \fC\fBupdate(Observable, Object)\fP\fP method of the \fCObserver\fP interface\&. This method will be called automatically from an \fCObservable\fP object within its \fCnotifyObservers()\fP method\&. 
.br
 If no Object (a\fCnull\fP value) is passed as arg, the actual value of the \fBValueSupplier\fP will be fetched with the \fCvalue()\fP method of the \fBValueSupplier\fP\&. Otherwise it is expected that the actual value is passed in the Object arg\&.
.PP
\fBParameters:\fP
.RS 4
\fIo\fP java\&.util\&.Observable : The Observable calling this method within its own \fCnotifyObservers()\fP method\&. 
.br
\fIarg\fP Object : The Object with which this \fC\fBTally\fP\fP is updated\&. Normally a double number which is added to the statistics or \fCnull\fP\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
