.TH "desmoj.extensions.experimentation.ui.GraphicalObserver" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.experimentation.ui.GraphicalObserver \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.core\&.util\&.SimRunListener\fP, and \fBdesmoj\&.extensions\&.experimentation\&.ui\&.IGraphicalObserver\fP\&.
.PP
Inherited by \fBdesmoj\&.extensions\&.experimentation\&.ui\&.HistogramPlotter\fP, and \fBdesmoj\&.extensions\&.experimentation\&.ui\&.TimeSeriesPlotter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGraphicalObserver\fP (String name, \fBGraphicalObserverContext\fP c)"
.br
.ti -1c
.RI "\fBGraphicalObserverContext\fP \fBgetContext\fP ()"
.br
.ti -1c
.RI "abstract Component \fBgetGUI\fP ()"
.br
.ti -1c
.RI "void \fBregister\fP ()"
.br
.ti -1c
.RI "void \fBderegister\fP ()"
.br
.ti -1c
.RI "void \fBsetVisible\fP (boolean visible)"
.br
.ti -1c
.RI "void \fBsetSize\fP (int width, int height)"
.br
.ti -1c
.RI "void \fBsetLocation\fP (int x, int y)"
.br
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base class for graphical observers in the experiment launcher\&. A graphical observer can display itself inside a graphical observer context (e\&.g\&. a JDesktop component)\&.
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Nicolas Knaak
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.experimentation\&.ui\&.GraphicalObserver\&.GraphicalObserver (Stringname, \fBGraphicalObserverContext\fPc)"
Creates a new graphical observer\&.
.PP
\fBParameters:\fP
.RS 4
\fIname\fP Name of the graphical observer 
.br
\fIc\fP the context this graphical observer is displayed in 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void desmoj\&.extensions\&.experimentation\&.ui\&.GraphicalObserver\&.deregister ()\fC [virtual]\fP"
Deregisters the observer from the context 
.PP
Implements \fBdesmoj\&.extensions\&.experimentation\&.ui\&.IGraphicalObserver\fP\&.
.SS "\fBGraphicalObserverContext\fP desmoj\&.extensions\&.experimentation\&.ui\&.GraphicalObserver\&.getContext ()\fC [virtual]\fP"
Returns the context this observer is displayed in
.PP
\fBReturns:\fP
.RS 4
The context (e\&.g\&. a JDesktop component)\&. 
.RE
.PP

.PP
Implements \fBdesmoj\&.extensions\&.experimentation\&.ui\&.IGraphicalObserver\fP\&.
.SS "abstract Component desmoj\&.extensions\&.experimentation\&.ui\&.GraphicalObserver\&.getGUI ()\fC [pure virtual]\fP"
Should return the graphical observer's main GUI component
.PP
\fBReturns:\fP
.RS 4
an AWT or Swing component\&. 
.RE
.PP

.PP
Implements \fBdesmoj\&.extensions\&.experimentation\&.ui\&.IGraphicalObserver\fP\&.
.PP
Implemented in \fBdesmoj\&.extensions\&.experimentation\&.ui\&.TimeSeriesPlotter\fP, and \fBdesmoj\&.extensions\&.experimentation\&.ui\&.HistogramPlotter\fP\&.
.SS "String desmoj\&.extensions\&.experimentation\&.ui\&.GraphicalObserver\&.getName ()\fC [virtual]\fP"
Returns the observer's name
.PP
\fBReturns:\fP
.RS 4
name 
.RE
.PP

.PP
Implements \fBdesmoj\&.extensions\&.experimentation\&.ui\&.IGraphicalObserver\fP\&.
.SS "void desmoj\&.extensions\&.experimentation\&.ui\&.GraphicalObserver\&.register ()\fC [virtual]\fP"
Registers the observer with the context 
.PP
Implements \fBdesmoj\&.extensions\&.experimentation\&.ui\&.IGraphicalObserver\fP\&.
.SS "void desmoj\&.extensions\&.experimentation\&.ui\&.GraphicalObserver\&.setLocation (intx, inty)\fC [virtual]\fP"
Sets the position of the observer's main window's upper left edge\&.
.PP
\fBParameters:\fP
.RS 4
\fIx\fP horizontal position 
.br
\fIy\fP vertical position 
.RE
.PP

.PP
Implements \fBdesmoj\&.extensions\&.experimentation\&.ui\&.IGraphicalObserver\fP\&.
.SS "void desmoj\&.extensions\&.experimentation\&.ui\&.GraphicalObserver\&.setSize (intwidth, intheight)\fC [virtual]\fP"
Sets the observer's main window's size\&.
.PP
\fBParameters:\fP
.RS 4
\fIwidth\fP window width 
.br
\fIheight\fP window height 
.RE
.PP

.PP
Implements \fBdesmoj\&.extensions\&.experimentation\&.ui\&.IGraphicalObserver\fP\&.
.SS "void desmoj\&.extensions\&.experimentation\&.ui\&.GraphicalObserver\&.setVisible (booleanvisible)\fC [virtual]\fP"
Sets the observer visible withing the context 
.PP
Implements \fBdesmoj\&.extensions\&.experimentation\&.ui\&.IGraphicalObserver\fP\&.
.SS "void desmoj\&.extensions\&.experimentation\&.ui\&.GraphicalObserver\&.update ()\fC [virtual]\fP"
Requests an update of the observer's display from the context\&. 
.PP
Implements \fBdesmoj\&.extensions\&.experimentation\&.ui\&.IGraphicalObserver\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
