.TH "desmoj.core.dist.DiscreteDistPoisson" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.core.dist.DiscreteDistPoisson \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits DiscreteDist< Long >\&.
.PP
Inherited by \fBdesmoj\&.core\&.dist\&.IntDistPoisson\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDiscreteDistPoisson\fP (\fBModel\fP owner, String name, double meanValue, boolean showInReport, boolean showInTrace)"
.br
.ti -1c
.RI "\fBdesmoj\&.core\&.report\&.Reporter\fP \fBcreateReporter\fP ()"
.br
.ti -1c
.RI "double \fBgetMean\fP ()"
.br
.ti -1c
.RI "Long \fBsample\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "double \fBmean\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Poisson distributed stream of pseudo random integer numbers\&. The distribution specified by one parameter describing the mean value\&.
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Tim Lechler 
.PP
Ruth Meyer 
.PP
.nf
    Licensed under the Apache License, Version 2.0 (the "License"); you
    may not use this file except in compliance with the License. You may
    obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
    implied. See the License for the specific language governing
    permissions and limitations under the License.
.fi
.PP
 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.core\&.dist\&.DiscreteDistPoisson\&.DiscreteDistPoisson (\fBModel\fPowner, Stringname, doublemeanValue, booleanshowInReport, booleanshowInTrace)"
Creates a poisson distributed stream of pseudo random integer numbers\&. The parameter describes the mean value\&. Giving zero or negative values for the mean value will result in zero being returned by the \fC\fBsample()\fP\fP method\&.
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP Model : The distribution's owner 
.br
\fIname\fP java\&.lang\&.String : The distribution's name 
.br
\fImeanValue\fP double : The mean \fCdouble\fP value for this distribution 
.br
\fIshowInReport\fP boolean : Flag for producing reports 
.br
\fIshowInTrace\fP boolean : Flag for producing trace output 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBdesmoj\&.core\&.report\&.Reporter\fP desmoj\&.core\&.dist\&.DiscreteDistPoisson\&.createReporter ()"
Creates the default reporter for the PoissonDiscreteDist distribution\&.
.PP
\fBReturns:\fP
.RS 4
Reporter : The reporter for the PoissonDiscreteDist distribution 
.RE
.PP
\fBSee Also:\fP
.RS 4
DiscreteDistPoissonReporter 
.RE
.PP

.SS "double desmoj\&.core\&.dist\&.DiscreteDistPoisson\&.getMean ()"
Returns the mean value of the poisson distribution\&.
.PP
\fBReturns:\fP
.RS 4
double : The mean value of this Poisson distribution 
.RE
.PP

.SS "Long desmoj\&.core\&.dist\&.DiscreteDistPoisson\&.sample ()"
Returns the next poisson distributed sample from this distribution\&.
.PP
\fBReturns:\fP
.RS 4
Long : The next Poisson distributed sample\&. This will be zero if the given mean value <= 0\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "double desmoj\&.core\&.dist\&.DiscreteDistPoisson\&.mean\fC [protected]\fP"
The mean value of the poisson distribution as given to the constructor\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
