.TH "desmoj.extensions.visualEvents.SetPositionEvent" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualEvents.SetPositionEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.extensions\&.visualEvents\&.VisualEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSetPositionEvent\fP (Object source, String affectedSpatialObjectName, double x, double y, double z, \fBTimeInstant\fP occurredTime)"
.br
.ti -1c
.RI "double \fBgetX\fP ()"
.br
.ti -1c
.RI "double \fBgetY\fP ()"
.br
.ti -1c
.RI "double \fBgetZ\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This event indicates the setting of a new position for a SpatialObject\&. 
.PP
\fBAuthor:\fP
.RS 4
Fred Sun 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.visualEvents\&.SetPositionEvent\&.SetPositionEvent (Objectsource, StringaffectedSpatialObjectName, doublex, doubley, doublez, \fBTimeInstant\fPoccurredTime)"
Constructs a new \fBSetPositionEvent\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsource\fP The object on which the event initially occurred\&. 
.br
\fIaffectedSpatialObjectName\fP The name of the object who's position should be set\&. 
.br
\fIx\fP The new x value\&. 
.br
\fIy\fP The new y value\&. 
.br
\fIz\fP The new z value\&. 
.br
\fIoccuredTime\fP The TimeInstant when the event occurred\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "double desmoj\&.extensions\&.visualEvents\&.SetPositionEvent\&.getX ()"
Gets the new x value\&. 
.PP
\fBReturns:\fP
.RS 4
The new x value\&. 
.RE
.PP

.SS "double desmoj\&.extensions\&.visualEvents\&.SetPositionEvent\&.getY ()"
Gets the new y value\&. 
.PP
\fBReturns:\fP
.RS 4
The new y value\&. 
.RE
.PP

.SS "double desmoj\&.extensions\&.visualEvents\&.SetPositionEvent\&.getZ ()"
Gets the new z value\&. 
.PP
\fBReturns:\fP
.RS 4
The new z value\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
