.TH "desmoj.extensions.visualization3d.ModelManager" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization3d.ModelManager \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModelManager\fP (String filePath)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBModelManager\fP loads the Model-XML file where the SpatialObject and its associated 3D-Model is listed\&. The decoration models will also be listed in the file and loaded by this class\&.  The associated model will be load and stored within this class\&.
.PP
\fBAuthor:\fP
.RS 4
Fred Sun 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.visualization3d\&.ModelManager\&.ModelManager (StringfilePath)"
Constructs a \fBModelManager\fP and load the XML file where the 3D-models are specified\&.
.PP
\fBParameters:\fP
.RS 4
\fIfilePath\fP The path to the XML file where the 3D-models are specified\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
