.TH "desmoj.core.report.TableFormatter" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.core.report.TableFormatter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBdesmoj\&.core\&.report\&.AbstractTableFormatter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBopen\fP (String name)"
.br
.ti -1c
.RI "void \fBclose\fP ()"
.br
.ti -1c
.RI "void \fBcloseRow\fP ()"
.br
.ti -1c
.RI "void \fBcloseTable\fP ()"
.br
.ti -1c
.RI "void \fBcloseTableNoTopTag\fP ()"
.br
.ti -1c
.RI "void \fBopenRow\fP ()"
.br
.ti -1c
.RI "void \fBopenTable\fP (String heading)"
.br
.ti -1c
.RI "boolean \fBrowIsOpen\fP ()"
.br
.ti -1c
.RI "boolean \fBtableIsOpen\fP ()"
.br
.ti -1c
.RI "void \fBwriteCell\fP (String s, int spanning)"
.br
.ti -1c
.RI "void \fBwriteHeading\fP (int i, String s)"
.br
.ti -1c
.RI "void \fBwriteHeadingCell\fP (String s)"
.br
.ti -1c
.RI "void \fBwriteHorizontalRuler\fP ()"
.br
.ti -1c
.RI "String \fBwriteTime\fP (String s)"
.br
.ti -1c
.RI "int \fBtimePrecision\fP ()"
.br
.ti -1c
.RI "void \fBsetOutput\fP (\fBFileOutput\fP out)"
.br
.ti -1c
.RI "void \fBsetTimePrecision\fP (int tp)"
.br
.ti -1c
.RI "String \fBgetFileFormat\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
An interface representing basic facilites for writing data into tables\&. The specified operations are adapted from the deprecated class demoj\&.report\&.HTMLFileOutput\&.
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Tim Lechler (\fBHTMLFileOutput\fP), Nicolas Knaak
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Member Function Documentation"
.PP 
.SS "void desmoj\&.core\&.report\&.TableFormatter\&.close ()"
Should close the document 
.PP
Implemented in \fBdesmoj\&.core\&.report\&.ASCIITableFormatter\fP, and \fBdesmoj\&.core\&.report\&.HTMLTableFormatter\fP\&.
.SS "void desmoj\&.core\&.report\&.TableFormatter\&.closeRow ()"
Should close a table row 
.PP
Implemented in \fBdesmoj\&.core\&.report\&.HTMLTableFormatter\fP, and \fBdesmoj\&.core\&.report\&.ASCIITableFormatter\fP\&.
.SS "void desmoj\&.core\&.report\&.TableFormatter\&.closeTable ()"
Should close a table 
.PP
Implemented in \fBdesmoj\&.core\&.report\&.HTMLTableFormatter\fP, and \fBdesmoj\&.core\&.report\&.ASCIITableFormatter\fP\&.
.SS "void desmoj\&.core\&.report\&.TableFormatter\&.closeTableNoTopTag ()"
Should close a table without writing a top tag (HTML specific) 
.PP
Implemented in \fBdesmoj\&.core\&.report\&.HTMLTableFormatter\fP, and \fBdesmoj\&.core\&.report\&.ASCIITableFormatter\fP\&.
.SS "String desmoj\&.core\&.report\&.TableFormatter\&.getFileFormat ()"

.PP
\fBReturns:\fP
.RS 4
appendix of the file format the table is stored in (e\&.g\&. 'html' or 'txt') 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.core\&.report\&.HTMLTableFormatter\fP, and \fBdesmoj\&.core\&.report\&.ASCIITableFormatter\fP\&.
.SS "void desmoj\&.core\&.report\&.TableFormatter\&.open (Stringname)"
Should open a new document containing multiple tables with the given name
.PP
\fBParameters:\fP
.RS 4
\fIname\fP table name 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.core\&.report\&.ASCIITableFormatter\fP, and \fBdesmoj\&.core\&.report\&.HTMLTableFormatter\fP\&.
.SS "void desmoj\&.core\&.report\&.TableFormatter\&.openRow ()"
Should open a row 
.PP
Implemented in \fBdesmoj\&.core\&.report\&.HTMLTableFormatter\fP, and \fBdesmoj\&.core\&.report\&.ASCIITableFormatter\fP\&.
.SS "void desmoj\&.core\&.report\&.TableFormatter\&.openTable (Stringheading)"
Should open a table with the given heading
.PP
\fBParameters:\fP
.RS 4
\fIheading\fP table heading 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.core\&.report\&.HTMLTableFormatter\fP, and \fBdesmoj\&.core\&.report\&.ASCIITableFormatter\fP\&.
.SS "boolean desmoj\&.core\&.report\&.TableFormatter\&.rowIsOpen ()"

.PP
\fBReturns:\fP
.RS 4
\fCtrue\fP if a row is currently open, \fCfalse\fP otherwise 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.core\&.report\&.HTMLTableFormatter\fP, and \fBdesmoj\&.core\&.report\&.AbstractTableFormatter\fP\&.
.SS "void desmoj\&.core\&.report\&.TableFormatter\&.setOutput (\fBFileOutput\fPout)"
Should set an output file to write the table to
.PP
\fBParameters:\fP
.RS 4
\fIout\fP a desmoj\&.report\&.FileOutput to write the table to 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.core\&.report\&.AbstractTableFormatter\fP\&.
.SS "void desmoj\&.core\&.report\&.TableFormatter\&.setTimePrecision (inttp)"
Should set the required precision of time values\&.
.PP
\fBParameters:\fP
.RS 4
\fItp\fP precision 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.core\&.report\&.AbstractTableFormatter\fP\&.
.SS "boolean desmoj\&.core\&.report\&.TableFormatter\&.tableIsOpen ()"

.PP
\fBReturns:\fP
.RS 4
\fCtrue\fP if a table is currently open, \fCfalse\fP otherwise 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.core\&.report\&.HTMLTableFormatter\fP, and \fBdesmoj\&.core\&.report\&.AbstractTableFormatter\fP\&.
.SS "int desmoj\&.core\&.report\&.TableFormatter\&.timePrecision ()"
Should return the precision used for time values\&.
.PP
\fBReturns:\fP
.RS 4
precision 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.core\&.report\&.AbstractTableFormatter\fP\&.
.SS "void desmoj\&.core\&.report\&.TableFormatter\&.writeCell (Strings, intspanning)"
Should write the given string into a new table cell
.PP
\fBParameters:\fP
.RS 4
\fIs\fP string to write 
.br
\fIspanning\fP number of cells to span 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.core\&.report\&.HTMLTableFormatter\fP, and \fBdesmoj\&.core\&.report\&.ASCIITableFormatter\fP\&.
.SS "void desmoj\&.core\&.report\&.TableFormatter\&.writeHeading (inti, Strings)"
Should write the given heading of size i into a new table cell
.PP
\fBParameters:\fP
.RS 4
\fIs\fP string to write 
.br
\fIi\fP size (must be interpreted in a sensible way)\&. 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.core\&.report\&.HTMLTableFormatter\fP, and \fBdesmoj\&.core\&.report\&.ASCIITableFormatter\fP\&.
.SS "void desmoj\&.core\&.report\&.TableFormatter\&.writeHeadingCell (Strings)"
Should write the given heading of default size into a new table cell
.PP
\fBParameters:\fP
.RS 4
\fIs\fP string to write 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.core\&.report\&.HTMLTableFormatter\fP, and \fBdesmoj\&.core\&.report\&.ASCIITableFormatter\fP\&.
.SS "void desmoj\&.core\&.report\&.TableFormatter\&.writeHorizontalRuler ()"
Writes a horizontal ruler 
.PP
Implemented in \fBdesmoj\&.core\&.report\&.HTMLTableFormatter\fP, and \fBdesmoj\&.core\&.report\&.ASCIITableFormatter\fP\&.
.SS "String desmoj\&.core\&.report\&.TableFormatter\&.writeTime (Strings)"
Should format the given time String and write it into a cell
.PP
\fBParameters:\fP
.RS 4
\fIs\fP a string containing simulation time in float format\&. 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.core\&.report\&.AbstractTableFormatter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
