.TH "desmoj.core.report.OutputTypeEndToExport" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.core.report.OutputTypeEndToExport \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.core\&.report\&.OutputType\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBexport\fP (String pathname, String filename)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface for Outputs that cannot be written line by line, e\&.g\&. Excel\&.
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBDate:\fP
.RS 4
30\&.03\&.2011 
.RE
.PP
\fBAuthor:\fP
.RS 4
Xiufeng Li 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void desmoj\&.core\&.report\&.OutputTypeEndToExport\&.export (Stringpathname, Stringfilename)"
Export a new few file for the writting output\&.
.PP
\fBParameters:\fP
.RS 4
\fIpathname\fP String: path to write in 
.br
\fIfilename\fP String: name of the file 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
