.TH "desmoj.extensions.crossbar.CrossbarMessage.DistributionMode" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.crossbar.CrossbarMessage.DistributionMode \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDISTRIBUTE_BY_REFERENCE\fP"
.br
.ti -1c
.RI "\fBDISTRIBUTE_AS_COPY\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBDistributionMode\fP defines how a \fBCrossbarMessage\fP is distributed to receiver processes\&. It can either be distributed by reference, meaning each receiver gets the exact same message object, or as a copy so that each receiver only gets a (shallow) copy of the original message object\&.
.PP
\fBAuthor:\fP
.RS 4
Malte Unkrig 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
