.TH "desmoj.extensions.visualization2d.engine.model.Bin" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization2d.engine.model.Bin \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Basic\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBin\fP (\fBModel\fP model, String id, long initialValue)"
.br
.ti -1c
.RI "\fBModel\fP \fBgetModel\fP ()"
.br
.ti -1c
.RI "String \fBgetId\fP ()"
.br
.ti -1c
.RI "void \fBsetName\fP (String name)"
.br
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.ti -1c
.RI "long \fBgetLwb\fP ()"
.br
.ti -1c
.RI "long \fBgetCount\fP ()"
.br
.ti -1c
.RI "void \fBsetCount\fP (long value, boolean aggregate)"
.br
.ti -1c
.RI "String[][] \fBgetContentConsumer\fP ()"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "void \fBretrieveBegin\fP (String entityId, int priority, long n, String priorityRule, long time)"
.br
.ti -1c
.RI "void \fBretrieveEnd\fP (String entityId, long time)"
.br
.ti -1c
.RI "void \fBstore\fP (String entityId, long n, long time)"
.br
.ti -1c
.RI "\fBGrafic\fP \fBcreateGrafic\fP (String viewId, int x, int y, String defaultEntityTypeId, int anzVisible, boolean horizontal, Dimension deltaSize)  throws ModelException"
.br
.ti -1c
.RI "\fBGrafic\fP \fBgetGrafic\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
describes a unbounded stock
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
christian.mueller@th-wildau.de For information about subproject: desmoj\&.extensions\&.visualization2d please have a look at: http://www.th-wildau.de/cmueller/Desmo-J/Visualization2d/
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Bin\&.Bin (\fBModel\fPmodel, Stringid, longinitialValue)"

.PP
\fBParameters:\fP
.RS 4
\fImodel\fP used animation\&.model\&.Model 
.br
\fIid\fP 
.br
\fIinitialValue\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBGrafic\fP desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Bin\&.createGrafic (StringviewId, intx, inty, StringdefaultEntityTypeId, intanzVisible, booleanhorizontal, DimensiondeltaSize) throws \fBModelException\fP"
create a StockGrafic 
.PP
\fBParameters:\fP
.RS 4
\fIviewId\fP Id of view 
.br
\fIx\fP middlepoint x-coordinate 
.br
\fIy\fP middlepoint y-coordinate 
.br
\fIdefaultEntityTypeId\fP for sizing 
.RE
.PP
\fBReturns:\fP
.RS 4
StockGrafic 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBModelException\fP\fP 
.RE
.PP

.SS "\fBGrafic\fP desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Bin\&.getGrafic ()"
get ProcessGrafic, created before 
.PP
Implements \fBdesmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Basic\fP\&.
.SS "String desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Bin\&.getId ()"
get id of stock 
.PP
Implements \fBdesmoj\&.extensions\&.visualization2d\&.engine\&.orga\&.ClassBasic\fP\&.
.SS "String desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Bin\&.getName ()"
get name of bin 
.PP
Implements \fBdesmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Basic\fP\&.
.SS "void desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Bin\&.setName (Stringname)"
set name of stock 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
