.TH "desmoj.extensions.chaining.report.FlexReporterBuilder.FlexReporter" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.chaining.report.FlexReporterBuilder.FlexReporter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.core\&.report\&.Reporter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFlexReporter\fP (String \fBgroupHeading\fP, int groupId, LinkedList< \fBRow\fP > rows)"
.br
.ti -1c
.RI "final String[] \fBgetColumnTitles\fP ()"
.br
.ti -1c
.RI "final String[] \fBgetEntries\fP ()"
.br
.ti -1c
.RI "final int \fBgetGroupID\fP ()"
.br
.ti -1c
.RI "LinkedList< \fBRow\fP > \fBgetRows\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A flexible reporter that allows multiple rows with individual formatted cells\&.
.PP
\fBAuthor:\fP
.RS 4
Malte Unkrig 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.chaining\&.report\&.FlexReporterBuilder\&.FlexReporter\&.FlexReporter (StringgroupHeading, intgroupId, LinkedList< \fBRow\fP >rows)"
Constructs a \fBFlexReporter\fP with the given group heaing, group id and the given list of rows\&.
.PP
\fBParameters:\fP
.RS 4
\fIgroupHeading\fP The heading for the group this reporter contributes to 
.br
\fIgroupId\fP The id of the group this reporter contributes to 
.br
\fIrows\fP The list of rows which will be drawn for this reporter in the report 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "final String [] desmoj\&.extensions\&.chaining\&.report\&.FlexReporterBuilder\&.FlexReporter\&.getColumnTitles ()"

.SS "final String [] desmoj\&.extensions\&.chaining\&.report\&.FlexReporterBuilder\&.FlexReporter\&.getEntries ()\fC [virtual]\fP"
Returns an array of strings each containing the data for the corresponding column in array \fCcolumns[]\fP\&. Implement this method the an array of the same length as the columntitles is produced containing the data at the point of time this method is called by someone else to produce up-to-date information\&.
.PP
\fBReturns:\fP
.RS 4
java\&.lang\&.String[] : Array containing the data for reporting
.RE
.PP
 
.PP
Implements \fBdesmoj\&.core\&.report\&.Reporter\fP\&.
.SS "final int desmoj\&.extensions\&.chaining\&.report\&.FlexReporterBuilder\&.FlexReporter\&.getGroupID ()"

.SS "LinkedList<\fBRow\fP> desmoj\&.extensions\&.chaining\&.report\&.FlexReporterBuilder\&.FlexReporter\&.getRows ()"

.PP
\fBReturns:\fP
.RS 4
the rows that will be drawn for this reporter in the report 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
