.TH "desmoj.extensions.experimentation.ui.GraphicalObserverContext" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.experimentation.ui.GraphicalObserverContext \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBdesmoj\&.extensions\&.experimentation\&.ui\&.ObserverDesktop\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBadd\fP (\fBIGraphicalObserver\fP o)"
.br
.ti -1c
.RI "void \fBremove\fP (\fBIGraphicalObserver\fP o)"
.br
.ti -1c
.RI "void \fBsetVisible\fP (\fBIGraphicalObserver\fP o, boolean visible)"
.br
.ti -1c
.RI "\fBIGraphicalObserver\fP[] \fBgetChildren\fP ()"
.br
.ti -1c
.RI "void \fBsetSize\fP (\fBIGraphicalObserver\fP o, int width, int height)"
.br
.ti -1c
.RI "void \fBsetLocation\fP (\fBIGraphicalObserver\fP o, int x, int y)"
.br
.ti -1c
.RI "void \fBupdate\fP (\fBIGraphicalObserver\fP o)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents an arbitrary context (e\&.g\&. a JDesktop) for graphical observers\&.
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Nicolas Knaak
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Member Function Documentation"
.PP 
.SS "void desmoj\&.extensions\&.experimentation\&.ui\&.GraphicalObserverContext\&.add (\fBIGraphicalObserver\fPo)"
Should add a graphical observer to the context\&.
.PP
\fBParameters:\fP
.RS 4
\fIo\fP the graphical observer to add 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.extensions\&.experimentation\&.ui\&.ObserverDesktop\fP\&.
.SS "\fBIGraphicalObserver\fP [] desmoj\&.extensions\&.experimentation\&.ui\&.GraphicalObserverContext\&.getChildren ()"
Should returns all observers in this context\&.
.PP
\fBReturns:\fP
.RS 4
Graphical observer array 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.extensions\&.experimentation\&.ui\&.ObserverDesktop\fP\&.
.SS "void desmoj\&.extensions\&.experimentation\&.ui\&.GraphicalObserverContext\&.remove (\fBIGraphicalObserver\fPo)"
Should remove a graphical observer from the context\&.
.PP
\fBParameters:\fP
.RS 4
\fIo\fP the graphical observer to remove 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.extensions\&.experimentation\&.ui\&.ObserverDesktop\fP\&.
.SS "void desmoj\&.extensions\&.experimentation\&.ui\&.GraphicalObserverContext\&.setLocation (\fBIGraphicalObserver\fPo, intx, inty)"
Should set the given observer's window position
.PP
\fBParameters:\fP
.RS 4
\fIo\fP a graphical observer 
.br
\fIx\fP horizontal coordinate of upper left edge 
.br
\fIy\fP vertical coordinate of upper left edge 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.extensions\&.experimentation\&.ui\&.ObserverDesktop\fP\&.
.SS "void desmoj\&.extensions\&.experimentation\&.ui\&.GraphicalObserverContext\&.setSize (\fBIGraphicalObserver\fPo, intwidth, intheight)"
Should set the given observer's window size
.PP
\fBParameters:\fP
.RS 4
\fIo\fP a graphical observer 
.br
\fIwidth\fP window width 
.br
\fIheight\fP window height 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.extensions\&.experimentation\&.ui\&.ObserverDesktop\fP\&.
.SS "void desmoj\&.extensions\&.experimentation\&.ui\&.GraphicalObserverContext\&.setVisible (\fBIGraphicalObserver\fPo, booleanvisible)"
Should set the given graphical observer (in)visible
.PP
\fBParameters:\fP
.RS 4
\fIo\fP the graphical observer 
.br
\fIvisible\fP \&.\&.\&.to see or not to see\&.\&.\&. ;-) 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.extensions\&.experimentation\&.ui\&.ObserverDesktop\fP\&.
.SS "void desmoj\&.extensions\&.experimentation\&.ui\&.GraphicalObserverContext\&.update (\fBIGraphicalObserver\fPo)"
Should update the given graphical observer's display
.PP
\fBParameters:\fP
.RS 4
\fIgraphical\fP observer to update 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.extensions\&.experimentation\&.ui\&.ObserverDesktop\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
