.TH "desmoj.extensions.space3D.VisibleObject" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.space3D.VisibleObject \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBdesmoj\&.extensions\&.space3D\&.SpatialEntity\fP, \fBdesmoj\&.extensions\&.space3D\&.SpatialProcessQueue< P extends SimProcess >\fP, \fBdesmoj\&.extensions\&.space3D\&.SpatialQueue< E extends Entity >\fP, and \fBdesmoj\&.extensions\&.space3D\&.SpatialSimProcess\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract String \fBgetVisualModel\fP ()"
.br
.ti -1c
.RI "abstract boolean \fBisVisible\fP ()"
.br
.ti -1c
.RI "abstract void \fBremoveVisible\fP ()"
.br
.ti -1c
.RI "abstract void \fBsetVisible\fP (boolean visible)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This interface defines the methods for objects which should be visualized\&.  Every \fBVisibleObject\fP contains a type which indicates the 3D-Model at the visualization\&.
.PP
\fBAuthor:\fP
.RS 4
Fred Sun 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "abstract String desmoj\&.extensions\&.space3D\&.VisibleObject\&.getVisualModel ()\fC [pure virtual]\fP"
Get the type of the \fBSpatialObject\fP\&. 
.PP
\fBReturns:\fP
.RS 4
The type of the \fBSpatialObject\fP\&. 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.extensions\&.space3D\&.SpatialSimProcess\fP, \fBdesmoj\&.extensions\&.space3D\&.SpatialQueue< E extends Entity >\fP, \fBdesmoj\&.extensions\&.space3D\&.SpatialProcessQueue< P extends SimProcess >\fP, and \fBdesmoj\&.extensions\&.space3D\&.SpatialEntity\fP\&.
.SS "abstract boolean desmoj\&.extensions\&.space3D\&.VisibleObject\&.isVisible ()\fC [pure virtual]\fP"
Shows the visibility of the visual representation of this object\&.
.PP
\fBReturns:\fP
.RS 4
True is this object is visible\&. Else, false\&. 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.extensions\&.space3D\&.SpatialQueue< E extends Entity >\fP, \fBdesmoj\&.extensions\&.space3D\&.SpatialProcessQueue< P extends SimProcess >\fP, \fBdesmoj\&.extensions\&.space3D\&.SpatialEntity\fP, and \fBdesmoj\&.extensions\&.space3D\&.SpatialSimProcess\fP\&.
.SS "abstract void desmoj\&.extensions\&.space3D\&.VisibleObject\&.removeVisible ()\fC [pure virtual]\fP"
Sends a RemoveEvent to signal the observers that this object isn't needed anymore\&.  WARNING: The \fBSpatialObject\fP will be still existing\&. 
.PP
Implemented in \fBdesmoj\&.extensions\&.space3D\&.SpatialQueue< E extends Entity >\fP, \fBdesmoj\&.extensions\&.space3D\&.SpatialProcessQueue< P extends SimProcess >\fP, \fBdesmoj\&.extensions\&.space3D\&.SpatialEntity\fP, and \fBdesmoj\&.extensions\&.space3D\&.SpatialSimProcess\fP\&.
.SS "abstract void desmoj\&.extensions\&.space3D\&.VisibleObject\&.setVisible (booleanvisible)\fC [pure virtual]\fP"
Sets the visibility of the visual representation of this object\&.
.PP
\fBParameters:\fP
.RS 4
\fIvisible\fP True, if visible\&. Else, false\&. 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.extensions\&.space3D\&.SpatialQueue< E extends Entity >\fP, \fBdesmoj\&.extensions\&.space3D\&.SpatialProcessQueue< P extends SimProcess >\fP, \fBdesmoj\&.extensions\&.space3D\&.SpatialEntity\fP, and \fBdesmoj\&.extensions\&.space3D\&.SpatialSimProcess\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
