.TH "desmoj.extensions.visualization2d.animation.core.simulator.ProcessQueueAnimation< P extends SimProcessAnimation >" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization2d.animation.core.simulator.ProcessQueueAnimation< P extends SimProcessAnimation > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ProcessQueue< P >, and \fBdesmoj\&.extensions\&.visualization2d\&.animation\&.core\&.simulator\&.ListInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProcessQueueAnimation\fP (\fBModelAnimation\fP owner, String name, boolean showInReport, boolean showInTrace)"
.br
.ti -1c
.RI "\fBProcessQueueAnimation\fP (\fBModelAnimation\fP owner, String name, int sortOrder, int qCapacity, boolean showInReport, boolean showInTrace)"
.br
.ti -1c
.RI "void \fBcreateAnimation\fP (\fBPosition\fP pos, \fBFormExt\fP form, boolean showInAnimation)"
.br
.ti -1c
.RI "void \fBcreateAnimation\fP (\fBComment\fP comment, \fBPosition\fP pos, \fBFormExt\fP form, boolean showInAnimation)"
.br
.ti -1c
.RI "String \fBgetInternId\fP ()"
.br
.ti -1c
.RI "boolean \fBinsert\fP (P e)"
.br
.ti -1c
.RI "boolean \fBinsertAfter\fP (P e, P after)"
.br
.ti -1c
.RI "boolean \fBinsertBefore\fP (P e, P before)"
.br
.ti -1c
.RI "void \fBremove\fP (\fBSimProcess\fP e)"
.br
.ti -1c
.RI "boolean \fBremove\fP (int index)"
.br
.ti -1c
.RI "P \fBremoveFirst\fP ()"
.br
.ti -1c
.RI "P \fBremoveFirst\fP (Condition< P > c)"
.br
.ti -1c
.RI "P \fBremoveLast\fP ()"
.br
.ti -1c
.RI "P \fBremoveLast\fP (Condition< P > c)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Animation of ProcessQueue
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
christian.mueller@th-wildau.de For information about subproject: desmoj\&.extensions\&.visualization2d please have a look at: http://www.th-wildau.de/cmueller/Desmo-J/Visualization2d/
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&.
.PP
\fBParameters:\fP
.RS 4
\fI<P>\fP 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.simulator\&.ProcessQueueAnimation< P extends \fBSimProcessAnimation\fP >\&.ProcessQueueAnimation (\fBModelAnimation\fPowner, Stringname, booleanshowInReport, booleanshowInTrace)"
Constructor with the same parameters as in ProcessQueue 
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP as in ProcessQueue 
.br
\fIname\fP as in ProcessQueue 
.br
\fIshowInReport\fP as in ProcessQueue 
.br
\fIshowInTrace\fP as in ProcessQueue 
.RE
.PP

.SS "desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.simulator\&.ProcessQueueAnimation< P extends \fBSimProcessAnimation\fP >\&.ProcessQueueAnimation (\fBModelAnimation\fPowner, Stringname, intsortOrder, intqCapacity, booleanshowInReport, booleanshowInTrace)"
Constructor with the same parameters as in ProcessQueue 
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP as in ProcessQueue 
.br
\fIname\fP as in ProcessQueue 
.br
\fIsortOrder\fP possible values: ProcessQueueAnimation\&.FIFO ProcessQueueAnimation\&.LIFO 
.br
\fIqCapacity\fP capacity of queue 
.br
\fIshowInReport\fP as in ProcessQueue 
.br
\fIshowInTrace\fP as in ProcessQueue 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.simulator\&.ProcessQueueAnimation< P extends \fBSimProcessAnimation\fP >\&.createAnimation (\fBPosition\fPpos, \fBFormExt\fPform, booleanshowInAnimation)"
create animation with full parameterization 
.PP
\fBParameters:\fP
.RS 4
\fIpos\fP middle point of animation object 
.br
\fIform\fP form of animation object 
.br
\fIshowInAnimation\fP switch animation on or off 
.RE
.PP

.SS "void desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.simulator\&.ProcessQueueAnimation< P extends \fBSimProcessAnimation\fP >\&.createAnimation (\fBComment\fPcomment, \fBPosition\fPpos, \fBFormExt\fPform, booleanshowInAnimation)"
create animation with full parameterization 
.PP
\fBParameters:\fP
.RS 4
\fIcomment\fP 
.br
\fIpos\fP middle point of animation object 
.br
\fIform\fP form of animation object 
.br
\fIcommentStyle\fP 
.br
\fIcommentSize\fP 
.br
\fIcommentColor\fP 
.br
\fIcommentSizeExt\fP 
.br
\fIshowInAnimation\fP switch animation on or off 
.RE
.PP

.SS "String desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.simulator\&.ProcessQueueAnimation< P extends \fBSimProcessAnimation\fP >\&.getInternId ()"
gives the internal Id of this animation object\&. 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Implements \fBdesmoj\&.extensions\&.visualization2d\&.animation\&.core\&.simulator\&.ListInterface\fP\&.
.SS "boolean desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.simulator\&.ProcessQueueAnimation< P extends \fBSimProcessAnimation\fP >\&.insert (Pe)"
insert SimProcess e in sortorder 
.PP
\fBParameters:\fP
.RS 4
\fIe\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
true, when successful 
.RE
.PP

.SS "boolean desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.simulator\&.ProcessQueueAnimation< P extends \fBSimProcessAnimation\fP >\&.insertAfter (Pe, Pafter)"
insert SimProcess e after SimProcess after 
.PP
\fBParameters:\fP
.RS 4
\fIe\fP 
.br
\fIafter\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
true, when successful 
.RE
.PP

.SS "boolean desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.simulator\&.ProcessQueueAnimation< P extends \fBSimProcessAnimation\fP >\&.insertBefore (Pe, Pbefore)"
insert SimProcess e before SimProcess before 
.PP
\fBParameters:\fP
.RS 4
\fIe\fP 
.br
\fIbefore\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
true, when successful 
.RE
.PP

.SS "void desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.simulator\&.ProcessQueueAnimation< P extends \fBSimProcessAnimation\fP >\&.remove (\fBSimProcess\fPe)"

.SS "boolean desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.simulator\&.ProcessQueueAnimation< P extends \fBSimProcessAnimation\fP >\&.remove (intindex)"

.SS "P desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.simulator\&.ProcessQueueAnimation< P extends \fBSimProcessAnimation\fP >\&.removeFirst ()"

.SS "P desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.simulator\&.ProcessQueueAnimation< P extends \fBSimProcessAnimation\fP >\&.removeFirst (Condition< P >c)"

.SS "P desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.simulator\&.ProcessQueueAnimation< P extends \fBSimProcessAnimation\fP >\&.removeLast ()"

.SS "P desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.simulator\&.ProcessQueueAnimation< P extends \fBSimProcessAnimation\fP >\&.removeLast (Condition< P >c)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
