.TH "desmoj.extensions.experimentation.ui.AccessPointTableModel" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.experimentation.ui.AccessPointTableModel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits AbstractTableModel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAccessPointTableModel\fP (Map accpt)"
.br
.ti -1c
.RI "int \fBgetColumnCount\fP ()"
.br
.ti -1c
.RI "int \fBgetRowCount\fP ()"
.br
.ti -1c
.RI "String \fBgetColumnName\fP (int col)"
.br
.ti -1c
.RI "Object \fBgetValueAt\fP (int row, int col)"
.br
.ti -1c
.RI "void \fBsetValueAt\fP (Object o, int row, int col)"
.br
.ti -1c
.RI "boolean \fBisCellEditable\fP (int row, int col)"
.br
.ti -1c
.RI "void \fBgetValues\fP ()"
.br
.ti -1c
.RI "void \fBsetValues\fP ()"
.br
.ti -1c
.RI "Map \fBgetAccessPoints\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Adapter to show a map of access points in a swing table\&.
.PP
\fBAuthor:\fP
.RS 4
Nicolas Knaak 
.RE
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.experimentation\&.ui\&.AccessPointTableModel\&.AccessPointTableModel (Mapaccpt)"
Creates a new table model for the given table of access points
.PP
\fBParameters:\fP
.RS 4
\fIaccessPoints\fP a map containing access point objects 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "Map desmoj\&.extensions\&.experimentation\&.ui\&.AccessPointTableModel\&.getAccessPoints ()"

.PP
\fBReturns:\fP
.RS 4
The access points represented by the table model 
.RE
.PP

.SS "int desmoj\&.extensions\&.experimentation\&.ui\&.AccessPointTableModel\&.getColumnCount ()"

.PP
\fBReturns:\fP
.RS 4
The number of columns\&. It is always 2\&. 
.RE
.PP

.SS "String desmoj\&.extensions\&.experimentation\&.ui\&.AccessPointTableModel\&.getColumnName (intcol)"

.PP
\fBParameters:\fP
.RS 4
\fIcol\fP an index 
.RE
.PP
\fBReturns:\fP
.RS 4
The column name at the given index (0: 'Attribute', 1: 'Value') 
.RE
.PP

.SS "int desmoj\&.extensions\&.experimentation\&.ui\&.AccessPointTableModel\&.getRowCount ()"

.PP
\fBReturns:\fP
.RS 4
The number of rows (number of access points) 
.RE
.PP

.SS "Object desmoj\&.extensions\&.experimentation\&.ui\&.AccessPointTableModel\&.getValueAt (introw, intcol)"

.PP
\fBParameters:\fP
.RS 4
\fIrow\fP row index 
.br
\fIcol\fP column index 
.RE
.PP
\fBReturns:\fP
.RS 4
The value at the given index 
.RE
.PP

.SS "void desmoj\&.extensions\&.experimentation\&.ui\&.AccessPointTableModel\&.getValues ()"
Reads all values from the access points into the table model 
.SS "boolean desmoj\&.extensions\&.experimentation\&.ui\&.AccessPointTableModel\&.isCellEditable (introw, intcol)"
Returns the editable status of the cell at the given index\&. Only cells representing MutableAccessPoints are editable
.PP
\fBParameters:\fP
.RS 4
\fIrow\fP row index 
.br
\fIcol\fP column index 
.RE
.PP
\fBReturns:\fP
.RS 4
true iff the cell at the given index can be edited\&. 
.RE
.PP

.SS "void desmoj\&.extensions\&.experimentation\&.ui\&.AccessPointTableModel\&.setValueAt (Objecto, introw, intcol)"
Sets the value at the given index\&.
.PP
\fBParameters:\fP
.RS 4
\fIrow\fP row index 
.br
\fIcol\fP column index 
.br
\fIo\fP The value to be set 
.RE
.PP

.SS "void desmoj\&.extensions\&.experimentation\&.ui\&.AccessPointTableModel\&.setValues ()"
Writes all values from the table model to the access points\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
