.TH "desmoj.core.observer.Subject< T, X >" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.core.observer.Subject< T, X > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBaddObserver\fP (Observer< T, X > observer)"
.br
.ti -1c
.RI "void \fBdeleteObserver\fP (Observer< T, X > observer)"
.br
.ti -1c
.RI "void \fBnotifyObservers\fP (T subject, X eventObject)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface which an Subject can implement to notify possible Observers
.PP
\fBAuthor:\fP
.RS 4
Christian Mentz
.RE
.PP
\fBParameters:\fP
.RS 4
\fI<T>\fP Class of an possible Subject 
.br
\fI<X>\fP Type of the Event which is passed in the update Method
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Member Function Documentation"
.PP 
.SS "void desmoj\&.core\&.observer\&.Subject< T, X >\&.addObserver (Observer< T, X >observer)"
This method adds an observer to the subject
.PP
\fBParameters:\fP
.RS 4
\fIobserver\fP the observer which should be added to the subject 
.RE
.PP

.SS "void desmoj\&.core\&.observer\&.Subject< T, X >\&.deleteObserver (Observer< T, X >observer)"
This method deletes an observer from the subject
.PP
\fBParameters:\fP
.RS 4
\fIobserver\fP the observer which should be deleted 
.RE
.PP

.SS "void desmoj\&.core\&.observer\&.Subject< T, X >\&.notifyObservers (Tsubject, XeventObject)"
This method is used to notify the registerd observers
.PP
\fBParameters:\fP
.RS 4
\fIsubject\fP reference to the actual subject 
.br
\fIeventObject\fP an eventtype to distinguish different notification types like itemAdded or itemRemoved 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
