.TH "desmoj.extensions.visualization2d.engine.model.EntityType" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization2d.engine.model.EntityType \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.extensions\&.visualization2d\&.engine\&.orga\&.ClassBasic\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEntityType\fP (String id, \fBdesmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Model\fP model, int width, int height, \fBAttribute\fP[] posStates, String[] posAttr, int show)  throws ModelException"
.br
.ti -1c
.RI "boolean \fBaddPossibleAttribut\fP (String attr)"
.br
.ti -1c
.RI "boolean \fBexistPossibleAttribut\fP (String key)"
.br
.ti -1c
.RI "String[] \fBgetPossibleAttributes\fP ()"
.br
.ti -1c
.RI "String \fBgetId\fP ()"
.br
.ti -1c
.RI "\fBdesmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Model\fP \fBgetModell\fP ()"
.br
.ti -1c
.RI "int \fBgetWidth\fP ()"
.br
.ti -1c
.RI "int \fBgetHeight\fP ()"
.br
.ti -1c
.RI "String[] \fBgetPossibleStates\fP ()"
.br
.ti -1c
.RI "boolean \fBexistPosibleState\fP (String state)"
.br
.ti -1c
.RI "String \fBgetImageId\fP (String state)"
.br
.ti -1c
.RI "Image \fBgetImage\fP (String state)  throws ModelException"
.br
.ti -1c
.RI "int \fBgetShow\fP ()"
.br
.ti -1c
.RI "void \fBsetShow\fP (int show)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final int \fBSHOW_NAME\fP = 1"
.br
.ti -1c
.RI "static final int \fBSHOW_ICON\fP = 2"
.br
.in -1c
.SH "Detailed Description"
.PP 
All entities of same entity-type has the same basic properties\&. These are:
.IP "\(bu" 2
same size in animation (width/heigth)
.IP "\(bu" 2
same possible states with same icon for a state
.IP "\(bu" 2
same possible attribute-key's
.PP
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
christian.mueller@th-wildau.de For information about subproject: desmoj\&.extensions\&.visualization2d please have a look at: http://www.th-wildau.de/cmueller/Desmo-J/Visualization2d/
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.EntityType\&.EntityType (Stringid, \fBdesmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Model\fPmodel, intwidth, intheight, \fBAttribute\fP[]posStates, String[]posAttr, intshow) throws \fBModelException\fP"

.PP
\fBParameters:\fP
.RS 4
\fIid\fP EntityTypeId must be unique 
.br
\fImodell\fP 
.br
\fIwidth\fP pixel-size in animation 
.br
\fIheight\fP pixel-size in animation 
.br
\fIposStates\fP \fBAttribute\fP[] with key:state and value:iconId 
.br
\fIposAttr\fP String[] with attribute-keys 
.br
\fIshow\fP combination of show-flags 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBModelException\fP\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "boolean desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.EntityType\&.addPossibleAttribut (Stringattr)"
add an attribute-key as possible 
.PP
\fBParameters:\fP
.RS 4
\fIattr\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
true, when successful 
.RE
.PP

.SS "boolean desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.EntityType\&.existPosibleState (Stringstate)"
check if an state exist 
.PP
\fBParameters:\fP
.RS 4
\fIstate\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
true, when state exist 
.RE
.PP

.SS "boolean desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.EntityType\&.existPossibleAttribut (Stringkey)"
check if an key exist\&. 
.PP
\fBParameters:\fP
.RS 4
\fIkey\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
true, when key exist 
.RE
.PP

.SS "Image desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.EntityType\&.getImage (Stringstate) throws \fBModelException\fP"
get Image of state 
.PP
\fBParameters:\fP
.RS 4
\fIstate\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
image 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBModelException\fP\fP 
.RE
.PP

.SS "String desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.EntityType\&.getImageId (Stringstate)"
get image-id of state 
.PP
\fBParameters:\fP
.RS 4
\fIstate\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
image-id 
.RE
.PP

.SS "String [] desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.EntityType\&.getPossibleAttributes ()"
get all possible attribute-key's 
.PP
\fBReturns:\fP
.RS 4
array of attribute-keys 
.RE
.PP

.SS "String [] desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.EntityType\&.getPossibleStates ()"
get all possible states 
.PP
\fBReturns:\fP
.RS 4
array of states 
.RE
.PP

.SS "int desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.EntityType\&.getShow ()"
Show is the sum of EntityType\&.SHOW_ Flags 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SS "void desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.EntityType\&.setShow (intshow)"
Show is the sum of EntityType\&.SHOW_ Flags 
.PP
\fBParameters:\fP
.RS 4
\fIshow\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
