.TH "desmoj.extensions.visualization2d.engine.command.Cmd" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization2d.engine.command.Cmd \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final char \fBCOMMAND_SEPARATOR\fP = ';'"
.br
.ti -1c
.RI "static final char \fBPARAMETER_SEPARATOR\fP = ','"
.br
.ti -1c
.RI "static final char \fBKEY_VALUE_SEPARATOR\fP = ':'"
.br
.ti -1c
.RI "static final char \fBVALUE_SEPARATOR\fP = '|'"
.br
.ti -1c
.RI "static final String \fBCOMMAND_KEY\fP = 'cmd'"
.br
.ti -1c
.RI "static final String \fBTIME_KEY\fP = 'time'"
.br
.ti -1c
.RI "static final String \fBINIT_KEY\fP = 'init'"
.br
.ti -1c
.RI "static final String \fBEND_CMD\fP = 'end'"
.br
.ti -1c
.RI "static final String \fBREMARK_KEY\fP = 'remark'"
.br
.ti -1c
.RI "static final char \fBREPLACE_CHAR\fP = ' '"
.br
.ti -1c
.RI "static final String \fBNAME_KEY\fP = 'name'"
.br
.ti -1c
.RI "static final String \fBVELOCITY_KEY\fP = 'velocity'"
.br
.ti -1c
.RI "static final String \fBPRIORITY_KEY\fP = 'priority'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface with some constants used in cmds-files\&. This constants are described also in
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
christian.mueller@th-wildau.de For information about subproject: desmoj\&.extensions\&.visualization2d please have a look at: http://www.th-wildau.de/cmueller/Desmo-J/Visualization2d/
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Member Data Documentation"
.PP 
.SS "final String desmoj\&.extensions\&.visualization2d\&.engine\&.command\&.Cmd\&.COMMAND_KEY = 'cmd'\fC [static]\fP"
Name of command-parameter 
.SS "final char desmoj\&.extensions\&.visualization2d\&.engine\&.command\&.Cmd\&.COMMAND_SEPARATOR = ';'\fC [static]\fP"
Every command must end with this sign\&. 
.SS "final String desmoj\&.extensions\&.visualization2d\&.engine\&.command\&.Cmd\&.END_CMD = 'end'\fC [static]\fP"
Name value of last command\&. 
.SS "final String desmoj\&.extensions\&.visualization2d\&.engine\&.command\&.Cmd\&.INIT_KEY = 'init'\fC [static]\fP"
Name of command-parameter\&. 
.SS "final char desmoj\&.extensions\&.visualization2d\&.engine\&.command\&.Cmd\&.KEY_VALUE_SEPARATOR = ':'\fC [static]\fP"
Every \fBParameter\fP has a name and a value\&. This sign separates name and value\&. 
.SS "final String desmoj\&.extensions\&.visualization2d\&.engine\&.command\&.Cmd\&.NAME_KEY = 'name'\fC [static]\fP"
Name of name- parameter and attribute of an entity\&. The name-attribute is the standard-attribute to store the name of an entity\&. When this value is stored in an other attribute, then the name of this attribute is stored in the name-parameter\&. The viewer shows an entity with his name\&. When an entity hasn't a name, the viewer extend a name from its id\&.
.PP
For lists, routes and processes, there is only a name-parameter with a name as value\&. 
.SS "final char desmoj\&.extensions\&.visualization2d\&.engine\&.command\&.Cmd\&.PARAMETER_SEPARATOR = ','\fC [static]\fP"
This sign must be between two command-parameters 
.SS "final String desmoj\&.extensions\&.visualization2d\&.engine\&.command\&.Cmd\&.PRIORITY_KEY = 'priority'\fC [static]\fP"
Name of priority- parameter and attribute of an entity\&. The priority-attribute is the standard-attribute to store the priority of an entity on a list\&. When this value is stored in an other attribute, then the name of this attribute is stored in the priority-parameter\&. 
.SS "final String desmoj\&.extensions\&.visualization2d\&.engine\&.command\&.Cmd\&.REMARK_KEY = 'remark'\fC [static]\fP"
Name of remark parameter\&. This parameter isn't processed\&. 
.SS "final String desmoj\&.extensions\&.visualization2d\&.engine\&.command\&.Cmd\&.TIME_KEY = 'time'\fC [static]\fP"
Name of time parameter 
.SS "final char desmoj\&.extensions\&.visualization2d\&.engine\&.command\&.Cmd\&.VALUE_SEPARATOR = '|'\fC [static]\fP"
In some parameters the value have some parts (e\&.g\&. coordinates)\&. This sign separate this parts\&. 
.SS "final String desmoj\&.extensions\&.visualization2d\&.engine\&.command\&.Cmd\&.VELOCITY_KEY = 'velocity'\fC [static]\fP"
Name of velocity- parameter and attribute of an entity\&. The velocity-attribute is the standard-attribute to store the velocity of an entity on a route\&. When this value is stored in an other attribute, then the name of this attribute is stored in the velocity-parameter\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
