.TH "desmoj.extensions.space3D.RotatingDoneEvent" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.space3D.RotatingDoneEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.core\&.simulator\&.ExternalEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRotatingDoneEvent\fP (\fBModel\fP owner, String name, boolean showInTrace, \fBMovableSpatialObject\fP targetObject)"
.br
.ti -1c
.RI "void \fBeventRoutine\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBRotatingDoneEvent\fP class represents a internal event which notifies a \fBMovableSpatialObject\fP the end of its rotation\&. And it should only be used by a \fBMovableSpatialObject\fP\&. If some other entities call the constructor a DESMOJException will be thrown\&. 
.PP
\fBAuthor:\fP
.RS 4
Fred Sun 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.space3D\&.RotatingDoneEvent\&.RotatingDoneEvent (\fBModel\fPowner, Stringname, booleanshowInTrace, \fBMovableSpatialObject\fPtargetObject)"
Constructs a \fBRotatingDoneEvent\fP and checks whether the caller is a instance of the \fBMovableSpatialObject\fP\&. If not, a DESMOJException will be thrown\&. 
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP The model this event is associated to 
.br
\fIname\fP The name of this event 
.br
\fIshowInTrace\fP Flag for showing event in trace-files\&. Set it to true if event should show up in trace\&. Set it to false if event should not be shown in trace\&. 
.br
\fItargetObject\fP A reference to the object which should be the target of this event\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void desmoj\&.extensions\&.space3D\&.RotatingDoneEvent\&.eventRoutine ()\fC [virtual]\fP"
Implement this method to express the semantics of this external event\&. External events are supposed to act on the model or experiment in general\&. They are not related to a special Entity (unlike method \fCeventRoutine(Entity who)\fP of class \fCEvent\fP)\&. Override this method to implement this Externalevent's behaviour\&. 
.PP
Implements \fBdesmoj\&.core\&.simulator\&.ExternalEvent\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
