.TH "desmoj.core.statistic.DataListTally.DataList" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.core.statistic.DataListTally.DataList \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.core\&.simulator\&.Reportable\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBElement\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataList\fP (\fBModel\fP owner, String name, boolean showInReport, boolean showInTrace)"
.br
.ti -1c
.RI "\fBReporter\fP \fBcreateReporter\fP ()"
.br
.ti -1c
.RI "int \fBgetLength\fP ()"
.br
.ti -1c
.RI "void \fBadd\fP (double value)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "\fBDataList\fP \fBsort\fP (\fBDataList\fP list)"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.ti -1c
.RI "\fBElement\fP \fBgetFirst\fP ()"
.br
.ti -1c
.RI "\fBElement\fP \fBgetLast\fP ()"
.br
.ti -1c
.RI "String \fBgetTallyName\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBDataList\fP \fBnextInStack\fP = null"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A simple List for storing values passed to a \fBTally\fP\&. This list is created to produce low overhead while simulating\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.core\&.statistic\&.DataListTally\&.DataList\&.DataList (\fBModel\fPowner, Stringname, booleanshowInReport, booleanshowInTrace)"
Constructor for a new \fBDataList\fP
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP Model : The model this \fBDataList\fP is associated to 
.br
\fIname\fP java\&.lang\&.String : The name of this \fBDataList\fP object 
.br
\fIshowInReport\fP boolean : Flag for showing the report about this \fBDataList\fP\&. 
.br
\fIshowInTrace\fP boolean : Flag for showing the trace output of this \fBDataList\fP\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void desmoj\&.core\&.statistic\&.DataListTally\&.DataList\&.add (doublevalue)"
Adds an \fBElement\fP to the end of the \fBDataList\fP\&.
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP double : The value of the new \fBElement\fP in the list\&. 
.RE
.PP

.SS "void desmoj\&.core\&.statistic\&.DataListTally\&.DataList\&.clear ()"
Removes all Elements from this List\&. 
.SS "\fBReporter\fP desmoj\&.core\&.statistic\&.DataListTally\&.DataList\&.createReporter ()"
Returns a Reporter to produce a report about this \fBDataList\fP\&.
.PP
\fBReturns:\fP
.RS 4
desmoj\&.report\&.Reporter : The Reporter for this \fBDataList\fP\&. 
.RE
.PP

.SS "\fBElement\fP desmoj\&.core\&.statistic\&.DataListTally\&.DataList\&.getFirst ()"
Returns the list's first \fBElement\fP\&.
.PP
\fBReturns:\fP
.RS 4
the first \fBElement\fP or \fCnull\fP if the list is empty\&. 
.RE
.PP

.SS "\fBElement\fP desmoj\&.core\&.statistic\&.DataListTally\&.DataList\&.getLast ()"
Returns the list's last \fBElement\fP\&.
.PP
\fBReturns:\fP
.RS 4
the last \fBElement\fP of \fCnull\fP if the list is empty\&. 
.RE
.PP

.SS "int desmoj\&.core\&.statistic\&.DataListTally\&.DataList\&.getLength ()"
Returns the list's length\&.
.PP
\fBReturns:\fP
.RS 4
the length of this \fBDataList\fP\&. 
.RE
.PP

.SS "String desmoj\&.core\&.statistic\&.DataListTally\&.DataList\&.getTallyName ()"
Returns the name of the \fBTally\fP, this list belongs to\&.
.PP
\fBReturns:\fP
.RS 4
the \fBTally\fP's name\&. 
.RE
.PP

.SS "\fBDataList\fP desmoj\&.core\&.statistic\&.DataListTally\&.DataList\&.sort (\fBDataList\fPlist)"
Sorts the given list using a merge-sort algorithm
.PP
\fBParameters:\fP
.RS 4
\fIlist\fP \fBDataList\fP : the list to be sorted\&.
.RE
.PP
\fBReturns:\fP
.RS 4
The sorted list\&. 
.RE
.PP

.SS "String desmoj\&.core\&.statistic\&.DataListTally\&.DataList\&.toString ()"
Creates a String containing all Elements of the list and its length\&.
.PP
\fBReturns:\fP
.RS 4
the list as String\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
