.TH "desmoj.core.advancedModellingFeatures.StockBeanInfo" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.core.advancedModellingFeatures.StockBeanInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits SimpleBeanInfo\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "java\&.beans\&.PropertyDescriptor \fBavailPropertyDescriptor\fP ()"
.br
.ti -1c
.RI "java\&.beans\&.MethodDescriptor \fBavgAvailMethodDescriptor\fP ()"
.br
.ti -1c
.RI "java\&.beans\&.PropertyDescriptor \fBcapacityPropertyDescriptor\fP ()"
.br
.ti -1c
.RI "java\&.beans\&.PropertyDescriptor \fBconsumersPropertyDescriptor\fP ()"
.br
.ti -1c
.RI "java\&.beans\&.MethodDescriptor \fBcreateReporterMethodDescriptor\fP ()"
.br
.ti -1c
.RI "java\&.beans\&.BeanInfo[] \fBgetAdditionalBeanInfo\fP ()"
.br
.ti -1c
.RI "java\&.beans\&.BeanDescriptor \fBgetBeanDescriptor\fP ()"
.br
.ti -1c
.RI "java\&.beans\&.MethodDescriptor \fBgetConsQueueStrategyMethodDescriptor\fP ()"
.br
.ti -1c
.RI "java\&.beans\&.MethodDescriptor \fBgetConsRefusedMethodDescriptor\fP ()"
.br
.ti -1c
.RI "java\&.beans\&.EventSetDescriptor[] \fBgetEventSetDescriptors\fP ()"
.br
.ti -1c
.RI "java\&.beans\&.MethodDescriptor[] \fBgetMethodDescriptors\fP ()"
.br
.ti -1c
.RI "java\&.beans\&.MethodDescriptor \fBgetProdQueueStrategyMethodDescriptor\fP ()"
.br
.ti -1c
.RI "java\&.beans\&.MethodDescriptor \fBgetProdRefusedMethodDescriptor\fP ()"
.br
.ti -1c
.RI "java\&.beans\&.MethodDescriptor \fBgetProducerQueueMethodDescriptor\fP ()"
.br
.ti -1c
.RI "java\&.beans\&.PropertyDescriptor[] \fBgetPropertyDescriptors\fP ()"
.br
.ti -1c
.RI "java\&.beans\&.PropertyDescriptor \fBinitialPropertyDescriptor\fP ()"
.br
.ti -1c
.RI "java\&.beans\&.PropertyDescriptor \fBmaximumPropertyDescriptor\fP ()"
.br
.ti -1c
.RI "java\&.beans\&.PropertyDescriptor \fBminimumPropertyDescriptor\fP ()"
.br
.ti -1c
.RI "java\&.beans\&.PropertyDescriptor \fBproducersPropertyDescriptor\fP ()"
.br
.ti -1c
.RI "java\&.beans\&.PropertyDescriptor \fBrefusedPropertyDescriptor\fP ()"
.br
.ti -1c
.RI "java\&.beans\&.MethodDescriptor \fBresetMethodDescriptor\fP ()"
.br
.ti -1c
.RI "java\&.beans\&.MethodDescriptor \fBretrieve_longMethodDescriptor\fP ()"
.br
.ti -1c
.RI "java\&.beans\&.MethodDescriptor \fBstore_longMethodDescriptor\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static java\&.lang\&.reflect\&.Method \fBfindMethod\fP (Class<?> aClass, java\&.lang\&.String methodName, int parameterCount)"
.br
.ti -1c
.RI "static java\&.lang\&.Class< \fBStock\fP > \fBgetBeanClass\fP ()"
.br
.ti -1c
.RI "static java\&.lang\&.String \fBgetBeanClassName\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The bean information class for desmoj\&.Stock\&.
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Member Function Documentation"
.PP 
.SS "java\&.beans\&.PropertyDescriptor desmoj\&.core\&.advancedModellingFeatures\&.StockBeanInfo\&.availPropertyDescriptor ()"
Gets the avail property descriptor\&.
.PP
\fBReturns:\fP
.RS 4
java\&.beans\&.PropertyDescriptor 
.RE
.PP

.SS "java\&.beans\&.MethodDescriptor desmoj\&.core\&.advancedModellingFeatures\&.StockBeanInfo\&.avgAvailMethodDescriptor ()"
Gets the avgAvail() method descriptor\&.
.PP
\fBReturns:\fP
.RS 4
java\&.beans\&.MethodDescriptor 
.RE
.PP

.SS "java\&.beans\&.PropertyDescriptor desmoj\&.core\&.advancedModellingFeatures\&.StockBeanInfo\&.capacityPropertyDescriptor ()"
Gets the capacity property descriptor\&.
.PP
\fBReturns:\fP
.RS 4
java\&.beans\&.PropertyDescriptor 
.RE
.PP

.SS "java\&.beans\&.PropertyDescriptor desmoj\&.core\&.advancedModellingFeatures\&.StockBeanInfo\&.consumersPropertyDescriptor ()"
Gets the consumers property descriptor\&.
.PP
\fBReturns:\fP
.RS 4
java\&.beans\&.PropertyDescriptor 
.RE
.PP

.SS "java\&.beans\&.MethodDescriptor desmoj\&.core\&.advancedModellingFeatures\&.StockBeanInfo\&.createReporterMethodDescriptor ()"
Gets the createReporter() method descriptor\&.
.PP
\fBReturns:\fP
.RS 4
java\&.beans\&.MethodDescriptor 
.RE
.PP

.SS "static java\&.lang\&.reflect\&.Method desmoj\&.core\&.advancedModellingFeatures\&.StockBeanInfo\&.findMethod (Class<?>aClass, java\&.lang\&.StringmethodName, intparameterCount)\fC [static]\fP"
Find the method by comparing (name & parameter size) against the methods in the class\&.
.PP
\fBReturns:\fP
.RS 4
java\&.lang\&.reflect\&.Method 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIaClass\fP java\&.lang\&.Class 
.br
\fImethodName\fP java\&.lang\&.String 
.br
\fIparameterCount\fP int 
.RE
.PP

.SS "java\&.beans\&.BeanInfo [] desmoj\&.core\&.advancedModellingFeatures\&.StockBeanInfo\&.getAdditionalBeanInfo ()"
Returns the BeanInfo of the superclass of this bean to inherit its features\&.
.PP
\fBReturns:\fP
.RS 4
java\&.beans\&.BeanInfo[] 
.RE
.PP

.SS "static java\&.lang\&.Class<\fBStock\fP> desmoj\&.core\&.advancedModellingFeatures\&.StockBeanInfo\&.getBeanClass ()\fC [static]\fP"
Gets the bean class\&.
.PP
\fBReturns:\fP
.RS 4
java\&.lang\&.Class 
.RE
.PP

.SS "static java\&.lang\&.String desmoj\&.core\&.advancedModellingFeatures\&.StockBeanInfo\&.getBeanClassName ()\fC [static]\fP"
Gets the bean class name\&.
.PP
\fBReturns:\fP
.RS 4
java\&.lang\&.String 
.RE
.PP

.SS "java\&.beans\&.MethodDescriptor desmoj\&.core\&.advancedModellingFeatures\&.StockBeanInfo\&.getConsQueueStrategyMethodDescriptor ()"
Gets the getConsQueueStrategy() method descriptor\&.
.PP
\fBReturns:\fP
.RS 4
java\&.beans\&.MethodDescriptor 
.RE
.PP

.SS "java\&.beans\&.MethodDescriptor desmoj\&.core\&.advancedModellingFeatures\&.StockBeanInfo\&.getConsRefusedMethodDescriptor ()"
Gets the getConsRefused() method descriptor\&.
.PP
\fBReturns:\fP
.RS 4
java\&.beans\&.MethodDescriptor 
.RE
.PP

.SS "java\&.beans\&.EventSetDescriptor [] desmoj\&.core\&.advancedModellingFeatures\&.StockBeanInfo\&.getEventSetDescriptors ()"
Return the event set descriptors for this bean\&.
.PP
\fBReturns:\fP
.RS 4
java\&.beans\&.EventSetDescriptor[] 
.RE
.PP

.SS "java\&.beans\&.MethodDescriptor [] desmoj\&.core\&.advancedModellingFeatures\&.StockBeanInfo\&.getMethodDescriptors ()"
Return the method descriptors for this bean\&.
.PP
\fBReturns:\fP
.RS 4
java\&.beans\&.MethodDescriptor[] 
.RE
.PP

.SS "java\&.beans\&.MethodDescriptor desmoj\&.core\&.advancedModellingFeatures\&.StockBeanInfo\&.getProdQueueStrategyMethodDescriptor ()"
Gets the getProdQueueStrategy() method descriptor\&.
.PP
\fBReturns:\fP
.RS 4
java\&.beans\&.MethodDescriptor 
.RE
.PP

.SS "java\&.beans\&.MethodDescriptor desmoj\&.core\&.advancedModellingFeatures\&.StockBeanInfo\&.getProdRefusedMethodDescriptor ()"
Gets the getProdRefused() method descriptor\&.
.PP
\fBReturns:\fP
.RS 4
java\&.beans\&.MethodDescriptor 
.RE
.PP

.SS "java\&.beans\&.MethodDescriptor desmoj\&.core\&.advancedModellingFeatures\&.StockBeanInfo\&.getProducerQueueMethodDescriptor ()"
Gets the getProducerQueue() method descriptor\&.
.PP
\fBReturns:\fP
.RS 4
java\&.beans\&.MethodDescriptor 
.RE
.PP

.SS "java\&.beans\&.PropertyDescriptor [] desmoj\&.core\&.advancedModellingFeatures\&.StockBeanInfo\&.getPropertyDescriptors ()"
Return the property descriptors for this bean\&.
.PP
\fBReturns:\fP
.RS 4
java\&.beans\&.PropertyDescriptor[] 
.RE
.PP

.SS "java\&.beans\&.PropertyDescriptor desmoj\&.core\&.advancedModellingFeatures\&.StockBeanInfo\&.initialPropertyDescriptor ()"
Gets the initial property descriptor\&.
.PP
\fBReturns:\fP
.RS 4
java\&.beans\&.PropertyDescriptor 
.RE
.PP

.SS "java\&.beans\&.PropertyDescriptor desmoj\&.core\&.advancedModellingFeatures\&.StockBeanInfo\&.maximumPropertyDescriptor ()"
Gets the maximum property descriptor\&.
.PP
\fBReturns:\fP
.RS 4
java\&.beans\&.PropertyDescriptor 
.RE
.PP

.SS "java\&.beans\&.PropertyDescriptor desmoj\&.core\&.advancedModellingFeatures\&.StockBeanInfo\&.minimumPropertyDescriptor ()"
Gets the minimum property descriptor\&.
.PP
\fBReturns:\fP
.RS 4
java\&.beans\&.PropertyDescriptor 
.RE
.PP

.SS "java\&.beans\&.PropertyDescriptor desmoj\&.core\&.advancedModellingFeatures\&.StockBeanInfo\&.producersPropertyDescriptor ()"
Gets the producers property descriptor\&.
.PP
\fBReturns:\fP
.RS 4
java\&.beans\&.PropertyDescriptor 
.RE
.PP

.SS "java\&.beans\&.PropertyDescriptor desmoj\&.core\&.advancedModellingFeatures\&.StockBeanInfo\&.refusedPropertyDescriptor ()"
Gets the refused property descriptor\&.
.PP
\fBReturns:\fP
.RS 4
java\&.beans\&.PropertyDescriptor 
.RE
.PP

.SS "java\&.beans\&.MethodDescriptor desmoj\&.core\&.advancedModellingFeatures\&.StockBeanInfo\&.resetMethodDescriptor ()"
Gets the reset() method descriptor\&.
.PP
\fBReturns:\fP
.RS 4
java\&.beans\&.MethodDescriptor 
.RE
.PP

.SS "java\&.beans\&.MethodDescriptor desmoj\&.core\&.advancedModellingFeatures\&.StockBeanInfo\&.retrieve_longMethodDescriptor ()"
Gets the retrieve(long) method descriptor\&.
.PP
\fBReturns:\fP
.RS 4
java\&.beans\&.MethodDescriptor 
.RE
.PP

.SS "java\&.beans\&.MethodDescriptor desmoj\&.core\&.advancedModellingFeatures\&.StockBeanInfo\&.store_longMethodDescriptor ()"
Gets the store(long) method descriptor\&.
.PP
\fBReturns:\fP
.RS 4
java\&.beans\&.MethodDescriptor 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
