.TH "desmoj.extensions.chaining.report.FlexReporterBuilder.Row" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.chaining.report.FlexReporterBuilder.Row \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRow\fP (RowCloseCallback closeCallback)"
.br
.ti -1c
.RI "\fBRow\fP \fBaddCell\fP (Object cellValue)"
.br
.ti -1c
.RI "\fBRow\fP \fBaddHeadingCell\fP (Object cellValue)"
.br
.ti -1c
.RI "\fBFlexReporterBuilder\fP \fBcloseRow\fP ()"
.br
.ti -1c
.RI "LinkedList< \fBCell\fP > \fBgetCells\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a row that will be drawn in the report\&. A row is made up of individual cells 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.chaining\&.report\&.FlexReporterBuilder\&.Row\&.Row (RowCloseCallbackcloseCallback)"
Constructs the \fBRow\fP with the given close callback
.PP
\fBParameters:\fP
.RS 4
\fIcloseCallback\fP A callback object that is notified when a row is closed 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBRow\fP desmoj\&.extensions\&.chaining\&.report\&.FlexReporterBuilder\&.Row\&.addCell (ObjectcellValue)"
Adds a cell with the given value to this row
.PP
\fBParameters:\fP
.RS 4
\fIcellValue\fP The value of the new cell 
.RE
.PP
\fBReturns:\fP
.RS 4
the row for cahining 
.RE
.PP

.SS "\fBRow\fP desmoj\&.extensions\&.chaining\&.report\&.FlexReporterBuilder\&.Row\&.addHeadingCell (ObjectcellValue)"
Adds a heading cell with the given value to this row
.PP
\fBParameters:\fP
.RS 4
\fIcellValue\fP \fBRow\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
the row for cahining 
.RE
.PP

.SS "\fBFlexReporterBuilder\fP desmoj\&.extensions\&.chaining\&.report\&.FlexReporterBuilder\&.Row\&.closeRow ()"
Closes the row so a new one can be opened
.PP
\fBReturns:\fP
.RS 4
The \fBFlexReporterBuilder\fP for chaining 
.RE
.PP

.SS "LinkedList<\fBCell\fP> desmoj\&.extensions\&.chaining\&.report\&.FlexReporterBuilder\&.Row\&.getCells ()"

.PP
\fBReturns:\fP
.RS 4
the list of cells belonging to this row 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
