.TH "desmoj.core.simulator.ExternalEventReset" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.core.simulator.ExternalEventReset \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.core\&.simulator\&.ExternalEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExternalEventReset\fP (\fBModel\fP owner, boolean showInTrace)"
.br
.ti -1c
.RI "void \fBeventRoutine\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
An external event to reset the statistic counters of the model\&.
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Kristof Hamann
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.core\&.simulator\&.ExternalEventReset\&.ExternalEventReset (\fBModel\fPowner, booleanshowInTrace)"
Creates an external event to reset the statistic counters of the model\&. 
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP The external event's model 
.br
\fIshowInTrace\fP Flag for showing this external event in tracemessages 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void desmoj\&.core\&.simulator\&.ExternalEventReset\&.eventRoutine ()\fC [virtual]\fP"
The event routine resets the statistic counters of the model\&. 
.PP
\fBSee Also:\fP
.RS 4
\fBModel::reset()\fP 
.RE
.PP

.PP
Implements \fBdesmoj\&.core\&.simulator\&.ExternalEvent\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
