.TH "desmoj.extensions.experimentation.util.FileUtil" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.experimentation.util.FileUtil \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBcopy\fP (URL source, String destination)"
.br
.ti -1c
.RI "static void \fBcopy\fP (String source, String destination)"
.br
.ti -1c
.RI "static void \fBdeleteFile\fP (String filename)"
.br
.ti -1c
.RI "static void \fBextractFile\fP (String jarArchive, String fileToExtract, String destination)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void desmoj\&.extensions\&.experimentation\&.util\&.FileUtil\&.copy (URLsource, Stringdestination)\fC [static]\fP"
copy the file of a given URL to the given destination
.PP
\fBParameters:\fP
.RS 4
\fIsource\fP URL: the URL of the source file 
.br
\fIdestination\fP String: the filename of the destination 
.RE
.PP

.SS "static void desmoj\&.extensions\&.experimentation\&.util\&.FileUtil\&.copy (Stringsource, Stringdestination)\fC [static]\fP"
copy the file of a given URL to the given destination
.PP
\fBParameters:\fP
.RS 4
\fIsource\fP String: the name of the source file 
.br
\fIdestination\fP String: the filename of the destination 
.RE
.PP

.SS "static void desmoj\&.extensions\&.experimentation\&.util\&.FileUtil\&.deleteFile (Stringfilename)\fC [static]\fP"
deletes a file
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP String: the name of the file to be deleted\&. 
.RE
.PP

.SS "static void desmoj\&.extensions\&.experimentation\&.util\&.FileUtil\&.extractFile (StringjarArchive, StringfileToExtract, Stringdestination)\fC [static]\fP"
extract a file from a jar archive
.PP
\fBParameters:\fP
.RS 4
\fIjarArchive\fP String: the filename of the source archive 
.br
\fIfileToExtract\fP String: the name of the file to extract (full path from archive root) 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
