.TH "desmoj.extensions.visualEvents.MoveEvent" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualEvents.MoveEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.extensions\&.visualEvents\&.VisualEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMoveEvent\fP (Object source, String moverName, \fBMovement\fP movement, boolean focusOnTrack, Vector3d frontSideVec, \fBTimeInstant\fP occurredTime)"
.br
.ti -1c
.RI "\fBMovement\fP \fBgetMovement\fP ()"
.br
.ti -1c
.RI "boolean \fBisFocusedOnTrack\fP ()"
.br
.ti -1c
.RI "Vector3d \fBgetFrontSideVector\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBMoveEvent\fP indicates the event when a SpatialObject is be moving or a new position is set\&. It could be received by visualizing instances or animation recording instances\&. 
.PP
\fBAuthor:\fP
.RS 4
Fred Sun 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.visualEvents\&.MoveEvent\&.MoveEvent (Objectsource, StringmoverName, \fBMovement\fPmovement, booleanfocusOnTrack, Vector3dfrontSideVec, \fBTimeInstant\fPoccurredTime)"
Constructs a \fBMoveEvent\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsource\fP The object on which the event initially occurred\&. 
.br
\fImoverName\fP The name of the object who's moving\&. 
.br
\fImovement\fP The movement which should be performed\&. 
.br
\fIfrontSideVec\fP The front side vector if the focusOnTrack is on\&. 
.br
\fIoccuredTime\fP The TimeInstant when the event occurred\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "Vector3d desmoj\&.extensions\&.visualEvents\&.MoveEvent\&.getFrontSideVector ()"
Gets the front side vector if exists\&. 
.PP
\fBReturns:\fP
.RS 4
The front side vector\&. 
.RE
.PP

.SS "\fBMovement\fP desmoj\&.extensions\&.visualEvents\&.MoveEvent\&.getMovement ()"
Gets the movement which should be performed\&. 
.PP
\fBReturns:\fP
.RS 4
the movement\&. 
.RE
.PP

.SS "boolean desmoj\&.extensions\&.visualEvents\&.MoveEvent\&.isFocusedOnTrack ()"
Shows whether the moving object should focus on the track while performing the movement\&. 
.PP
\fBReturns:\fP
.RS 4
true, if it should focus on the track\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
