.TH "desmoj.extensions.visualization2d.engine.modelGrafic.ViewGrafic" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization2d.engine.modelGrafic.ViewGrafic \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits JLayeredPane, and \fBdesmoj\&.extensions\&.visualization2d\&.engine\&.modelGrafic\&.Grafic\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBViewGrafic\fP (\fBModel\fP model, String viewId)  throws ModelGraficException"
.br
.ti -1c
.RI "Rectangle \fBgetBoundsExtern\fP ()"
.br
.ti -1c
.RI "Point \fBtransformToIntern\fP (Point p)"
.br
.ti -1c
.RI "Point \fBtransformToExtern\fP (Point p)"
.br
.ti -1c
.RI "String \fBgetViewId\fP ()"
.br
.ti -1c
.RI "void \fBpaintZoomMarker\fP (Point zoomPoint, boolean shiftMode)"
.br
.ti -1c
.RI "boolean \fBisInZoomCenter\fP (Point p)"
.br
.ti -1c
.RI "boolean \fBsetZoomFactor\fP (double zoomFactor, Point zoomPoint)"
.br
.ti -1c
.RI "double \fBgetZoomFactor\fP ()"
.br
.ti -1c
.RI "Point \fBgetZoomPoint\fP ()"
.br
.ti -1c
.RI "void \fBupdateInit\fP (long time)"
.br
.ti -1c
.RI "void \fBupdateDynamic\fP (long time)"
.br
.ti -1c
.RI "BufferedImage \fBgetSnapShot\fP (String title)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The Viewer contains TabedPane with different views\&. Each view needs a viewGrafic\&.
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
christian.mueller@th-wildau.de For information about subproject: desmoj\&.extensions\&.visualization2d please have a look at: http://www.th-wildau.de/cmueller/Desmo-J/Visualization2d/
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Member Function Documentation"
.PP 
.SS "Rectangle desmoj\&.extensions\&.visualization2d\&.engine\&.modelGrafic\&.ViewGrafic\&.getBoundsExtern ()"
Construct the smallest rectangle, which include the positions of all entities, routes, lists, processes and stations; 
.PP
\fBReturns:\fP
.RS 4
smallest rectangle 
.RE
.PP

.SS "BufferedImage desmoj\&.extensions\&.visualization2d\&.engine\&.modelGrafic\&.ViewGrafic\&.getSnapShot (Stringtitle)"
Paints a snapshot of this \fBViewGrafic\fP in a BufferedImage\&. Title is printed in top left corner, when title != null 
.PP
\fBParameters:\fP
.RS 4
\fItitle\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
BufferedImage with a snapshot 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
