.TH "desmoj.extensions.visualization2d.engine.modelGrafic.StationGrafic" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization2d.engine.modelGrafic.StationGrafic \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits JComponent, and \fBdesmoj\&.extensions\&.visualization2d\&.engine\&.modelGrafic\&.Grafic\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStationGrafic\fP (\fBStation\fP station, String viewId, Point pointExtern)"
.br
.ti -1c
.RI "String \fBgetViewId\fP ()"
.br
.ti -1c
.RI "void \fBtransform\fP ()"
.br
.ti -1c
.RI "Rectangle \fBgetBoundsExtern\fP ()"
.br
.ti -1c
.RI "Point \fBgetPosition\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static String[] \fBgetViews\fP (\fBModel\fP model)"
.br
.ti -1c
.RI "static Rectangle \fBgetBoundsExternGlobal\fP (\fBModel\fP model, String viewId)"
.br
.ti -1c
.RI "static void \fBupdateInit\fP (\fBModel\fP model, String viewId, JComponent panel)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBpaintComponent\fP (Graphics g)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBGrafic\fP of a station, thats a start- or end- point of route\&.
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
christian.mueller@th-wildau.de For information about subproject: desmoj\&.extensions\&.visualization2d please have a look at: http://www.th-wildau.de/cmueller/Desmo-J/Visualization2d/
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Member Function Documentation"
.PP 
.SS "static Rectangle desmoj\&.extensions\&.visualization2d\&.engine\&.modelGrafic\&.StationGrafic\&.getBoundsExternGlobal (\fBModel\fPmodel, StringviewId)\fC [static]\fP"
Construct the smallest rectangle, which include the positions of all stations in view 
.PP
\fBParameters:\fP
.RS 4
\fIviewId\fP id of view 
.RE
.PP
\fBReturns:\fP
.RS 4
smallest rectangle when an \fBStationGrafic\fP exist, null otherwise 
.RE
.PP

.SS "static String [] desmoj\&.extensions\&.visualization2d\&.engine\&.modelGrafic\&.StationGrafic\&.getViews (\fBModel\fPmodel)\fC [static]\fP"
get all views (viewId's) with Stations 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
