.TH "desmoj.extensions.experimentation.ui.ChartOwner" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.experimentation.ui.ChartOwner \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBdesmoj\&.extensions\&.experimentation\&.ui\&.HistogramPlotter\fP, and \fBdesmoj\&.extensions\&.experimentation\&.ui\&.TimeSeriesPlotter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBdrawChart\fP (Graphics g)"
.br
.in -1c
.SH "Detailed Description"
.PP 
An interface which asks for a method \fBdrawChart()\fP\&. This is needed for the class \fBChart\fP\&. Within the paint() method of \fBChart\fP the \fBdrawChart()\fP method of the given \fBChartOwner\fP is called\&. The \fBdrawChart()\fP method should implement the algorithm which draws the data (e\&.g\&. a histogram or a mathematical function)\&.
.PP
In Desmo-J the \fBHistogramPlotter\fP and the TimerSeriesPlotter are inherited from this interface\&.
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Philip Joschko
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Member Function Documentation"
.PP 
.SS "void desmoj\&.extensions\&.experimentation\&.ui\&.ChartOwner\&.drawChart (Graphicsg)"
This method implements the drawing of the data for a \fBChart\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIg\fP The specified Graphics object\&. 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.extensions\&.experimentation\&.ui\&.TimeSeriesPlotter\fP, and \fBdesmoj\&.extensions\&.experimentation\&.ui\&.HistogramPlotter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
