.TH "desmoj.extensions.grafic.util.TimeSeriesDataSetAdapter" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.grafic.util.TimeSeriesDataSetAdapter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits AbstractXYDataset, XYDataset, DomainInfo, and RangeInfo\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTimeSeriesDataSetAdapter\fP (\fBTimeSeries\fP timeSeries, boolean allowMultipleValues)"
.br
.ti -1c
.RI "Number \fBgetX\fP (int i, int j)"
.br
.ti -1c
.RI "Number \fBgetY\fP (int i, int j)"
.br
.ti -1c
.RI "int \fBgetSeriesCount\fP ()"
.br
.ti -1c
.RI "Comparable \fBgetSeriesKey\fP (int i)"
.br
.ti -1c
.RI "int \fBgetItemCount\fP (int i)"
.br
.ti -1c
.RI "double \fBgetDomainLowerBound\fP ()"
.br
.ti -1c
.RI "double \fBgetDomainLowerBound\fP (boolean flag)"
.br
.ti -1c
.RI "double \fBgetDomainUpperBound\fP ()"
.br
.ti -1c
.RI "double \fBgetDomainUpperBound\fP (boolean flag)"
.br
.ti -1c
.RI "Range \fBgetDomainBounds\fP ()"
.br
.ti -1c
.RI "Range \fBgetDomainBounds\fP (boolean flag)"
.br
.ti -1c
.RI "Range \fBgetDomainRange\fP ()"
.br
.ti -1c
.RI "double \fBgetRangeLowerBound\fP ()"
.br
.ti -1c
.RI "double \fBgetRangeLowerBound\fP (boolean flag)"
.br
.ti -1c
.RI "double \fBgetRangeUpperBound\fP ()"
.br
.ti -1c
.RI "double \fBgetRangeUpperBound\fP (boolean flag)"
.br
.ti -1c
.RI "Range \fBgetRangeBounds\fP (boolean flag)"
.br
.ti -1c
.RI "Range \fBgetValueRange\fP ()"
.br
.ti -1c
.RI "Number \fBgetMinimumDomainValue\fP ()"
.br
.ti -1c
.RI "Number \fBgetMaximumDomainValue\fP ()"
.br
.ti -1c
.RI "Number \fBgetMinimumRangeValue\fP ()"
.br
.ti -1c
.RI "Number \fBgetMaximumRangeValue\fP ()"
.br
.ti -1c
.RI "boolean \fBisValid\fP ()"
.br
.ti -1c
.RI "TimeUnit \fBgetRangeTimeUnit\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class to convert DesmoJ timeseries data into jFreeChart format When in DesmoJ dataset getShowTimeSpansInReport() is set, the data values are interpreted as a timespan in a appropriate time unit\&.
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
christian.mueller@th-wildau.de and goebel@informatik.uni-hamburg.de modified at 4\&.12\&.2012 by christian.mueller@th-wildau.de
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.grafic\&.util\&.TimeSeriesDataSetAdapter\&.TimeSeriesDataSetAdapter (\fBTimeSeries\fPtimeSeries, booleanallowMultipleValues)"
convert a DesmoJ timeserie to an JFREE\&.CHART XYDataset\&. When allowMultipleValues is set, multiple range values of a time value are allowed\&. In the opposite case only the last range value of a time value is accepted\&. In the case timeSeries\&.getShowTimeSpansInReport() the data values are interpreted as a timespan in a appropriate time unit\&. 
.PP
\fBParameters:\fP
.RS 4
\fItimeSeries\fP DesmoJ timeSerie 
.br
\fIallowMultipleValues\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "TimeUnit desmoj\&.extensions\&.grafic\&.util\&.TimeSeriesDataSetAdapter\&.getRangeTimeUnit ()"
in the case timeSeries\&.getShowTimeSpansInReport() a rangeTimeUnit is automatic determined 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SS "boolean desmoj\&.extensions\&.grafic\&.util\&.TimeSeriesDataSetAdapter\&.isValid ()"
is invalid when timeSeries\&.getShowTimeSpansInReport() and timsSeries has negative values 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
