.TH "desmoj.extensions.chaining.report.FlexReporterBuilder.HeadingCell" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.chaining.report.FlexReporterBuilder.HeadingCell \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.extensions\&.chaining\&.report\&.FlexReporterBuilder\&.Cell\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHeadingCell\fP (Object cellValue)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A cell that should be visually displayed as a heading cell in the report\&. For example by drawing it bold\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.chaining\&.report\&.FlexReporterBuilder\&.HeadingCell\&.HeadingCell (ObjectcellValue)"
Constructs a heading cell with the given value
.PP
\fBParameters:\fP
.RS 4
\fIcellValue\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
