.TH "desmoj.extensions.applicationDomains.harbour.MostFreePlaceBlockYardStrategy" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.applicationDomains.harbour.MostFreePlaceBlockYardStrategy \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.core\&.simulator\&.ModelComponent\fP, and \fBdesmoj\&.extensions\&.applicationDomains\&.harbour\&.ChooseBlockYardStrategy\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMostFreePlaceBlockYardStrategy\fP (\fBModel\fP owner)"
.br
.ti -1c
.RI "\fBBlock\fP \fBgetBlock\fP (\fBBlock\fP[] blocks)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBMostFreePlaceBlockYardStrategy\fP presents the strategy that is used by the \fC\fBYard\fP\fP to find a certain block to store a container by the following way: the block with the most free place will be selected\&. \fBMostFreePlaceBlockYardStrategy\fP impements \fC\fBChooseBlockYardStrategy\fP\fP\&.
.PP
\fBSee Also:\fP
.RS 4
\fBChooseBlockYardStrategy\fP 
.PP
\fBModelComponent\fP
.RE
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Eugenia Neufeld
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.applicationDomains\&.harbour\&.MostFreePlaceBlockYardStrategy\&.MostFreePlaceBlockYardStrategy (\fBModel\fPowner)"
Constructs the \fBMostFreePlaceBlockYardStrategy\fP for a yard\&.
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP desmoj\&.Model : The model this \fBMostFreePlaceBlockYardStrategy\fP is associated to\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBBlock\fP desmoj\&.extensions\&.applicationDomains\&.harbour\&.MostFreePlaceBlockYardStrategy\&.getBlock (\fBBlock\fP[]blocks)"
This method describes the \fBMostFreePlaceBlockYardStrategy\fP that is used by the yard and returns the block with the most free place (most place to reserve) to store there\&.
.PP
\fBParameters:\fP
.RS 4
\fIblocks\fP \fC\fBBlock\fP\fP[] : The array of the blocks\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fC\fBBlock\fP\fP[] : the found block\&. 
.RE
.PP

.PP
Implements \fBdesmoj\&.extensions\&.applicationDomains\&.harbour\&.ChooseBlockYardStrategy\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
