.TH "desmoj.extensions.visualization2d.engine.viewer.LanguageSupport" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization2d.engine.viewer.LanguageSupport \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Locale \fBgetLocale\fP ()"
.br
.ti -1c
.RI "String \fBgetString\fP (String key)"
.br
.ti -1c
.RI "URL \fBgetInternURL\fP (String key)"
.br
.ti -1c
.RI "URL \fBgetExternURL\fP (String key)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBLanguageSupport\fP (Locale locale)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
