.TH "desmoj.extensions.visualEvents.VisualEventListener" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualEvents.VisualEventListener \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits EventListener\&.
.PP
Inherited by \fBdesmoj\&.extensions\&.visualization3d\&.VisualizationControl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract void \fBvisualEventReceived\fP (\fBVisualEvent\fP evt)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is the basic listener interface for all the VisualEvents 
.PP
\fBAuthor:\fP
.RS 4
Fred Sun 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "abstract void desmoj\&.extensions\&.visualEvents\&.VisualEventListener\&.visualEventReceived (\fBVisualEvent\fPevt)\fC [pure virtual]\fP"
Invoked when a \fBVisualEvent\fP occurred\&. 
.PP
\fBParameters:\fP
.RS 4
\fIevt\fP The occurred \fBVisualEvent\fP\&. 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.extensions\&.visualization3d\&.VisualizationControl\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
