.TH "desmoj.extensions.space3D.SimpleLocation" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.space3D.SimpleLocation \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.extensions\&.space3D\&.SpatialEntity\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSimpleLocation\fP (\fBModel\fP owner, String name, String type, boolean showInTrace)"
.br
.ti -1c
.RI "\fBSimpleLocation\fP (\fBModel\fP owner, String name, String type, boolean showInTrace, \fBExtendedLength\fP startPositionX, \fBExtendedLength\fP startPositionY, \fBExtendedLength\fP startPositionZ)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This class represents a simple abstract location\&.
.PP
\fBAuthor:\fP
.RS 4
Fred Sun 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.space3D\&.SimpleLocation\&.SimpleLocation (\fBModel\fPowner, Stringname, Stringtype, booleanshowInTrace)"
Creates a \fBSimpleLocation\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP The model this location is associated to\&. 
.br
\fIname\fP The name of the location\&. 
.br
\fItype\fP The type attribute belongs to the \fBSpatialObject\fP interface\&. 
.br
\fIshowInTrace\fP Flag for showing entity in trace-files\&. Set it to true if entity should show up in trace\&. Set to false in entity should not be shown in trace\&. 
.RE
.PP

.SS "desmoj\&.extensions\&.space3D\&.SimpleLocation\&.SimpleLocation (\fBModel\fPowner, Stringname, Stringtype, booleanshowInTrace, \fBExtendedLength\fPstartPositionX, \fBExtendedLength\fPstartPositionY, \fBExtendedLength\fPstartPositionZ)"
Creates a \fBSimpleLocation\fP with specified position\&. 
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP The model this location is associated to\&. 
.br
\fIname\fP The name of the location\&. 
.br
\fItype\fP The type attribute belongs to the \fBSpatialObject\fP interface\&. 
.br
\fIshowInTrace\fP Flag for showing entity in trace-files\&. Set it to true if entity should show up in trace\&. Set to false in entity should not be shown in trace\&. 
.br
\fIstartPositionX\fP The x start position in \fBExtendedLength\fP\&. 
.br
\fIstartPositionY\fP The y start position in \fBExtendedLength\fP\&. 
.br
\fIstartPositionZ\fP The z start position in \fBExtendedLength\fP\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
