.TH "desmoj.extensions.visualization2d.engine.modelGrafic.EntityPosition" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization2d.engine.modelGrafic.EntityPosition \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEntityPosition\fP (double positionX, double positionY, double angle, boolean direction)"
.br
.ti -1c
.RI "void \fBsetX\fP (double x)"
.br
.ti -1c
.RI "double \fBgetX\fP ()"
.br
.ti -1c
.RI "void \fBsetY\fP (double y)"
.br
.ti -1c
.RI "double \fBgetY\fP ()"
.br
.ti -1c
.RI "void \fBsetAngle\fP (double angle)"
.br
.ti -1c
.RI "double \fBgetAngle\fP ()"
.br
.ti -1c
.RI "void \fBsetDirection\fP (boolean direction)"
.br
.ti -1c
.RI "boolean \fBgetDirection\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
describes the position of an entity
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
christian.mueller@th-wildau.de For information about subproject: desmoj\&.extensions\&.visualization2d please have a look at: http://www.th-wildau.de/cmueller/Desmo-J/Visualization2d/
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.visualization2d\&.engine\&.modelGrafic\&.EntityPosition\&.EntityPosition (doublepositionX, doublepositionY, doubleangle, booleandirection)"

.PP
\fBParameters:\fP
.RS 4
\fIpositionX\fP 
.br
\fIpositionY\fP 
.br
\fIangle\fP rotation angle 
.br
\fIdirection\fP icon is not reflected 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
