.TH "desmoj.extensions.visualization2d.animation.processStation.ProcessStationResNoAnimation< Proc extends EntityBasicAnimation >" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization2d.animation.processStation.ProcessStationResNoAnimation< Proc extends EntityBasicAnimation > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.core\&.simulator\&.ModelComponent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProcessStationResNoAnimation\fP (\fBModelAnimation\fP owner, String name, \fBPosition\fP pos, \fBFormExt\fP form, boolean showInAnimation)"
.br
.ti -1c
.RI "\fBProcessStationResNoAnimation\fP (\fBModelAnimation\fP owner, String name, \fBComment\fP comment, \fBPosition\fP pos, \fBFormExt\fP form, boolean showInAnimation)"
.br
.ti -1c
.RI "\fBProcessStationResNoAnimation\fP (\fBModelAnimation\fP owner, String name, \fBPosition\fP pos, \fBFormExt\fP form, String listId, boolean showInAnimation)"
.br
.ti -1c
.RI "\fBProcessStationResNoAnimation\fP (\fBModelAnimation\fP owner, String name, \fBPosition\fP pos, \fBFormExt\fP form, \fBListInterface\fP list, boolean showInAnimation)"
.br
.ti -1c
.RI "\fBProcessStationResNoAnimation\fP (\fBModelAnimation\fP owner, String name, \fBComment\fP comment, \fBPosition\fP pos, \fBFormExt\fP form, \fBListInterface\fP list, boolean showInAnimation)"
.br
.ti -1c
.RI "boolean \fBinsert\fP (java\&.util\&.List< Proc > procEntities)"
.br
.ti -1c
.RI "EntryAnimation< Proc, 
.br
\fBEntityBasicAnimation\fP > \fBremove\fP (Proc e)"
.br
.ti -1c
.RI "int \fBlength\fP ()"
.br
.ti -1c
.RI "java\&.util\&.List< String > \fBgetProcNames\fP (int i)"
.br
.ti -1c
.RI "java\&.util\&.List< String > \fBgetResourceNames\fP (int i)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Animation of ProcessStation with no resources, there are some SimProcesses processed Entities
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
christian.mueller@th-wildau.de For information about subproject: desmoj\&.extensions\&.visualization2d please have a look at: http://www.th-wildau.de/cmueller/Desmo-J/Visualization2d/
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&.
.PP
\fBParameters:\fP
.RS 4
\fI<Proc>\fP SimProcesses as processed Entity 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.visualization2d\&.animation\&.processStation\&.ProcessStationResNoAnimation< Proc extends \fBEntityBasicAnimation\fP >\&.ProcessStationResNoAnimation (\fBModelAnimation\fPowner, Stringname, \fBPosition\fPpos, \fBFormExt\fPform, booleanshowInAnimation)"
Build a ProcessStation\&. This Station contains some process entries\&. Each Entry contains some animated process and no resource entities\&. With insert a new process entry is created and with remove a process entry will be deleted\&. A process entry looks like a working station\&. 
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP 
.br
\fIname\fP 
.br
\fIpos\fP 
.br
\fIform\fP 
.br
\fIshowInAnimation\fP 
.RE
.PP

.SS "desmoj\&.extensions\&.visualization2d\&.animation\&.processStation\&.ProcessStationResNoAnimation< Proc extends \fBEntityBasicAnimation\fP >\&.ProcessStationResNoAnimation (\fBModelAnimation\fPowner, Stringname, \fBComment\fPcomment, \fBPosition\fPpos, \fBFormExt\fPform, booleanshowInAnimation)"
Build a ProcessStation\&. This Station contains some process entries\&. Each Entry contains some animated process and no resource entities\&. With insert a new process entry is created and with remove a process entry will be deleted\&. A process entry looks like a working station\&. 
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP 
.br
\fIname\fP 
.br
\fIcomment\fP 
.br
\fIpos\fP 
.br
\fIform\fP 
.br
\fIshowInAnimation\fP 
.RE
.PP

.SS "desmoj\&.extensions\&.visualization2d\&.animation\&.processStation\&.ProcessStationResNoAnimation< Proc extends \fBEntityBasicAnimation\fP >\&.ProcessStationResNoAnimation (\fBModelAnimation\fPowner, Stringname, \fBPosition\fPpos, \fBFormExt\fPform, StringlistId, booleanshowInAnimation)"
Build a ProcessStation\&. This Station contains some process entries\&. Each Entry contains some animated process and no resource entities\&. With insert a new process entry is created and with remove a process entry will be deleted\&. A process entry looks like a working station\&. 
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP 
.br
\fIname\fP 
.br
\fIpos\fP 
.br
\fIform\fP 
.br
\fIlistId\fP not used 
.br
\fIshowInAnimation\fP 
.RE
.PP

.SS "desmoj\&.extensions\&.visualization2d\&.animation\&.processStation\&.ProcessStationResNoAnimation< Proc extends \fBEntityBasicAnimation\fP >\&.ProcessStationResNoAnimation (\fBModelAnimation\fPowner, Stringname, \fBComment\fPcomment, \fBPosition\fPpos, \fBFormExt\fPform, \fBListInterface\fPlist, booleanshowInAnimation)"
Build a ProcessStation\&. This Station contains some process entries\&. Each Entry contains some animated process and no resource entities\&. With insert a new process entry is created and with remove a process entry will be deleted\&. A process entry looks like a working station\&. 
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP used model 
.br
\fIname\fP name of process-station 
.br
\fIpos\fP middle point of animation object 
.br
\fIform\fP form of animation object 
.br
\fIlist\fP queue from where process-entities are coming, maybe null 
.br
\fIshowInAnimation\fP switch animation on or off 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "java\&.util\&.List<String> desmoj\&.extensions\&.visualization2d\&.animation\&.processStation\&.ProcessStationResNoAnimation< Proc extends \fBEntityBasicAnimation\fP >\&.getProcNames (inti)"
Gives names of Proc entities in entry i\&. 
.PP
\fBParameters:\fP
.RS 4
\fIi\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "java\&.util\&.List<String> desmoj\&.extensions\&.visualization2d\&.animation\&.processStation\&.ProcessStationResNoAnimation< Proc extends \fBEntityBasicAnimation\fP >\&.getResourceNames (inti)"
Gives names of Res entities in entry i\&. For each abstract entity an empty string is given\&. 
.PP
\fBParameters:\fP
.RS 4
\fIi\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "boolean desmoj\&.extensions\&.visualization2d\&.animation\&.processStation\&.ProcessStationResNoAnimation< Proc extends \fBEntityBasicAnimation\fP >\&.insert (java\&.util\&.List< Proc >procEntities)"
Create a new process entry with process entities\&. 
.PP
\fBParameters:\fP
.RS 4
\fIprocEntities\fP Array of process entities 
.RE
.PP
\fBReturns:\fP
.RS 4
true, when successful 
.RE
.PP

.SS "int desmoj\&.extensions\&.visualization2d\&.animation\&.processStation\&.ProcessStationResNoAnimation< Proc extends \fBEntityBasicAnimation\fP >\&.length ()"
Gives nr of entries in station\&. 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SS "EntryAnimation<Proc, \fBEntityBasicAnimation\fP> desmoj\&.extensions\&.visualization2d\&.animation\&.processStation\&.ProcessStationResNoAnimation< Proc extends \fBEntityBasicAnimation\fP >\&.remove (Proce)"
Remove the process entry which contains the process entity e\&. All entities of the removed entry are removed also\&. 
.PP
\fBParameters:\fP
.RS 4
\fIe\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
the removed Entry, null when not successful 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
