.TH "desmoj.core.report.MessageReceiver" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.core.report.MessageReceiver \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBdesmoj\&.core\&.report\&.DebugFileOut\fP, \fBdesmoj\&.core\&.report\&.ErrorFileOut\fP, \fBdesmoj\&.core\&.report\&.MessageDistributor\fP, \fBdesmoj\&.core\&.report\&.OutputType\fP, \fBdesmoj\&.core\&.report\&.ReportFileOut\fP, \fBdesmoj\&.core\&.report\&.ScreenOutput\fP, \fBdesmoj\&.core\&.report\&.StandardFileOut\fP, and \fBdesmoj\&.core\&.report\&.TraceFileOut\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBreceive\fP (\fBMessage\fP m)"
.br
.ti -1c
.RI "void \fBreceive\fP (\fBdesmoj\&.core\&.report\&.Reporter\fP r)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provides the basic interface implemented by all classes receiving messages of any type in the DESMO-J framework\&. This allows for flexible organisation of the messaging subsystem, enabling different kinds of output paths for different kinds of messages, including multiple outputs of the same type of message\&.
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Tim Lechler
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Member Function Documentation"
.PP 
.SS "void desmoj\&.core\&.report\&.MessageReceiver\&.receive (\fBMessage\fPm)"
Implement this method to define the behaviour of the messagereceiver when messages are sent to it\&.
.PP
\fBParameters:\fP
.RS 4
\fIm\fP \fBMessage\fP : The message sent to the messagereceiver 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.core\&.report\&.MessageDistributor\fP, \fBdesmoj\&.extensions\&.xml\&.report\&.XMLReportOutput\fP, \fBdesmoj\&.core\&.report\&.TraceFileOut\fP, \fBdesmoj\&.core\&.report\&.ErrorFileOut\fP, \fBdesmoj\&.core\&.report\&.DebugFileOut\fP, \fBdesmoj\&.core\&.report\&.ReportFileOut\fP, \fBdesmoj\&.core\&.report\&.StandardFileOut\fP, \fBdesmoj\&.extensions\&.xml\&.report\&.XMLTraceOutput\fP, \fBdesmoj\&.core\&.report\&.ScreenOutput\fP, and \fBdesmoj\&.core\&.report\&.NullOutput\fP\&.
.SS "void desmoj\&.core\&.report\&.MessageReceiver\&.receive (\fBdesmoj\&.core\&.report\&.Reporter\fPr)"
Implement this method to define the behaviour of the messagereceiver when reporters are sent to it\&.
.PP
\fBParameters:\fP
.RS 4
\fIr\fP \fBReporter\fP : The reporter sent to the messagereceiver 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.core\&.report\&.MessageDistributor\fP, \fBdesmoj\&.core\&.report\&.ErrorFileOut\fP, \fBdesmoj\&.core\&.report\&.TraceFileOut\fP, \fBdesmoj\&.core\&.report\&.DebugFileOut\fP, \fBdesmoj\&.core\&.report\&.ReportFileOut\fP, and \fBdesmoj\&.core\&.report\&.ReportMultRowsFileOut\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
