.TH "desmoj.extensions.visualEvents.SetVisibleEvent" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualEvents.SetVisibleEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.extensions\&.visualEvents\&.VisualEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSetVisibleEvent\fP (Object source, String affectedSpatialObjectName, boolean visibleEnable, \fBTimeInstant\fP occurredTime)"
.br
.ti -1c
.RI "boolean \fBgetVisible\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This event sets the visibility of the visible representation of an object\&.
.PP
\fBAuthor:\fP
.RS 4
Fred Sun 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.visualEvents\&.SetVisibleEvent\&.SetVisibleEvent (Objectsource, StringaffectedSpatialObjectName, booleanvisibleEnable, \fBTimeInstant\fPoccurredTime)"

.PP
\fBParameters:\fP
.RS 4
\fIsource\fP 
.br
\fIaffectedSpatialObjectName\fP 
.br
\fIoccurredTime\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "boolean desmoj\&.extensions\&.visualEvents\&.SetVisibleEvent\&.getVisible ()"
Gets the boolean value which shows whether the target should be visible or not\&.
.PP
\fBReturns:\fP
.RS 4
True, if the target should be visible\&. Else, false\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
