.TH "desmoj.extensions.visualEvents.AttachEvent" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualEvents.AttachEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.extensions\&.visualEvents\&.VisualEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAttachEvent\fP (Object source, String attacherObjectName, String hostName, \fBTimeInstant\fP occurredTime)"
.br
.ti -1c
.RI "String \fBgetHostName\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBAttachEvent\fP indicates that a MovableSpatialObject is attached to an other\&. 
.PP
\fBAuthor:\fP
.RS 4
Fred Sun 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.visualEvents\&.AttachEvent\&.AttachEvent (Objectsource, StringattacherObjectName, StringhostName, \fBTimeInstant\fPoccurredTime)"
Constructs an \fBAttachEvent\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsource\fP The object on which the event initially occurred\&. 
.br
\fIattacherObjectName\fP The name of the object who's attached to a host\&. 
.br
\fIThe\fP name of the object which is attached by the attacher\&. 
.br
\fIoccurredTime\fP The TimeInstant when the event occurred\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "String desmoj\&.extensions\&.visualEvents\&.AttachEvent\&.getHostName ()"
Gets the ID of the host\&. 
.PP
\fBReturns:\fP
.RS 4
The ID of the host\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
