.TH "desmoj.extensions.applicationDomains.harbour.ExternalTransporter" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.applicationDomains.harbour.ExternalTransporter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.core\&.simulator\&.SimProcess\fP\&.
.PP
Inherited by \fBdesmoj\&.extensions\&.applicationDomains\&.harbour\&.Ship\fP, and \fBdesmoj\&.extensions\&.applicationDomains\&.harbour\&.Truck\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExternalTransporter\fP (\fBModel\fP owner, String name, long nImportGoods, long nExportGoods, boolean showInTrace)"
.br
.ti -1c
.RI "void \fBsetNumberOfImportGoods\fP (long n)"
.br
.ti -1c
.RI "long \fBgetNumberOfImportGoods\fP ()"
.br
.ti -1c
.RI "void \fBsetNumberOfExportGoods\fP (long n)"
.br
.ti -1c
.RI "long \fBgetNumberOfExportGoods\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
An \fBExternalTransporter\fP is represents any kind of an external transporter ( \fC\fBShip\fP\fP,\fC\fBTruck\fP\fP, Train)that arrives in a container terminal to deliver and/or pick up some containers (goods)\&. It has a certain number of import/export containers that must have loaded/unloaded before it can leave a container terminal\&. The both numbers must be not negative\&. \fBExternalTransporter\fP is derived from SimProcess\&. Its \fC\fBlifeCycle()\fP\fP must be implemented by the user in order to specify the behavior of the \fBExternalTransporter\fP\&.
.PP
\fBSee Also:\fP
.RS 4
\fBSimProcess\fP
.RE
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Eugenia Neufeld
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.applicationDomains\&.harbour\&.ExternalTransporter\&.ExternalTransporter (\fBModel\fPowner, Stringname, longnImportGoods, longnExportGoods, booleanshowInTrace)"
Constructs an \fBExternalTransporter\fP which arrives at a container terminal to deliver and/or pick up some containers (goods)\&. Implement its or more its derived classes \fC\fBlifeCycle()\fP\fP method like \fC\fBShip\fP\fP,\fC\fBTruck\fP\fP or Train to specify its behavior\&. An External Transporter has a number of import/export containers that must have loaded/unloaded before it can leave a container terminal\&. Both must not be negative\&. Their default value is one\&.
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP desmoj\&.Model : The model this \fBExternalTransporter\fP is associated to\&. 
.br
\fIname\fP java\&.lang\&.String : The name of this \fBExternalTransporter\fP\&. 
.br
\fInImportGoods\fP long : The number of import goods this \fBExternalTransporter\fP has to bring /take to/from container terminal\&. 
.br
\fInExportGoods\fP long : The number of export goods this \fBExternalTransporter\fP has to take /bring from/to container terminal\&. 
.br
\fIshowInTrace\fP boolean : Flag, if this ExternaTransporter should produce a trace output or not\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "long desmoj\&.extensions\&.applicationDomains\&.harbour\&.ExternalTransporter\&.getNumberOfExportGoods ()"
Returns the number of export goods (containers) of this \fBExternalTransporter\fP\&.
.PP
\fBReturns:\fP
.RS 4
long : The number of export goods of this \fBExternalTransporter\fP\&. 
.RE
.PP

.SS "long desmoj\&.extensions\&.applicationDomains\&.harbour\&.ExternalTransporter\&.getNumberOfImportGoods ()"
Returns the number of import goods (containers) of this \fBExternalTransporter\fP\&.
.PP
\fBReturns:\fP
.RS 4
long : The number of import goods of this \fBExternalTransporter\fP\&. 
.RE
.PP

.SS "void desmoj\&.extensions\&.applicationDomains\&.harbour\&.ExternalTransporter\&.setNumberOfExportGoods (longn)"
Sets the number of export goods (containers) of this \fBExternalTransporter\fP to a new value\&. The new value must not be negative\&.
.PP
\fBParameters:\fP
.RS 4
\fIn\fP long : The new number of export goods of this \fBExternalTransporter\fP\&. 
.RE
.PP

.SS "void desmoj\&.extensions\&.applicationDomains\&.harbour\&.ExternalTransporter\&.setNumberOfImportGoods (longn)"
Sets the number of import goods (containers) of this \fBExternalTransporter\fP to a new value\&. The new value must not be negative\&.
.PP
\fBParameters:\fP
.RS 4
\fIn\fP long : The new number of import goods of this \fBExternalTransporter\fP\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
