.TH "desmoj.extensions.visualEvents.MovementInterruptEvent" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualEvents.MovementInterruptEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.extensions\&.visualEvents\&.VisualEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMovementInterruptEvent\fP (Object source, String affectedSpatialObjectName, double[] stoppedAtPosition, \fBTimeInstant\fP occurredTime)"
.br
.ti -1c
.RI "double[] \fBgetStoppedAtPosition\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
A \fBMovementInterruptEvent\fP indicates that a MovabelSpatialSimProcess's movement has been interrupted\&. 
.PP
\fBAuthor:\fP
.RS 4
Fred Sun 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.visualEvents\&.MovementInterruptEvent\&.MovementInterruptEvent (Objectsource, StringaffectedSpatialObjectName, double[]stoppedAtPosition, \fBTimeInstant\fPoccurredTime)"
Constructs a \fBMovementInterruptEvent\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsource\fP The object on which the event initially occurred\&. 
.br
\fIaffectedSpatialObjectName\fP The name of the object who's movement is interrupted\&. 
.br
\fIstoppedAtPosition\fP The position where the performer has to be when this event occurs\&. 
.br
\fIoccurredTime\fP The TimeInstant when the event occurred\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "double [] desmoj\&.extensions\&.visualEvents\&.MovementInterruptEvent\&.getStoppedAtPosition ()"
Returns the position where the involved object has to be when this event occurs\&. 
.PP
\fBReturns:\fP
.RS 4
The position\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
