.TH "desmoj.extensions.visualization3d.VisualizationClockAlpha" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization3d.VisualizationClockAlpha \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Alpha\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVisualizationClockAlpha\fP (long duration)"
.br
.ti -1c
.RI "float \fBvalue\fP ()"
.br
.ti -1c
.RI "boolean \fBfinished\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This Alpha uses the \fBVisualizationClock\fP instead of the system clock for speed control\&. Everything else is the same like Alpha class\&.  For more information see \fCjavax\&.media\&.j3d\&.Alpha\fP
.PP
\fBAuthor:\fP
.RS 4
Fred Sun 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.visualization3d\&.VisualizationClockAlpha\&.VisualizationClockAlpha (longduration)"
Constructs an \fBVisualizationClockAlpha\fP object with specified duration\&.
.PP
\fBParameters:\fP
.RS 4
\fIduration\fP The duration of this alpha\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
