.TH "desmoj.extensions.chaining.report.FlexReporterBuilder.Cell" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.chaining.report.FlexReporterBuilder.Cell \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBdesmoj\&.extensions\&.chaining\&.report\&.FlexReporterBuilder\&.HeadingCell\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCell\fP (Object cellValue)"
.br
.ti -1c
.RI "String \fBgetValue\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a cell that will be drawn in a report 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.chaining\&.report\&.FlexReporterBuilder\&.Cell\&.Cell (ObjectcellValue)"
Constructs a cell with the given value
.PP
\fBParameters:\fP
.RS 4
\fIcellValue\fP The value of the cell 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "String desmoj\&.extensions\&.chaining\&.report\&.FlexReporterBuilder\&.Cell\&.getValue ()"

.PP
\fBReturns:\fP
.RS 4
the value of the cell 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
