.TH "desmoj.extensions.visualization2d.engine.modelGrafic.ModelGrafic" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization2d.engine.modelGrafic.ModelGrafic \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits JPanel, \fBdesmoj\&.extensions\&.visualization2d\&.engine\&.modelGrafic\&.Grafic\fP, and ChangeListener\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBZoomEntry\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModelGrafic\fP (\fBModel\fP model)  throws ModelGraficException"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "Rectangle \fBgetBoundsExtern\fP ()"
.br
.ti -1c
.RI "Point \fBtransformToIntern\fP (String viewId, Point p)"
.br
.ti -1c
.RI "Point \fBtransformToIntern\fP (Point p)"
.br
.ti -1c
.RI "Point \fBtransformToExtern\fP (String viewId, Point p)"
.br
.ti -1c
.RI "Point \fBtransformToExtern\fP (Point p)"
.br
.ti -1c
.RI "\fBViewGrafic\fP \fBgetSelectedView\fP ()"
.br
.ti -1c
.RI "String \fBgetSelectedViewId\fP ()"
.br
.ti -1c
.RI "JScrollPane \fBgetSelectedComponent\fP ()"
.br
.ti -1c
.RI "void \fBpaintZoomMarker\fP (Point zoomPoint, boolean shiftMode)"
.br
.ti -1c
.RI "boolean \fBisInZoomCenter\fP (Point p)"
.br
.ti -1c
.RI "void \fBsetZoomFactor\fP (double zoomFactor, Point zoomPoint, long time)"
.br
.ti -1c
.RI "double \fBgetZoomFactor\fP (String viewId)"
.br
.ti -1c
.RI "Point \fBgetZoomPoint\fP (String viewId)"
.br
.ti -1c
.RI "Hashtable< String, \fBZoomEntry\fP > \fBgetZoomProperty\fP ()"
.br
.ti -1c
.RI "void \fBsetZoomProperty\fP (Hashtable< String, \fBZoomEntry\fP > zoomProperty)"
.br
.ti -1c
.RI "void \fBupdateInit\fP (long time)"
.br
.ti -1c
.RI "void \fBupdateDynamic\fP (long time)"
.br
.ti -1c
.RI "void \fBstateChanged\fP (ChangeEvent e)"
.br
.ti -1c
.RI "boolean \fBmakeSnapShot\fP (File directory, boolean all)  throws IOException"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The grafic of a model is an JPanel with all animated objects\&.
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
christian.mueller@th-wildau.de For information about subproject: desmoj\&.extensions\&.visualization2d please have a look at: http://www.th-wildau.de/cmueller/Desmo-J/Visualization2d/
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Member Function Documentation"
.PP 
.SS "Rectangle desmoj\&.extensions\&.visualization2d\&.engine\&.modelGrafic\&.ModelGrafic\&.getBoundsExtern ()"
Construct the smallest rectangle, which include the positions of all entities, routes, lists, processes and stations; 
.PP
\fBReturns:\fP
.RS 4
smallest rectangle 
.RE
.PP

.SS "boolean desmoj\&.extensions\&.visualization2d\&.engine\&.modelGrafic\&.ModelGrafic\&.makeSnapShot (Filedirectory, booleanall) throws IOException"
make snapshots as png image and store it into directory 
.PP
\fBParameters:\fP
.RS 4
\fIdirectory\fP A directory 
.br
\fIall\fP Make snapshots from all views or only from the actual selected view 
.RE
.PP
\fBReturns:\fP
.RS 4
returnCode 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIIOException\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
