.TH "desmoj.extensions.applicationDomains.harbour.MyTruck" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.applicationDomains.harbour.MyTruck \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Condition< Truck >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMyTruck\fP (\fBModel\fP owner, String name, \fBLane\fP lane, boolean showInTrace)"
.br
.ti -1c
.RI "boolean \fBcheck\fP (\fBTruck\fP t)"
.br
.ti -1c
.RI "void \fBsetLane\fP (\fBLane\fP l)"
.br
.ti -1c
.RI "\fBLane\fP \fBgetLane\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This condition should check if the number of lane of the truck where he waits for an internal transporter at the \fC\fBHoldingArea\fP\fP is equal the number of the lane of this condition\&. The condition is used by an internal transporter to find the needed truck that it has to unload/load\&.
.PP
\fBSee Also:\fP
.RS 4
Condition
.RE
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Eugenia Neufeld
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.applicationDomains\&.harbour\&.MyTruck\&.MyTruck (\fBModel\fPowner, Stringname, \fBLane\fPlane, booleanshowInTrace)"
Constructs a \fBMyTruck\fP condition with all the given parameters\&.
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP desmoj\&.Model : The model this \fBMyTruck\fP condition belongs to\&. 
.br
\fIname\fP java\&.lang\&.String : The name of this \fBMyTruck\fP condition\&. 
.br
\fIlane\fP \fBLane\fP : The lane of this \fBMyTruck\fP condition\&. 
.br
\fIshowInTrace\fP boolean : Flag, if this \fBMyTruck\fP condition should produce a trace output or not\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "boolean desmoj\&.extensions\&.applicationDomains\&.harbour\&.MyTruck\&.check (\fBTruck\fPt)"
Returns a boolean showing whether the number of the truck lane is equal to the condition lane\&.
.PP
\fBReturns:\fP
.RS 4
boolean : Is \fCtrue\fP, if the number of the lanes are equal, \fCfalse\fP otherwise\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIe\fP Entity : The entity (\fBTruck\fP) to test\&. 
.RE
.PP

.SS "\fBLane\fP desmoj\&.extensions\&.applicationDomains\&.harbour\&.MyTruck\&.getLane ()"
Returns the lane that must be checked with the truck lane\&.
.PP
\fBReturns:\fP
.RS 4
\fC\fBLane\fP\fP: The lane of this condition\&. 
.RE
.PP

.SS "void desmoj\&.extensions\&.applicationDomains\&.harbour\&.MyTruck\&.setLane (\fBLane\fPl)"
Sets the lane that must be checked with the truck lane \&.
.PP
\fBParameters:\fP
.RS 4
\fIl\fP \fC\fBLane\fP\fP: The new lane for this condition \&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
