.TH "desmoj.extensions.visualization2d.animation.BackgroundLineAnimation" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization2d.animation.BackgroundLineAnimation \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBackgroundLineAnimation\fP (\fBModelAnimation\fP owner, String baseId, int lineSize, \fBPosition\fP startPoint, Point[] addPoints, double level, Color lineColor, boolean showInAnimation)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Background elements are rectangles\&. There are two types:
.IP "\(bu" 2
One has fixed corner points and
.IP "\(bu" 2
the other has a fixed middle point\&. The size is set also or comes from the text element\&. It is possible to show a text in the rectangle\&. There is a automatic word wrapping\&. For an explicit newline use a 
.br
 tag\&. The text- position, size and style can be set explicitly\&. The colors of text and background can be set also\&. When background is null, the background is transparent\&. The level value determine the order of painting\&. Elements with low level value are painted in front of elements with high level\&.
.PP
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
christian.mueller@th-wildau.de For information about subproject: desmoj\&.extensions\&.visualization2d please have a look at: http://www.th-wildau.de/cmueller/Desmo-J/Visualization2d/
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.visualization2d\&.animation\&.BackgroundLineAnimation\&.BackgroundLineAnimation (\fBModelAnimation\fPowner, StringbaseId, intlineSize, \fBPosition\fPstartPoint, Point[]addPoints, doublelevel, ColorlineColor, booleanshowInAnimation)"
paint a line in background 
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP Simulation model 
.br
\fIbaseId\fP A internal Name\&. The framework generate with this name an id 
.br
\fIlineSize\fP Size of line in pixel\&. Look at BackgroundLine\&.LineSize\&.\&.\&.\&. 
.br
\fIstartPoint\fP Startpoint of Line 
.br
\fIaddPoints\fP Additional points of line 
.br
\fIlevel\fP Elements with low level are painted in front of elements with high level 
.br
\fIlineColor\fP Color of line 
.br
\fIshowInAnimation\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
