.TH "desmoj.extensions.visualization2d.animation.core.advancedModellingFeatures.WaitQueueAnimation" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization2d.animation.core.advancedModellingFeatures.WaitQueueAnimation \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits WaitQueue\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWaitQueueAnimation\fP (\fBModelAnimation\fP owner, String name, int masterSortOrder, int masterQCapacity, int slaveSortOrder, int slaveQCapacity, boolean showInReport, boolean showInTrace)"
.br
.ti -1c
.RI "\fBWaitQueueAnimation\fP (\fBModelAnimation\fP owner, String name, boolean showInReport, boolean showInTrace)"
.br
.ti -1c
.RI "void \fBcreateAnimation\fP (\fBPosition\fP pos, \fBFormExt\fP form, boolean showInAnimation)"
.br
.ti -1c
.RI "String \fBgetInternId\fP ()"
.br
.ti -1c
.RI "boolean \fBcooperate\fP (\fBProcessCoopAnimation\fP coop)"
.br
.ti -1c
.RI "boolean \fBcooperate\fP (\fBProcessCoopAnimation\fP coop, Condition cond)"
.br
.ti -1c
.RI "boolean \fBwaitOnCoop\fP ()"
.br
.ti -1c
.RI "boolean \fBanimationIsOn\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Animation of a WaitQueue
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
christian.mueller@th-wildau.de For information about subproject: desmoj\&.extensions\&.visualization2d please have a look at: http://www.th-wildau.de/cmueller/Desmo-J/Visualization2d/
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.advancedModellingFeatures\&.WaitQueueAnimation\&.WaitQueueAnimation (\fBModelAnimation\fPowner, Stringname, intmasterSortOrder, intmasterQCapacity, intslaveSortOrder, intslaveQCapacity, booleanshowInReport, booleanshowInTrace)"
Constructor with same parameters as WaitQueue 
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP used model 
.br
\fIname\fP as in WaitQueue 
.br
\fImasterSortOrder\fP as in WaitQueue 
.br
\fImasterQCapacity\fP as in WaitQueue 
.br
\fIslaveSortOrder\fP as in WaitQueue 
.br
\fIslaveQCapacity\fP as in WaitQueue 
.br
\fIshowInReport\fP as in WaitQueue 
.br
\fIshowInTrace\fP as in WaitQueue 
.RE
.PP

.SS "desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.advancedModellingFeatures\&.WaitQueueAnimation\&.WaitQueueAnimation (\fBModelAnimation\fPowner, Stringname, booleanshowInReport, booleanshowInTrace)"
Constructor with same parameters as WaitQueue 
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP used model 
.br
\fIname\fP as in WaitQueue 
.br
\fIshowInReport\fP as in WaitQueue 
.br
\fIshowInTrace\fP as in WaitQueue 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "boolean desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.advancedModellingFeatures\&.WaitQueueAnimation\&.cooperate (\fBProcessCoopAnimation\fPcoop)"
This method is called from a SimProcessAnimation which wants to cooperate as master 
.PP
\fBParameters:\fP
.RS 4
\fIcoop\fP as in waitQueue 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "boolean desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.advancedModellingFeatures\&.WaitQueueAnimation\&.cooperate (\fBProcessCoopAnimation\fPcoop, Conditioncond)"
This method is called from a SimProcessAnimation which wants to cooperate as master and is looking for a slave complying to a certain condition described in cond 
.PP
\fBParameters:\fP
.RS 4
\fIcoop\fP as in waitQueue 
.br
\fIcond\fP as in waitQueue 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "void desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.advancedModellingFeatures\&.WaitQueueAnimation\&.createAnimation (\fBPosition\fPpos, \fBFormExt\fPform, booleanshowInAnimation)"
create animation with full parameterization 
.PP
\fBParameters:\fP
.RS 4
\fIid\fP internal objectId for animation\&. Must be unique\&. 
.br
\fIpos\fP middle point of animation object 
.br
\fIform\fP form of animation object 
.br
\fIshowInAnimation\fP switch animation on or off 
.RE
.PP

.SS "String desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.advancedModellingFeatures\&.WaitQueueAnimation\&.getInternId ()"
gives the internal Id of this animation object\&. 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SS "boolean desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.advancedModellingFeatures\&.WaitQueueAnimation\&.waitOnCoop ()"
This method is called from a SimProcessAnimation which wants to cooperate as a slave\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
