.TH "desmoj.core.dist.DiscreteDist< N extends Number >" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.core.dist.DiscreteDist< N extends Number > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits NumericalDist< N >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDiscreteDist\fP (\fBModel\fP owner, String name, boolean showInReport, boolean showInTrace)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Superclass for all distributions returning discrete samples of arbitrary numerical type\&.
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Tim Lechler, Johannes Goebel 
.PP
.nf
    Licensed under the Apache License, Version 2.0 (the "License"); you
    may not use this file except in compliance with the License. You may
    obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
    implied. See the License for the specific language governing
    permissions and limitations under the License.
.fi
.PP
 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.core\&.dist\&.DiscreteDist< N extends Number >\&.DiscreteDist (\fBModel\fPowner, Stringname, booleanshowInReport, booleanshowInTrace)"
Constructs a distribution returning discretely distributed samples of a custom type\&. Note that the method \fCN sample()\fP returning the samples (inherited from \fCNumericalDist<N>\fP) has to be implemented in subclasses\&.
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP Model : The distribution's owner 
.br
\fIname\fP java\&.lang\&.String : The distribution's name 
.br
\fIshowInReport\fP boolean : Flag to show distribution in report 
.br
\fIshowInTrace\fP boolean : Flag to show distribution in trace 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
