.TH "desmoj.extensions.visualEvents.VisualEvent" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualEvents.VisualEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits EventObject\&.
.PP
Inherited by \fBdesmoj\&.extensions\&.visualEvents\&.AttachEvent\fP, \fBdesmoj\&.extensions\&.visualEvents\&.CreateVisibleObjectEvent\fP, \fBdesmoj\&.extensions\&.visualEvents\&.DetachEvent\fP, \fBdesmoj\&.extensions\&.visualEvents\&.MoveEvent\fP, \fBdesmoj\&.extensions\&.visualEvents\&.MovementInterruptEvent\fP, \fBdesmoj\&.extensions\&.visualEvents\&.RemoveEvent\fP, \fBdesmoj\&.extensions\&.visualEvents\&.RotateEvent\fP, \fBdesmoj\&.extensions\&.visualEvents\&.RotationInterruptEvent\fP, \fBdesmoj\&.extensions\&.visualEvents\&.SetOrientationEvent\fP, \fBdesmoj\&.extensions\&.visualEvents\&.SetPositionEvent\fP, and \fBdesmoj\&.extensions\&.visualEvents\&.SetVisibleEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVisualEvent\fP (Object source, String affectedSpatialObjectName, \fBTimeInstant\fP occurredTime)"
.br
.ti -1c
.RI "\fBTimeInstant\fP \fBgetOccurredTime\fP ()"
.br
.ti -1c
.RI "String \fBgetTargetName\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is the basic class for all the events which indicate the changing of the spatial attributes\&. 
.PP
\fBAuthor:\fP
.RS 4
Fred Sun 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.visualEvents\&.VisualEvent\&.VisualEvent (Objectsource, StringaffectedSpatialObjectName, \fBTimeInstant\fPoccurredTime)"
Constructs a \fBVisualEvent\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsource\fP The object on which the event initially occurred\&. 
.br
\fIaffectedSpatialObjectName\fP The name of the SpatialObject which is affected by this \fBVisualEvent\fP\&. 
.br
\fIoccuredTime\fP The time when this event occurred\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBTimeInstant\fP desmoj\&.extensions\&.visualEvents\&.VisualEvent\&.getOccurredTime ()"
Gets the SimTime when this event occurred\&. 
.PP
\fBReturns:\fP
.RS 4
The event occurred time in TimeInstant\&. 
.RE
.PP

.SS "String desmoj\&.extensions\&.visualEvents\&.VisualEvent\&.getTargetName ()"
Gets the ID of the object which is affected by this event\&. 
.PP
\fBReturns:\fP
.RS 4
the name of the performer\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
