.TH "desmoj.extensions.visualization2d.animation.core.advancedModellingFeatures.ProcessCoopAnimation" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization2d.animation.core.advancedModellingFeatures.ProcessCoopAnimation \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ProcessCoop\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProcessCoopAnimation\fP (\fBModelAnimation\fP owner, String name, boolean showInTrace)"
.br
.ti -1c
.RI "void \fBcreateAnimation\fP (\fBWaitQueueAnimation\fP waitQueueAnimation)"
.br
.ti -1c
.RI "void \fBcooperation\fP (\fBSimProcess\fP master, \fBSimProcess\fP slave)"
.br
.ti -1c
.RI "abstract void \fBcooperationAnimation\fP (\fBSimProcess\fP master, \fBSimProcess\fP slave)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is used in method cooperation in class WaitQueueanimation
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
christian.mueller@th-wildau.de For information about subproject: desmoj\&.extensions\&.visualization2d please have a look at: http://www.th-wildau.de/cmueller/Desmo-J/Visualization2d/
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.advancedModellingFeatures\&.ProcessCoopAnimation\&.ProcessCoopAnimation (\fBModelAnimation\fPowner, Stringname, booleanshowInTrace)"
Constructor with same parameters as in ProcessCoop 
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP 
.br
\fIname\fP 
.br
\fIshowInTrace\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.advancedModellingFeatures\&.ProcessCoopAnimation\&.cooperation (\fBSimProcess\fPmaster, \fBSimProcess\fPslave)"
Implemention of cooperation method of ProcessCoop\&. It calls: beginCooperation, cooperationAnimation, endCooperation 
.SS "abstract void desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.advancedModellingFeatures\&.ProcessCoopAnimation\&.cooperationAnimation (\fBSimProcess\fPmaster, \fBSimProcess\fPslave)\fC [pure virtual]\fP"
This method must be implement and describe the cooperation\&. The master is active and slave is passive\&. 
.PP
\fBParameters:\fP
.RS 4
\fImaster\fP 
.br
\fIslave\fP 
.RE
.PP

.SS "void desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.advancedModellingFeatures\&.ProcessCoopAnimation\&.createAnimation (\fBWaitQueueAnimation\fPwaitQueueAnimation)"
This animation is part of animation of WaitQueue 
.PP
\fBParameters:\fP
.RS 4
\fIwaitQueueAnimation\fP used WaitQueue 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
