.TH "desmoj.extensions.experimentation.util.XSLFilter" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.experimentation.util.XSLFilter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits FileFilter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBaccept\fP (File file)"
.br
.ti -1c
.RI "String \fBgetDescription\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "boolean desmoj\&.extensions\&.experimentation\&.util\&.XSLFilter\&.accept (Filefile)"
Accepts all directories and xsl files\&.
.PP
\fBParameters:\fP
.RS 4
\fIfile\fP file: file to be filtered 
.RE
.PP

.SS "String desmoj\&.extensions\&.experimentation\&.util\&.XSLFilter\&.getDescription ()"

.PP
\fBReturns:\fP
.RS 4
The description of this filter 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
