.TH "desmoj.core.report.TallyTimeSpanReporter" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.core.report.TallyTimeSpanReporter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.core\&.report\&.TallyReporter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTallyTimeSpanReporter\fP (\fBReportable\fP informationSource)"
.br
.ti -1c
.RI "String[] \fBgetEntries\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "String [] desmoj\&.core\&.report\&.TallyTimeSpanReporter\&.getEntries ()\fC [virtual]\fP"
Returns an array of Strings each containing the data for the corresponding column in array \fCcolumns[]\fP\&. Implement this method in a way, that an array of the same length as the column titles is produced containing the data at the point of time this method is called by someone else to produce up-to-date information\&.
.PP
\fBReturns:\fP
.RS 4
java\&.lang\&.String[] : Array containing the data for reporting 
.RE
.PP

.PP
Reimplemented from \fBdesmoj\&.core\&.report\&.TallyReporter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
