.TH "desmoj.extensions.visualization2d.engine.viewer.HelpDialogTemplate" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization2d.engine.viewer.HelpDialogTemplate \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ActionListener\&.
.PP
Inherited by \fBdesmoj\&.extensions\&.visualization2d\&.engine\&.viewer\&.AboutEngineDialog\fP, \fBdesmoj\&.extensions\&.visualization2d\&.engine\&.viewer\&.AboutModelDialog\fP, and \fBdesmoj\&.extensions\&.visualization2d\&.engine\&.viewer\&.HelpDialog\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHelpDialogTemplate\fP (\fBViewerPanel\fP viewer)"
.br
.ti -1c
.RI "void \fBactionPerformed\fP (ActionEvent e)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "abstract void \fBbuildDialog\fP ()  throws MalformedURLException"
.br
.ti -1c
.RI "\fBViewerPanel\fP \fBgetViewer\fP ()"
.br
.ti -1c
.RI "AppletContext \fBgetAppletContext\fP ()"
.br
.ti -1c
.RI "\fBLanguageSupport\fP \fBgetLanguage\fP ()"
.br
.ti -1c
.RI "URL \fBgetInternURL\fP (String key)"
.br
.ti -1c
.RI "URL \fBgetExternURL\fP (String key)"
.br
.ti -1c
.RI "String \fBreadContent\fP (URL url, int width)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Superclass of all HelpDialogs
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
christian.mueller@th-wildau.de For information about subproject: desmoj\&.extensions\&.visualization2d please have a look at: http://www.th-wildau.de/cmueller/Desmo-J/Visualization2d/
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
