.TH "desmoj.core.report.SeriesReporter" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.core.report.SeriesReporter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.core\&.report\&.DistributionReporter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSeriesReporter\fP (\fBReportable\fP informationSource)"
.br
.ti -1c
.RI "java\&.lang\&.String[] \fBgetEntries\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "java\&.lang\&.String [] desmoj\&.core\&.report\&.SeriesReporter\&.getEntries ()\fC [virtual]\fP"
Returns the array of strings containing all information about the series\&.
.PP
\fBReturns:\fP
.RS 4
java\&.lang\&.String[] : The array of Strings containing all information about the series 
.RE
.PP

.PP
Reimplemented from \fBdesmoj\&.core\&.report\&.DistributionReporter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
