.TH "desmoj.core.report.HTMLDebugOutput" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.core.report.HTMLDebugOutput \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.core\&.report\&.DebugFileOut\fP, and \fBdesmoj\&.core\&.report\&.OutputType\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHTMLDebugOutput\fP ()"
.br
.ti -1c
.RI "\fBHTMLDebugOutput\fP (int simTimeFloatingDigits)"
.br
.ti -1c
.RI "void \fBsetTimeFloats\fP (int timeFloats)"
.br
.ti -1c
.RI "String \fBgetAppendix\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Use this class to create HTML formatted Simulation Debug Output\&.
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Gunnar Kiesel
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.core\&.report\&.HTMLDebugOutput\&.HTMLDebugOutput ()"
Create a new \fBHTMLDebugOutput\fP class * 
.SH "Member Function Documentation"
.PP 
.SS "String desmoj\&.core\&.report\&.HTMLDebugOutput\&.getAppendix ()"
returns the file appendix for this output type * 
.PP
Implements \fBdesmoj\&.core\&.report\&.OutputType\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
