.TH "desmoj.extensions.experimentation.ui.IGraphicalObserver" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.experimentation.ui.IGraphicalObserver \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBdesmoj\&.extensions\&.experimentation\&.ui\&.GraphicalObserver\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract \fBGraphicalObserverContext\fP \fBgetContext\fP ()"
.br
.ti -1c
.RI "abstract Component \fBgetGUI\fP ()"
.br
.ti -1c
.RI "abstract void \fBregister\fP ()"
.br
.ti -1c
.RI "abstract void \fBderegister\fP ()"
.br
.ti -1c
.RI "abstract void \fBsetVisible\fP (boolean visible)"
.br
.ti -1c
.RI "abstract void \fBsetSize\fP (int width, int height)"
.br
.ti -1c
.RI "abstract void \fBsetLocation\fP (int x, int y)"
.br
.ti -1c
.RI "abstract String \fBgetName\fP ()"
.br
.ti -1c
.RI "abstract void \fBupdate\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "abstract void desmoj\&.extensions\&.experimentation\&.ui\&.IGraphicalObserver\&.deregister ()\fC [pure virtual]\fP"
Deregisters the observer from the context 
.PP
Implemented in \fBdesmoj\&.extensions\&.experimentation\&.ui\&.GraphicalObserver\fP\&.
.SS "abstract \fBGraphicalObserverContext\fP desmoj\&.extensions\&.experimentation\&.ui\&.IGraphicalObserver\&.getContext ()\fC [pure virtual]\fP"
Returns the context this observer is displayed in
.PP
\fBReturns:\fP
.RS 4
The context (e\&.g\&. a JDesktop component)\&. 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.extensions\&.experimentation\&.ui\&.GraphicalObserver\fP\&.
.SS "abstract Component desmoj\&.extensions\&.experimentation\&.ui\&.IGraphicalObserver\&.getGUI ()\fC [pure virtual]\fP"
Should return the graphical observer's main GUI component
.PP
\fBReturns:\fP
.RS 4
an AWT or Swing component\&. 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.extensions\&.experimentation\&.ui\&.TimeSeriesPlotter\fP, \fBdesmoj\&.extensions\&.experimentation\&.ui\&.HistogramPlotter\fP, and \fBdesmoj\&.extensions\&.experimentation\&.ui\&.GraphicalObserver\fP\&.
.SS "abstract String desmoj\&.extensions\&.experimentation\&.ui\&.IGraphicalObserver\&.getName ()\fC [pure virtual]\fP"
Returns the observer's name
.PP
\fBReturns:\fP
.RS 4
name 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.extensions\&.experimentation\&.ui\&.GraphicalObserver\fP\&.
.SS "abstract void desmoj\&.extensions\&.experimentation\&.ui\&.IGraphicalObserver\&.register ()\fC [pure virtual]\fP"
Registers the observer with the context 
.PP
Implemented in \fBdesmoj\&.extensions\&.experimentation\&.ui\&.GraphicalObserver\fP\&.
.SS "abstract void desmoj\&.extensions\&.experimentation\&.ui\&.IGraphicalObserver\&.setLocation (intx, inty)\fC [pure virtual]\fP"
Sets the position of the observer's main window's upper left edge\&.
.PP
\fBParameters:\fP
.RS 4
\fIx\fP horizontal position 
.br
\fIy\fP vertical position 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.extensions\&.experimentation\&.ui\&.GraphicalObserver\fP\&.
.SS "abstract void desmoj\&.extensions\&.experimentation\&.ui\&.IGraphicalObserver\&.setSize (intwidth, intheight)\fC [pure virtual]\fP"
Sets the observer's main window's size\&.
.PP
\fBParameters:\fP
.RS 4
\fIwidth\fP window width 
.br
\fIheight\fP window height 
.RE
.PP

.PP
Implemented in \fBdesmoj\&.extensions\&.experimentation\&.ui\&.GraphicalObserver\fP\&.
.SS "abstract void desmoj\&.extensions\&.experimentation\&.ui\&.IGraphicalObserver\&.setVisible (booleanvisible)\fC [pure virtual]\fP"
Sets the observer visible withing the context 
.PP
Implemented in \fBdesmoj\&.extensions\&.experimentation\&.ui\&.GraphicalObserver\fP\&.
.SS "abstract void desmoj\&.extensions\&.experimentation\&.ui\&.IGraphicalObserver\&.update ()\fC [pure virtual]\fP"
Requests an update of the observer's display from the context\&. 
.PP
Implemented in \fBdesmoj\&.extensions\&.experimentation\&.ui\&.GraphicalObserver\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
