.TH "desmoj.extensions.applicationDomains.harbour.Job" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.applicationDomains.harbour.Job \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.core\&.simulator\&.Entity\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJob\fP (\fBModel\fP owner, String name, int type, \fBModelComponent\fP origin, \fBModelComponent\fP destination, boolean showInTrace)"
.br
.ti -1c
.RI "void \fBsetOrigin\fP (\fBModelComponent\fP o)"
.br
.ti -1c
.RI "\fBModelComponent\fP \fBgetOrigin\fP ()"
.br
.ti -1c
.RI "void \fBsetDestination\fP (\fBModelComponent\fP d)"
.br
.ti -1c
.RI "\fBModelComponent\fP \fBgetDestination\fP ()"
.br
.ti -1c
.RI "void \fBsetType\fP (int t)"
.br
.ti -1c
.RI "int \fBgetType\fP ()"
.br
.ti -1c
.RI "boolean \fBisSelected\fP ()"
.br
.ti -1c
.RI "void \fBsetSelected\fP (boolean b)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A \fBJob\fP represents any kind of job that the \fC\fBInternalTransporter\fP\fP has to do in a container terminal\&. It has a certain origin (the place the internal transporter has to drive to to get/leave the containers(goods) and destination (the place the internal transporter has to drive to to leave/get the containers(goods)\&. It has also a certain typ: import or export\&. \fBJob\fP is derived from Entity\&.
.PP
\fBSee Also:\fP
.RS 4
Entity
.RE
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Eugenia Neufeld
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.applicationDomains\&.harbour\&.Job\&.Job (\fBModel\fPowner, Stringname, inttype, \fBModelComponent\fPorigin, \fBModelComponent\fPdestination, booleanshowInTrace)"
Constructs a \fBJob\fP that must been done by an internal transporter\&. A \fBJob\fP has a certain typ\&. This typ must be 1 (import) or 0 (export), if the job is an import or export job\&. A \fBJob\fP has also certain origin and destination\&.
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP desmoj\&.Model : The model this \fBJob\fP is associated to\&. 
.br
\fIname\fP java\&.lang\&.String : The name of this \fBJob\fP\&. 
.br
\fItyp\fP int : The typ of this \fBJob\fP: 1 or 0\&. 
.br
\fIorigin\fP \fCModelComponent\fP: The origin of this \fBJob\fP 
.br
\fIdestination\fP \fCModelComponent\fP: The destination of this \fBJob\fP 
.br
\fIshowInTrace\fP boolean : Flag, if this \fBJob\fP should produce a trace output or not\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBModelComponent\fP desmoj\&.extensions\&.applicationDomains\&.harbour\&.Job\&.getDestination ()"
Returns the destination of this job\&.
.PP
\fBReturns:\fP
.RS 4
\fCModelComponent\fP: The destination of this job\&. 
.RE
.PP

.SS "\fBModelComponent\fP desmoj\&.extensions\&.applicationDomains\&.harbour\&.Job\&.getOrigin ()"
Returns the origin of this job\&.
.PP
\fBReturns:\fP
.RS 4
\fCModelComponent\fP: The origin of this job\&. 
.RE
.PP

.SS "int desmoj\&.extensions\&.applicationDomains\&.harbour\&.Job\&.getType ()"
Returns the type of this job: 1 or 0\&.
.PP
\fBReturns:\fP
.RS 4
int : The type of this job\&. 
.RE
.PP

.SS "boolean desmoj\&.extensions\&.applicationDomains\&.harbour\&.Job\&.isSelected ()"
Returns true if job has been already selected for an internal transporter anf false otherwise\&.
.PP
\fBReturns:\fP
.RS 4
boolean : The boolean value if the job' been already selected\&. 
.RE
.PP

.SS "void desmoj\&.extensions\&.applicationDomains\&.harbour\&.Job\&.setDestination (\fBModelComponent\fPd)"
Sets the destination of this job\&.
.PP
\fBParameters:\fP
.RS 4
\fId\fP \fCModelComponent\fP: The new destination of this \fBJob\fP\&. 
.RE
.PP

.SS "void desmoj\&.extensions\&.applicationDomains\&.harbour\&.Job\&.setOrigin (\fBModelComponent\fPo)"
Sets the origin of this job\&.
.PP
\fBParameters:\fP
.RS 4
\fIo\fP \fCModelComponent\fP: The new origin of this \fBJob\fP\&. 
.RE
.PP

.SS "void desmoj\&.extensions\&.applicationDomains\&.harbour\&.Job\&.setSelected (booleanb)"
Sets the boolean value if the job' been already selected\&.
.PP
\fBParameters:\fP
.RS 4
\fIb\fP boolean : The new flag if the job' been already selected\&. 
.RE
.PP

.SS "void desmoj\&.extensions\&.applicationDomains\&.harbour\&.Job\&.setType (intt)"
Sets the type of this job\&.
.PP
\fBParameters:\fP
.RS 4
\fIi\fP int : The new type of this \fBJob\fP\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
