.TH "desmoj.extensions.visualEvents.SetOrientationEvent" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualEvents.SetOrientationEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.extensions\&.visualEvents\&.VisualEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSetOrientationEvent\fP (Object source, String affectedSpatialObjectName, Quat4d orientation, \fBTimeInstant\fP occurredTime)"
.br
.ti -1c
.RI "Quat4d \fBgetOrientation\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is an event which signals the reset of the rotation by an object\&. 
.PP
\fBAuthor:\fP
.RS 4
Fred Sun 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.visualEvents\&.SetOrientationEvent\&.SetOrientationEvent (Objectsource, StringaffectedSpatialObjectName, Quat4dorientation, \fBTimeInstant\fPoccurredTime)"
Constructs a \fBSetOrientationEvent\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsource\fP The object on which the event initially occurred\&. 
.br
\fIaffectedSpatialObjectName\fP The name of the object who's orientation should be set\&. 
.br
\fIorientation\fP The orientation should be set\&. 
.br
\fIoccurredTime\fP The TimeInstant when the event occurred\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "Quat4d desmoj\&.extensions\&.visualEvents\&.SetOrientationEvent\&.getOrientation ()"
Gets the orientation to be set by this event\&. 
.PP
\fBReturns:\fP
.RS 4
The orientation to be set\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
