.TH "desmoj.extensions.visualEvents.RemoveEvent" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualEvents.RemoveEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.extensions\&.visualEvents\&.VisualEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRemoveEvent\fP (Object source, String affectedSpatialObjectName, \fBTimeInstant\fP occurredTime)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A \fBRemoveEvent\fP indicates that a SpatialObject isn't needed anymore\&.
.PP
\fBAuthor:\fP
.RS 4
Fred Sun 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.visualEvents\&.RemoveEvent\&.RemoveEvent (Objectsource, StringaffectedSpatialObjectName, \fBTimeInstant\fPoccurredTime)"
Constructs a \fBRemoveEvent\fP\&.
.PP
\fBParameters:\fP
.RS 4
\fIsource\fP The object on which the event initially occurred\&. 
.br
\fIaffectedSpatialObjectName\fP The name of the object which should be removed\&. 
.br
\fIoccurredTime\fP The TimeInstant when the event occurred\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
