.TH "desmoj.extensions.visualization2d.animation.core.advancedModellingFeatures.StockAnimation" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization2d.animation.core.advancedModellingFeatures.StockAnimation \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.core\&.advancedModellingFeatures\&.Stock\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStockAnimation\fP (\fBModelAnimation\fP owner, String name, int producerSortOrder, int producerQCapacity, int consumerSortOrder, int consumerQCapacity, long initialUnits, long capacity, boolean showInReport, boolean showInTrace)"
.br
.ti -1c
.RI "\fBStockAnimation\fP (\fBModelAnimation\fP owner, String name, long initialUnits, long capacity, boolean showInReport, boolean showInTrace)"
.br
.ti -1c
.RI "void \fBcreateAnimation\fP (\fBPosition\fP pos, \fBFormExt\fP form, boolean showInAnimation)"
.br
.ti -1c
.RI "boolean \fBretrieve\fP (long noOfProducts)"
.br
.ti -1c
.RI "boolean \fBstore\fP (long noOfProducts)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Animation of a Stock
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
christian.mueller@th-wildau.de For information about subproject: desmoj\&.extensions\&.visualization2d please have a look at: http://www.th-wildau.de/cmueller/Desmo-J/Visualization2d/
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.advancedModellingFeatures\&.StockAnimation\&.StockAnimation (\fBModelAnimation\fPowner, Stringname, intproducerSortOrder, intproducerQCapacity, intconsumerSortOrder, intconsumerQCapacity, longinitialUnits, longcapacity, booleanshowInReport, booleanshowInTrace)"
Constructor with the same parameters as in Stock 
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP used model 
.br
\fIname\fP as in Stock 
.br
\fIproducerSortOrder\fP as in Stock 
.br
\fIproducerQCapacity\fP as in Stock 
.br
\fIconsumerSortOrder\fP as in Stock 
.br
\fIconsumerQCapacity\fP as in Stock 
.br
\fIinitialUnits\fP as in Stock 
.br
\fIcapacity\fP as in Stock 
.br
\fIshowInReport\fP as in Stock 
.br
\fIshowInTrace\fP as in Stock 
.RE
.PP

.SS "desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.advancedModellingFeatures\&.StockAnimation\&.StockAnimation (\fBModelAnimation\fPowner, Stringname, longinitialUnits, longcapacity, booleanshowInReport, booleanshowInTrace)"
Constructor with the same parameters as in Stock 
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP used model 
.br
\fIname\fP as in Stock 
.br
\fIinitialUnits\fP as in Stock 
.br
\fIcapacity\fP as in Stock 
.br
\fIshowInReport\fP as in Stock 
.br
\fIshowInTrace\fP as in Stock 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.advancedModellingFeatures\&.StockAnimation\&.createAnimation (\fBPosition\fPpos, \fBFormExt\fPform, booleanshowInAnimation)"
create animation with full parameterization 
.PP
\fBParameters:\fP
.RS 4
\fIpos\fP middle point of animation object 
.br
\fIform\fP form of animation object 
.br
\fIshowInAnimation\fP switch animation on or off 
.RE
.PP

.SS "boolean desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.advancedModellingFeatures\&.StockAnimation\&.retrieve (longnoOfProducts)"
A Consumer wants to retrieve noOfProducts When the stock is full, he must wait in a queue of consumer 
.PP
\fBParameters:\fP
.RS 4
\fInoOfProducts\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
true: Consumer got the products false: Consumer is rejected, because the waiting queue of consumer is full 
.RE
.PP

.SS "boolean desmoj\&.extensions\&.visualization2d\&.animation\&.core\&.advancedModellingFeatures\&.StockAnimation\&.store (longnoOfProducts)"
A Producer wants to store noOfProducts\&. When the stock is full, he must wait in a queue of producer 
.PP
\fBParameters:\fP
.RS 4
\fInoOfProducts\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
true: Producer can store the products false: Producer is rejected, because the waiting queue of producer is full 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
