.TH "desmoj.extensions.visualization2d.engine.modelGrafic.RouteGrafic" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization2d.engine.modelGrafic.RouteGrafic \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Object, and \fBdesmoj\&.extensions\&.visualization2d\&.engine\&.modelGrafic\&.Grafic\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRouteDynamicGrafic\fP"
.br
.ti -1c
.RI "class \fBRouteStaticGrafic\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRouteGrafic\fP (\fBRoute\fP route, Point[] pointsExtern, long time)"
.br
.ti -1c
.RI "String \fBgetViewId\fP ()"
.br
.ti -1c
.RI "void \fBtransform\fP (long time)"
.br
.ti -1c
.RI "Rectangle \fBgetBoundsExtern\fP ()"
.br
.ti -1c
.RI "RouteStaticGrafic \fBgetRouteStaticGrafic\fP ()"
.br
.ti -1c
.RI "RouteDynamicGrafic \fBgetRouteDynamicGrafic\fP ()"
.br
.ti -1c
.RI "void \fBupdate\fP (long time)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static String[] \fBgetViews\fP (\fBModel\fP model)"
.br
.ti -1c
.RI "static Rectangle \fBgetBoundsExternGlobal\fP (\fBModel\fP model, String viewId)"
.br
.ti -1c
.RI "static void \fBupdateInit\fP (\fBModel\fP model, String viewId, long time)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBGrafic\fP of a route\&. That contains static and dynamic components
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
christian.mueller@th-wildau.de For information about subproject: desmoj\&.extensions\&.visualization2d please have a look at: http://www.th-wildau.de/cmueller/Desmo-J/Visualization2d/
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.visualization2d\&.engine\&.modelGrafic\&.RouteGrafic\&.RouteGrafic (\fBRoute\fProute, Point[]pointsExtern, longtime)"
called by Route 
.PP
\fBParameters:\fP
.RS 4
\fIroute\fP 
.br
\fIpointsExtern\fP 
.br
\fItime\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static Rectangle desmoj\&.extensions\&.visualization2d\&.engine\&.modelGrafic\&.RouteGrafic\&.getBoundsExternGlobal (\fBModel\fPmodel, StringviewId)\fC [static]\fP"
Construct the smallest rectangle, which include the positions of all routes in view 
.PP
\fBParameters:\fP
.RS 4
\fImodel\fP 
.br
\fIviewId\fP id of view 
.RE
.PP
\fBReturns:\fP
.RS 4
smallest rectangle when an routeGrafic exist, null otherwise 
.RE
.PP

.SS "static String [] desmoj\&.extensions\&.visualization2d\&.engine\&.modelGrafic\&.RouteGrafic\&.getViews (\fBModel\fPmodel)\fC [static]\fP"
get all views (viewId's) with Route 
.PP
\fBParameters:\fP
.RS 4
\fImodel\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "void desmoj\&.extensions\&.visualization2d\&.engine\&.modelGrafic\&.RouteGrafic\&.transform (longtime)"
determine internal points for painting route 
.PP
\fBParameters:\fP
.RS 4
\fItime\fP actual simulationTime 
.RE
.PP

.SS "void desmoj\&.extensions\&.visualization2d\&.engine\&.modelGrafic\&.RouteGrafic\&.update (longtime)"
update entities on route 
.PP
\fBParameters:\fP
.RS 4
\fItime\fP actual simulation time 
.RE
.PP

.SS "static void desmoj\&.extensions\&.visualization2d\&.engine\&.modelGrafic\&.RouteGrafic\&.updateInit (\fBModel\fPmodel, StringviewId, longtime)\fC [static]\fP"
called by \fBViewGrafic\fP by view or zoom change 
.PP
\fBParameters:\fP
.RS 4
\fImodel\fP 
.br
\fIviewId\fP 
.br
\fItime\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
