.TH "desmoj.extensions.visualization3d.StaticObject" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization3d.StaticObject \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
This class contains all elements needed in a scene graph to describe a static object (i\&.e\&. a not movable SpatialObject) in a scene\&.
.PP
A \fBStaticObject\fP consists of a 3D-model which is contained in a BranchGroup, a TransformGroup who's responsible for the transformation of the object and a BranchGroup which is the detaching point for this object\&.
.PP
\fBAuthor:\fP
.RS 4
Fred Sun 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
