.TH "desmoj.extensions.visualization3d.RotationSwitchInterpolator" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization3d.RotationSwitchInterpolator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits RotationInterpolator\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRotationSwitchInterpolator\fP (TransformGroup target)"
.br
.ti -1c
.RI "void \fBcomputeTransform\fP (float alphaValue, Transform3D transform)"
.br
.ti -1c
.RI "void \fBprocessStimulus\fP (Enumeration criteria)"
.br
.ti -1c
.RI "void \fBstop\fP ()"
.br
.ti -1c
.RI "void \fBstart\fP (\fBVisualizationClockAlpha\fP alpha, float maximumAngle, Transform3D transformAxis, Transform3D currentTransform)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A slightly modified version of RotationInterpolator\&. It doesn't need much rotational data at the initiation\&. The alpha, rotation axis and the angles just need to be specified at the start\&. If the rotation is finished, the calculation will be stopped and the alpha removed\&.
.PP
\fBAuthor:\fP
.RS 4
Fred Sun 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.visualization3d\&.RotationSwitchInterpolator\&.RotationSwitchInterpolator (TransformGrouptarget)"
Constructs a \fBRotationSwitchInterpolator\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fItarget\fP The transformGroup node affected by this transformInterpolator 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void desmoj\&.extensions\&.visualization3d\&.RotationSwitchInterpolator\&.start (\fBVisualizationClockAlpha\fPalpha, floatmaximumAngle, Transform3DtransformAxis, Transform3DcurrentTransform)"
Sets the rotation data and start the interpolator\&.
.PP
\fBParameters:\fP
.RS 4
\fIalpha\fP The alpha which gives the duration 
.br
\fImaximumAngle\fP the ending angle in radians 
.br
\fItransformAxis\fP the transform that defines the local coordinate system in which this interpolator operates\&. The rotation is done about the Y-axis of this local coordinate system\&. 
.br
\fIcurrentTransform\fP the transform that contains the current orientation data of the object\&. 
.RE
.PP

.SS "void desmoj\&.extensions\&.visualization3d\&.RotationSwitchInterpolator\&.stop ()"
Stops the animation 

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
