.TH "desmoj.extensions.experimentation.ui.TimeSeriesPlotter" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.experimentation.ui.TimeSeriesPlotter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.extensions\&.experimentation\&.ui\&.GraphicalObserver\fP, \fBdesmoj\&.core\&.util\&.ExperimentListener\fP, \fBdesmoj\&.extensions\&.experimentation\&.ui\&.ChartOwner\fP, and Observer\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSimpleTimeSeriesViewer\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTimeSeriesPlotter\fP (String title, \fBGraphicalObserverContext\fP context, \fBTimeSeries\fP data[], int winWidth, int winHeight)"
.br
.ti -1c
.RI "\fBTimeSeriesPlotter\fP (String title, \fBGraphicalObserverContext\fP context, \fBTimeSeries\fP data, int winWidth, int winHeight)"
.br
.ti -1c
.RI "\fBTimeSeriesPlotter\fP (String title, \fBGraphicalObserverContext\fP context, \fBTimeSeries\fP data, int winWidth, int winHeight, String legend)"
.br
.ti -1c
.RI "\fBTimeSeriesPlotter\fP (String title, \fBGraphicalObserverContext\fP context, \fBTimeSeries\fP data, int winWidth, int winHeight, int xLocation, int yLocation)"
.br
.ti -1c
.RI "\fBTimeSeriesPlotter\fP (String title, \fBGraphicalObserverContext\fP context, \fBTimeSeries\fP data[], int winWidth, int winHeight, int xLocation, int yLocation)"
.br
.ti -1c
.RI "void \fBaddTimeSeries\fP (\fBTimeSeries\fP newData)"
.br
.ti -1c
.RI "void \fBaddTimeSeries\fP (\fBTimeSeries\fP newData, String legend)"
.br
.ti -1c
.RI "Component \fBgetGUI\fP ()"
.br
.ti -1c
.RI "void \fBexperimentRunning\fP (\fBSimRunEvent\fP e)"
.br
.ti -1c
.RI "void \fBexperimentStopped\fP (\fBSimRunEvent\fP e)"
.br
.ti -1c
.RI "void \fBexperimentPaused\fP (\fBSimRunEvent\fP e)"
.br
.ti -1c
.RI "void \fBdrawChart\fP (Graphics g)"
.br
.ti -1c
.RI "void \fBupdate\fP (Observable x, Object y)"
.br
.ti -1c
.RI "void \fBupdatePlotter\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple time series plotter that can be displayed in the experiment launcher\&.
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Nicolas Knaak 
.PP
Philip Joschko
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.experimentation\&.ui\&.TimeSeriesPlotter\&.TimeSeriesPlotter (Stringtitle, \fBGraphicalObserverContext\fPcontext, \fBTimeSeries\fPdata[], intwinWidth, intwinHeight)"
Creates a new TimeSeries plotter from the given array of TimeSeries objects\&.
.PP
\fBParameters:\fP
.RS 4
\fItitle\fP window title 
.br
\fIcontext\fP the context to show this observer in 
.br
\fIdata\fP array of TimeSeries data to display 
.br
\fIwinWidth\fP width of window 
.br
\fIwinHeight\fP height of window 
.RE
.PP

.SS "desmoj\&.extensions\&.experimentation\&.ui\&.TimeSeriesPlotter\&.TimeSeriesPlotter (Stringtitle, \fBGraphicalObserverContext\fPcontext, \fBTimeSeries\fPdata, intwinWidth, intwinHeight)"
Creates a new TimeSeries plotter from the given TimeSeries object\&. This is the main constructor\&. The other constructors finally call this one\&.
.PP
\fBParameters:\fP
.RS 4
\fItitle\fP window title 
.br
\fIcontext\fP the context to show this observer in 
.br
\fIdata\fP TimeSeries to display 
.br
\fIwinWidth\fP width of window 
.br
\fIwinHeight\fP height of window 
.RE
.PP

.SS "desmoj\&.extensions\&.experimentation\&.ui\&.TimeSeriesPlotter\&.TimeSeriesPlotter (Stringtitle, \fBGraphicalObserverContext\fPcontext, \fBTimeSeries\fPdata, intwinWidth, intwinHeight, Stringlegend)"
Creates a new TimeSeries plotter from the given TimeSeries object\&. This is the main constructor\&. The other constructors finally call this one\&.
.PP
\fBParameters:\fP
.RS 4
\fItitle\fP window title 
.br
\fIcontext\fP the context to show this observer in 
.br
\fIdata\fP TimeSeries to display 
.br
\fIwinWidth\fP width of window 
.br
\fIwinHeight\fP height of window 
.br
\fIString\fP legend (only used if further plots are added to this plotter) 
.RE
.PP

.SS "desmoj\&.extensions\&.experimentation\&.ui\&.TimeSeriesPlotter\&.TimeSeriesPlotter (Stringtitle, \fBGraphicalObserverContext\fPcontext, \fBTimeSeries\fPdata, intwinWidth, intwinHeight, intxLocation, intyLocation)"
Creates a new TimeSeries plotter from the given TimeSeries object\&.
.PP
\fBParameters:\fP
.RS 4
\fItitle\fP window title 
.br
\fIcontext\fP the context to show this observer in 
.br
\fIdata\fP data of time series to display 
.br
\fIwinWidth\fP width of window 
.br
\fIwinHeight\fP height of window 
.br
\fIxLocation\fP horizontal position of window 
.br
\fIyLocation\fP vertical position of window 
.RE
.PP

.SS "desmoj\&.extensions\&.experimentation\&.ui\&.TimeSeriesPlotter\&.TimeSeriesPlotter (Stringtitle, \fBGraphicalObserverContext\fPcontext, \fBTimeSeries\fPdata[], intwinWidth, intwinHeight, intxLocation, intyLocation)"
Creates a new TimeSeries plotter from the given array of TimeSeries objects\&.
.PP
\fBParameters:\fP
.RS 4
\fItitle\fP window title 
.br
\fIcontext\fP the context to show this observer in 
.br
\fIdata\fP data of time series to display 
.br
\fIwinWidth\fP width of window 
.br
\fIwinHeight\fP height of window 
.br
\fIxLocation\fP horizontal position of window 
.br
\fIyLocation\fP vertical position of window 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void desmoj\&.extensions\&.experimentation\&.ui\&.TimeSeriesPlotter\&.addTimeSeries (\fBTimeSeries\fPnewData)"
Adds another TimeSeries statistic object which will be displayed in the chart, using a default legend entry\&. 
.PP
\fBParameters:\fP
.RS 4
\fInewData\fP Another TimeSeries statistic object which will be displayed in the chart\&. 
.RE
.PP

.SS "void desmoj\&.extensions\&.experimentation\&.ui\&.TimeSeriesPlotter\&.addTimeSeries (\fBTimeSeries\fPnewData, Stringlegend)"
Adds another TimeSeries statistic object which will be displayed in the chart\&. 
.PP
\fBParameters:\fP
.RS 4
\fInewData\fP Another TimeSeries statistic object which will be displayed in the chart\&. 
.br
\fIlegend\fP A short description\&. * 
.RE
.PP

.SS "void desmoj\&.extensions\&.experimentation\&.ui\&.TimeSeriesPlotter\&.drawChart (Graphicsg)"
Draws the values given by the TimeSeries statistic object into the chart\&. This method is automatically invoked by the chart object, if it has to repaint\&. 
.PP
Implements \fBdesmoj\&.extensions\&.experimentation\&.ui\&.ChartOwner\fP\&.
.SS "void desmoj\&.extensions\&.experimentation\&.ui\&.TimeSeriesPlotter\&.experimentPaused (\fBSimRunEvent\fPe)"
Called when the experiment is paused\&. Update of display
.PP
\fBParameters:\fP
.RS 4
\fIe\fP a SimRunEvent 
.RE
.PP

.PP
Implements \fBdesmoj\&.core\&.util\&.ExperimentListener\fP\&.
.SS "void desmoj\&.extensions\&.experimentation\&.ui\&.TimeSeriesPlotter\&.experimentRunning (\fBSimRunEvent\fPe)"
Called when the experiment is (re)started\&. Nothing happens
.PP
\fBParameters:\fP
.RS 4
\fIe\fP a SimRunEvent 
.RE
.PP

.PP
Implements \fBdesmoj\&.core\&.util\&.ExperimentListener\fP\&.
.SS "void desmoj\&.extensions\&.experimentation\&.ui\&.TimeSeriesPlotter\&.experimentStopped (\fBSimRunEvent\fPe)"
Called when the experiment is stopped\&. Update of display
.PP
\fBParameters:\fP
.RS 4
\fIe\fP a SimRunEvent 
.RE
.PP

.PP
Implements \fBdesmoj\&.core\&.util\&.ExperimentListener\fP\&.
.SS "Component desmoj\&.extensions\&.experimentation\&.ui\&.TimeSeriesPlotter\&.getGUI ()\fC [virtual]\fP"
Returns the plotter's GUI (a JFreeCHartPanel)
.PP
\fBReturns:\fP
.RS 4
a JFreeChart panel to plot the time series 
.RE
.PP

.PP
Implements \fBdesmoj\&.extensions\&.experimentation\&.ui\&.GraphicalObserver\fP\&.
.SS "void desmoj\&.extensions\&.experimentation\&.ui\&.TimeSeriesPlotter\&.update (Observablex, Objecty)"
The update method (required by interface 'Observer') will be called, if the TimeSeries produces new values\&. 
.SS "void desmoj\&.extensions\&.experimentation\&.ui\&.TimeSeriesPlotter\&.updatePlotter ()"
This method updates the chart\&. The chart will only be repainted if a new scaling is required\&. If no rescaling is required, then only the new values are painted\&. Of course this is much faster\&.
.PP
Because the \fBTimeSeriesPlotter\fP has no bench marks for scaling at the beginning, you have to call this method at least one time, when the upper and lower limits are known\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
