.TH "desmoj.core.simulator.ExternalEventTimedTrace" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.core.simulator.ExternalEventTimedTrace \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.core\&.simulator\&.ExternalEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExternalEventTimedTrace\fP (String trueTime, int refUnit, String what, \fBModel\fP owner)"
.br
.ti -1c
.RI "void \fBeventRoutine\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBExternalEventTimedTrace\fP class allows for inserting items with true time values into the trace file\&. When the event routine is called an appropriate trace note is sent\&. 
.PP
The \fC\fBExperiment\fP\fP class uses \fC\fBExternalEventTimedTrace\fP\fP events to write the start and stop time of the trace period as true time into the trace file\&.
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Ruth Meyer
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.core\&.simulator\&.ExternalEventTimedTrace\&.ExternalEventTimedTrace (StringtrueTime, intrefUnit, Stringwhat, \fBModel\fPowner)"
Constructs an \fBExternalEventTimedTrace\fP with the given true time, time unit, description and model\&.
.PP
\fBParameters:\fP
.RS 4
\fItrueTime\fP String : the true time value to be written into the trace file 
.br
\fIrefUnit\fP int : the time unit as a constant defined in the \fC\fBUnits\fP\fP interface 
.br
\fIwhat\fP String : a short description of the true time value 
.br
\fIowner\fP \fBModel\fP : the model this event shall belong to 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void desmoj\&.core\&.simulator\&.ExternalEventTimedTrace\&.eventRoutine ()\fC [virtual]\fP"
Sends a trace note with the description and the true time including the time unit\&. 
.PP
Implements \fBdesmoj\&.core\&.simulator\&.ExternalEvent\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
