.TH "desmoj.core.simulator.QueueListRandom< E extends Entity >" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.core.simulator.QueueListRandom< E extends Entity > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits QueueListStandard< E >, and PropertyChangeListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQueueListRandom\fP ()"
.br
.ti -1c
.RI "void \fBinsert\fP (E e)"
.br
.ti -1c
.RI "void \fBsetSeed\fP (long newSeed)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains the implementation with the java\&.util\&.LinkedList to represent queueing functionality\&. The entities are queued in random order\&. The statistic data of the queue will be stored in a \fC\fBQueueBased\fP\fP object\&. The \fCQueueListStandardFifo\fP has a reference to its \fC\fBQueueBased\fP\fP object\&. This class needs a reference to a subclass of \fBQueueBased\fP to update the queue statistics\&. It is used in many kinds of queue implementations i\&.e\&. in classes \fCQueue\fP and \fCProcessQueue\fP\&.
.PP
\fBSee Also:\fP
.RS 4
QueueList 
.PP
\fBQueueBased\fP 
.PP
Queue 
.PP
ProcessQueue
.RE
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Johannes Go\*(4bel 
.PP
based on ideas from Soenke Claassen, Tim Lechler, Justin Neumann
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.core\&.simulator\&.QueueListRandom< E extends \fBEntity\fP >\&.QueueListRandom ()"
Constructs an empty \fCQueueListStandardFifo\fP with no reference to its client \fBQueueBased\fP\&. This no-arg constructor is necessary to instantiate an object of this class by calling the \fCjava\&.lang\&.Class\&.newInstance()\fP method\&. The reference to the \fBQueueBased\fP object making use of this queue-functionality must be provided later by calling the setQueueBased() method\&. The initial length is always zero\&. 
.SH "Member Function Documentation"
.PP 
.SS "void desmoj\&.core\&.simulator\&.QueueListRandom< E extends \fBEntity\fP >\&.insert (Ee)"
Adds a new \fBEntity\fP to the QueueListStandardFifo\&. The position on which the entity is inserted is randomly generated, disregarding priorities\&.
.PP
\fBParameters:\fP
.RS 4
\fIe\fP \fBEntity\fP : The \fBEntity\fP to add to the QueueListStandardFifo 
.RE
.PP

.SS "void desmoj\&.core\&.simulator\&.QueueListRandom< E extends \fBEntity\fP >\&.setSeed (longnewSeed)"
Sets the seed of this queue list's pseudo random number generator\&.
.PP
\fBParameters:\fP
.RS 4
\fInewSeed\fP long : new seed this queue list's pseudo random number generator 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
