.TH "desmoj.extensions.visualization3d.VisualizationClock" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization3d.VisualizationClock \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVisualizationClock\fP ()"
.br
.ti -1c
.RI "long \fBgetTime\fP ()"
.br
.ti -1c
.RI "void \fBsetRate\fP (double rate)"
.br
.ti -1c
.RI "double \fBgetRate\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
A clock who provides the modified time value for the VisualModules controlled by the \fBVisualizationControl\fP\&.  The speed of the clock can be changed through a speed rate  The influence of the rate to the clock speed is: clock speed = system clock speed * speed rate
.PP
\fBAuthor:\fP
.RS 4
Fred Sun 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.visualization3d\&.VisualizationClock\&.VisualizationClock ()"
Constructs a new ViaualizationClock with speed rate of 1\&. 
.SH "Member Function Documentation"
.PP 
.SS "double desmoj\&.extensions\&.visualization3d\&.VisualizationClock\&.getRate ()"
Gets the current speed rate\&. 
.PP
\fBReturns:\fP
.RS 4
The current speed rate 
.RE
.PP

.SS "long desmoj\&.extensions\&.visualization3d\&.VisualizationClock\&.getTime ()"
Returns the time value\&. 
.PP
\fBReturns:\fP
.RS 4
The time value\&. 
.RE
.PP

.SS "void desmoj\&.extensions\&.visualization3d\&.VisualizationClock\&.setRate (doublerate)"
Sets the speed rate, which influence the clock speed with: clock speed = system clock speed * speed rate 
.PP
\fBParameters:\fP
.RS 4
\fIrate\fP The speed rate\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
