.TH "desmoj.core.simulator.ExternalEventTraceOn" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.core.simulator.ExternalEventTraceOn \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.core\&.simulator\&.ExternalEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExternalEventTraceOn\fP (\fBModel\fP owner, boolean showInTrace)"
.br
.ti -1c
.RI "void \fBeventRoutine\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
external event switching on the trace output for the experiment\&. The messagemanager's channel for tracenotes is switched on to forward tracenotes to the configured Output\&.
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Tim Lechler
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.core\&.simulator\&.ExternalEventTraceOn\&.ExternalEventTraceOn (\fBModel\fPowner, booleanshowInTrace)"
Creates the external event to start the trace output for an experiment\&.
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP desmoj\&.Model : The model this external event is associated to 
.br
\fIshowInTrace\fP boolean : The flag indicating if this external event is shown in the trace output 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void desmoj\&.core\&.simulator\&.ExternalEventTraceOn\&.eventRoutine ()\fC [virtual]\fP"
Switches the messagemanager's trace note channel on to forward tracenotes to the configured output\&. 
.PP
Implements \fBdesmoj\&.core\&.simulator\&.ExternalEvent\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
