.TH "desmoj.core.dist.IntDistEmpirical" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.core.dist.IntDistEmpirical \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits DiscreteDistEmpirical< Long >, and \fBdesmoj\&.core\&.dist\&.IntDist\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIntDistEmpirical\fP (\fBModel\fP owner, String name, boolean showInReport, boolean showInTrace)"
.br
.ti -1c
.RI "void \fBaddEntry\fP (int value, double frequency)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Empirically distributed stream of pseudo random numbers of type \fClong\fP\&. Values produced by this distribution follow an empirical distribution which is specified by entries consisting of the observed value and the frequency (probability) this value has been observed to occur\&. These entries are made by using the \fC\fBaddEntry()\fP\fP method\&. There are a few conditions a user has to meet before actually being allowed to take a sample of this distribution\&.
.PP
\fBSee Also:\fP
.RS 4
\fBdesmoj\&.core\&.dist\&.Distribution\fP
.RE
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Tim Lechler 
.RE
.PP
\fBDeprecated\fP
.RS 4
Replaced by DiscreteDistEmpirical
.RE
.PP
.PP
.nf
        Licensed under the Apache License, Version 2.0 (the "License");
        you may not use this file except in compliance with the License.
        You may obtain a copy of the License at
        http://www.apache.org/licenses/LICENSE-2.0

        Unless required by applicable law or agreed to in writing,
        software distributed under the License is distributed on an
        "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
        either express or implied. See the License for the specific
        language governing permissions and limitations under the License..fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.core\&.dist\&.IntDistEmpirical\&.IntDistEmpirical (\fBModel\fPowner, Stringname, booleanshowInReport, booleanshowInTrace)"
Constructs an empirical distribution producing integer values\&. Empirical distributions have to be initialized manually before use\&. This is done by calling the \fCaddEntry(long, double)\fP method to add values defining the behaviour of the desired distribution\&.s
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP Model : The distribution's owner 
.br
\fIname\fP java\&.lang\&.String : The distribution's name 
.br
\fIshowInReport\fP boolean : Flag for producing reports 
.br
\fIshowInTrace\fP boolean : Flag for producing trace output 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void desmoj\&.core\&.dist\&.IntDistEmpirical\&.addEntry (intvalue, doublefrequency)"
Adds a new entry of an empirical value and its associated frequency\&.
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP int : The empirical value observed 
.br
\fIfrequency\fP double : The corresponding frequency of the empirical value 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
