.TH "desmoj.extensions.visualization2d.engine.WriteBsp0" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization2d.engine.WriteBsp0 \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.extensions\&.visualization2d\&.engine\&.command\&.WriteCmds\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWriteBsp0\fP (URL iconUrl)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBbsp_init\fP (long initTime)"
.br
.ti -1c
.RI "void \fBbsp_run\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Test-Application for writer testing\&. Only for devoloper\&. It's may be not correct\&.
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
christian.mueller@th-wildau.de For information about subproject: desmoj\&.extensions\&.visualization2d please have a look at: http://www.th-wildau.de/cmueller/Desmo-J/Visualization2d/
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Member Function Documentation"
.PP 
.SS "void desmoj\&.extensions\&.visualization2d\&.engine\&.WriteBsp0\&.bsp_init (longinitTime)\fC [protected]\fP"
Erzeugen der Cmd's fuer die Init-Phase 
.SS "void desmoj\&.extensions\&.visualization2d\&.engine\&.WriteBsp0\&.bsp_run ()\fC [protected]\fP"
Erzeugen der Cmd's fuer die Run Phase 

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
