.TH "desmoj.core.dist.ContDistGamma" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.core.dist.ContDistGamma \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.core\&.dist\&.ContDist\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBContDistGamma\fP (\fBModel\fP owner, String name, double \fBalpha\fP, double \fBbeta\fP, boolean showInReport, boolean showInTrace)"
.br
.ti -1c
.RI "\fBdesmoj\&.core\&.report\&.Reporter\fP \fBcreateReporter\fP ()"
.br
.ti -1c
.RI "double \fBgetAlpha\fP ()"
.br
.ti -1c
.RI "double \fBgetBeta\fP ()"
.br
.ti -1c
.RI "Double \fBsample\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "double \fBalpha\fP"
.br
.ti -1c
.RI "double \fBbeta\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBDistribution\fP returning gamma distributed double values\&.
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Peter Wueppen 
.PP
.nf
    Licensed under the Apache License, Version 2.0 (the "License"); you
    may not use this file except in compliance with the License. You may
    obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
    implied. See the License for the specific language governing
    permissions and limitations under the License.
.fi
.PP
 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.core\&.dist\&.ContDistGamma\&.ContDistGamma (\fBModel\fPowner, Stringname, doublealpha, doublebeta, booleanshowInReport, booleanshowInTrace)"
Creates a stream of pseudo random numbers following a gamma distribution\&. The specific parameters alpha and beta have to be given here at creation time\&.
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP Model : The distribution's owner 
.br
\fIname\fP java\&.lang\&.String : The distribution's name 
.br
\fIalpha\fP double: \fBDistribution\fP specific shape parameter alpha 
.br
\fIbeta\fP double : \fBDistribution\fP specific scale parameter beta 
.br
\fIshowInReport\fP boolean : Flag for producing reports 
.br
\fIshowInTrace\fP boolean : Flag for producing trace output 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBdesmoj\&.core\&.report\&.Reporter\fP desmoj\&.core\&.dist\&.ContDistGamma\&.createReporter ()"
Creates the default reporter for the GammaDist distribution\&.
.PP
\fBReturns:\fP
.RS 4
Reporter : The reporter for the GammaDist distribution 
.RE
.PP
\fBSee Also:\fP
.RS 4
\fBdesmoj\&.core\&.report\&.ContDistGammaReporter\fP 
.RE
.PP

.SS "double desmoj\&.core\&.dist\&.ContDistGamma\&.getAlpha ()"

.PP
\fBReturns:\fP
.RS 4
double : \fBDistribution\fP specific shape parameter alpha 
.RE
.PP

.SS "double desmoj\&.core\&.dist\&.ContDistGamma\&.getBeta ()"

.PP
\fBReturns:\fP
.RS 4
double : \fBDistribution\fP specific scale parameter beta 
.RE
.PP

.SS "Double desmoj\&.core\&.dist\&.ContDistGamma\&.sample ()"
Returns the next sample from this distribution\&. The value depends upon the seed, the number of values taken from the stream by using this method before and the alpha and beta parameters specified for this distribution\&.
.PP
\fBReturns:\fP
.RS 4
Double : The next gamma distributed sample from this distribution\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "double desmoj\&.core\&.dist\&.ContDistGamma\&.alpha\fC [protected]\fP"
\fBDistribution\fP specific shape parameter alpha 
.SS "double desmoj\&.core\&.dist\&.ContDistGamma\&.beta\fC [protected]\fP"
\fBDistribution\fP specific scale parameter beta 

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
