.TH "desmoj.extensions.experimentation.util.BatchRunner" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.experimentation.util.BatchRunner \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Runnable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBatchRunner\fP (String batchfilename)"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)  throws Exception "
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "Document \fBbatchfile\fP"
.br
.ti -1c
.RI "HashMap \fBdefaultExpSettings\fP = new HashMap()"
.br
.ti -1c
.RI "HashMap \fBdefaultModelParams\fP = new HashMap()"
.br
.ti -1c
.RI "\fBModel\fP \fBmodel\fP = null"
.br
.ti -1c
.RI "\fBExperimentRunner\fP \fBexpRunner\fP = null"
.br
.ti -1c
.RI "String \fBbatchfilename\fP = null"
.br
.in -1c
.SH "Detailed Description"
.PP 
A class to run a batch of simulation experiments from the console\&. The batches must be specified in an XML file\&. The XML file must start with a <batch>tag\&. In the top level tag it is possible to specify model and experiment settings valid for every run using the <model>and <exp>tag known from the \fBRun\fP class\&. Furthermore an arbitrary number of runs (specified by a <run>tag) containing the variable settings can be embedded\&.
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
Nicolas Knaak
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.experimentation\&.util\&.BatchRunner\&.BatchRunner (Stringbatchfilename)"
Creates a new \fBBatchRunner\fP that loads the given batch file\&.
.PP
\fBParameters:\fP
.RS 4
\fIbatchfilename\fP name of an (XML-)batchfile 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static void desmoj\&.extensions\&.experimentation\&.util\&.BatchRunner\&.main (String[]args) throws Exception\fC [static]\fP"
Command line interface for the batch runner 
.SS "void desmoj\&.extensions\&.experimentation\&.util\&.BatchRunner\&.run ()"
Runs the simulations specified in the assigned batch file 

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
