.TH "desmoj.extensions.visualization2d.engine.util.SpringUtilities" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization2d.engine.util.SpringUtilities \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBprintSizes\fP (Component c)"
.br
.ti -1c
.RI "static void \fBmakeGrid\fP (Container parent, int rows, int cols, int initialX, int initialY, int xPad, int yPad)"
.br
.ti -1c
.RI "static void \fBmakeCompactGrid\fP (Container parent, int rows, int cols, int initialX, int initialY, int xPad, int yPad)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A 1\&.4 file that provides utility methods for creating form- or grid-style layouts with SpringLayout\&. These utilities are used by several programs, such as SpringBox and SpringCompactGrid\&. 
.SH "Member Function Documentation"
.PP 
.SS "static void desmoj\&.extensions\&.visualization2d\&.engine\&.util\&.SpringUtilities\&.makeCompactGrid (Containerparent, introws, intcols, intinitialX, intinitialY, intxPad, intyPad)\fC [static]\fP"
Aligns the first \fCrows\fP * \fCcols\fP components of \fCparent\fP in a grid\&. Each component in a column is as wide as the maximum preferred width of the components in that column; height is similarly determined for each row\&. The parent is made just big enough to fit them all\&.
.PP
\fBParameters:\fP
.RS 4
\fIrows\fP number of rows 
.br
\fIcols\fP number of columns 
.br
\fIinitialX\fP x location to start the grid at 
.br
\fIinitialY\fP y location to start the grid at 
.br
\fIxPad\fP x padding between cells 
.br
\fIyPad\fP y padding between cells 
.RE
.PP

.SS "static void desmoj\&.extensions\&.visualization2d\&.engine\&.util\&.SpringUtilities\&.makeGrid (Containerparent, introws, intcols, intinitialX, intinitialY, intxPad, intyPad)\fC [static]\fP"
Aligns the first \fCrows\fP * \fCcols\fP components of \fCparent\fP in a grid\&. Each component is as big as the maximum preferred width and height of the components\&. The parent is made just big enough to fit them all\&.
.PP
\fBParameters:\fP
.RS 4
\fIrows\fP number of rows 
.br
\fIcols\fP number of columns 
.br
\fIinitialX\fP x location to start the grid at 
.br
\fIinitialY\fP y location to start the grid at 
.br
\fIxPad\fP x padding between cells 
.br
\fIyPad\fP y padding between cells 
.RE
.PP

.SS "static void desmoj\&.extensions\&.visualization2d\&.engine\&.util\&.SpringUtilities\&.printSizes (Componentc)\fC [static]\fP"
A debugging utility that prints to stdout the component's minimum, preferred, and maximum sizes\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
