.TH "desmoj.extensions.visualization3d.SpatialVis3DModule" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization3d.SpatialVis3DModule \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.extensions\&.visualization3d\&.VisualModule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpatialVis3DModule\fP (final String name, String filePath)"
.br
.ti -1c
.RI "\fBSpatialVis3DModule\fP (final String name, String filePath, boolean createFrame)"
.br
.ti -1c
.RI "void \fBcreateFrame\fP (final String name)"
.br
.ti -1c
.RI "String \fBgetModuleName\fP ()"
.br
.ti -1c
.RI "void \fBhandleEvent\fP (\fBVisualEvent\fP event)"
.br
.ti -1c
.RI "void \fBsetVisualizationControl\fP (\fBVisualizationControl\fP visCon)"
.br
.ti -1c
.RI "void \fBregisterNewVisualEventListener\fP (\fBVisualEventListener\fP listener)"
.br
.ti -1c
.RI "void \fBremoveVisualizationControl\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP (final String name, String filePath)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "Canvas3D \fB_canvas3D\fP = null"
.br
.in -1c
.SH "Detailed Description"
.PP 
This Module visualize the 3D-spatial objects using Java3D\&. 
.PP
\fBAuthor:\fP
.RS 4
Fred Sun 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.visualization3d\&.SpatialVis3DModule\&.SpatialVis3DModule (final Stringname, StringfilePath)"
Constructs a SpatialVix3DModule and load the decoration models into the scene\&.
.PP
\fBParameters:\fP
.RS 4
\fIname\fP the name of this module\&. 
.br
\fIfilePath\fP The file path to the XML-file, where the model data is specified\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "String desmoj\&.extensions\&.visualization3d\&.SpatialVis3DModule\&.getModuleName ()\fC [virtual]\fP"
Gets the name of the \fBVisualModule\fP\&. 
.PP
\fBReturns:\fP
.RS 4
The name of the \fBVisualModule\fP\&. 
.RE
.PP

.PP
Implements \fBdesmoj\&.extensions\&.visualization3d\&.VisualModule\fP\&.
.SS "void desmoj\&.extensions\&.visualization3d\&.SpatialVis3DModule\&.handleEvent (\fBVisualEvent\fPevent)\fC [virtual]\fP"
Handle the received event\&. 
.PP
\fBParameters:\fP
.RS 4
\fIevent\fP The event to be handled\&. 
.RE
.PP

.PP
Implements \fBdesmoj\&.extensions\&.visualization3d\&.VisualModule\fP\&.
.SS "void desmoj\&.extensions\&.visualization3d\&.SpatialVis3DModule\&.registerNewVisualEventListener (\fBVisualEventListener\fPlistener)"
Registers a customized VisualEventListener to this module\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlistener\fP The listener to be registered\&. 
.RE
.PP

.SS "void desmoj\&.extensions\&.visualization3d\&.SpatialVis3DModule\&.removeVisualizationControl ()\fC [virtual]\fP"
If a \fBVisualizationControl\fP is set, it will be removed from the module's local attribute by calling this method\&. This method will be called by \fBVisualizationControl\fP at the removing of the module\&. 
.PP
Implements \fBdesmoj\&.extensions\&.visualization3d\&.VisualModule\fP\&.
.SS "void desmoj\&.extensions\&.visualization3d\&.SpatialVis3DModule\&.setVisualizationControl (\fBVisualizationControl\fPvisCon)\fC [virtual]\fP"
Saves the \fBVisualizationControl\fP this module as a local attribute\&. This method will be called by \fBVisualizationControl\fP at the registration of the module\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvisCon\fP The owner of this module 
.RE
.PP

.PP
Implements \fBdesmoj\&.extensions\&.visualization3d\&.VisualModule\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
