.TH "desmoj.extensions.visualization2d.engine.model.List" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualization2d.engine.model.List \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdesmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Basic\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBList\fP (\fBModel\fP model, String praefix, String id)"
.br
.ti -1c
.RI "\fBModel\fP \fBgetModel\fP ()"
.br
.ti -1c
.RI "String \fBgetId\fP ()"
.br
.ti -1c
.RI "void \fBsetName\fP (String name)"
.br
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.ti -1c
.RI "String \fBgetCommentText\fP ()"
.br
.ti -1c
.RI "void \fBsetCommentTest\fP (String text)"
.br
.ti -1c
.RI "Color \fBgetCommentColor\fP ()"
.br
.ti -1c
.RI "void \fBsetCommentColor\fP (Color color)"
.br
.ti -1c
.RI "Font \fBgetCommentFont\fP ()"
.br
.ti -1c
.RI "void \fBsetCommentFont\fP (int style, int size)"
.br
.ti -1c
.RI "boolean \fBisCommentSizeExt\fP ()"
.br
.ti -1c
.RI "void \fBsetCommentSizeExt\fP (boolean commentSizeExt)"
.br
.ti -1c
.RI "boolean \fBcontainsInContainer\fP (String entityId)"
.br
.ti -1c
.RI "String[] \fBgetAllContentFromContainer\fP ()"
.br
.ti -1c
.RI "\fBGrafic\fP \fBcreateGrafic\fP (String viewId, int x, int y, String defaultEntityTypeId, int anzVisible, boolean horizontal)"
.br
.ti -1c
.RI "\fBGrafic\fP \fBcreateGrafic\fP (String viewId, int x, int y, String defaultEntityTypeId, int anzVisible, boolean horizontal, Dimension deltaSize)"
.br
.ti -1c
.RI "\fBGrafic\fP \fBgetGrafic\fP ()"
.br
.ti -1c
.RI "boolean \fBaddToContainer\fP (String entityId, int priority, String priorityRule, long time)  throws ModelException"
.br
.ti -1c
.RI "boolean \fBaddToContainerAfter\fP (String entityId, int priority, String entityAfterId, long time)  throws ModelException"
.br
.ti -1c
.RI "boolean \fBaddToContainerBefore\fP (String entityId, int priority, String entityBeforeId, long time)  throws ModelException"
.br
.ti -1c
.RI "boolean \fBremoveFromContainer\fP (String entityId, long time)  throws ModelException"
.br
.ti -1c
.RI "String[][] \fBgetContent\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fBPREFIX_QUEUE\fP = 'queue:'"
.br
.ti -1c
.RI "static final String \fBPREFIX_RESOURCE\fP = 'resource:'"
.br
.ti -1c
.RI "static final String \fBPREFIX_BIN_CONSUMER\fP = 'binCons:'"
.br
.ti -1c
.RI "static final String \fBPREFIX_STOCK_CONSUMER\fP = 'stockCons:'"
.br
.ti -1c
.RI "static final String \fBPREFIX_STOCK_PRODUCER\fP = 'stockProd:'"
.br
.ti -1c
.RI "static final String \fBPREFIX_WAIT_MASTER\fP = 'waitMaster:'"
.br
.ti -1c
.RI "static final String \fBPREFIX_WAIT_SLAVE\fP = 'waitSlave:'"
.br
.ti -1c
.RI "static final String \fBPRIO_FIRST\fP = 'first'"
.br
.ti -1c
.RI "static final String \fBPRIO_LAST\fP = 'last'"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBModel\fP \fBmodel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A list of entities, entities are sorted by priority\&. Grafical properties are stired in ListGrafic
.PP
\fBVersion:\fP
.RS 4
DESMO-J, Ver\&. 2\&.4\&.0 copyright (c) 2013 
.RE
.PP
\fBAuthor:\fP
.RS 4
christian.mueller@th-wildau.de For information about subproject: desmoj\&.extensions\&.visualization2d please have a look at: http://www.th-wildau.de/cmueller/Desmo-J/Visualization2d/
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.List\&.List (\fBModel\fPmodel, Stringpraefix, Stringid)"

.PP
\fBParameters:\fP
.RS 4
\fImodel\fP used animation\&.model\&.Model 
.br
\fIpraefix\fP 
.br
\fIid\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "boolean desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.List\&.addToContainer (StringentityId, intpriority, StringpriorityRule, longtime) throws \fBModelException\fP"
add entity to container 
.PP
\fBParameters:\fP
.RS 4
\fIentityId\fP Id of entity to insert 
.br
\fIpriority\fP priority of entity to insert 
.br
\fIpriorityRule\fP posible Values: List\&.FIRST, List\&.LAST 
.br
\fItime\fP simulation-time of operating 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBModelException\fP\fP 
.RE
.PP

.SS "boolean desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.List\&.addToContainerAfter (StringentityId, intpriority, StringentityAfterId, longtime) throws \fBModelException\fP"
Add entity after a given entity 
.PP
\fBParameters:\fP
.RS 4
\fIentityId\fP Id of entity to insert 
.br
\fIpriority\fP priority of new entity 
.br
\fIentityAfterId\fP Id of after entity 
.br
\fItime\fP simulation time of operation 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBModelException\fP\fP 
.RE
.PP

.SS "boolean desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.List\&.addToContainerBefore (StringentityId, intpriority, StringentityBeforeId, longtime) throws \fBModelException\fP"
Add entity before a given entity 
.PP
\fBParameters:\fP
.RS 4
\fIentityId\fP Id of entity to insert 
.br
\fIpriority\fP priority of new entity 
.br
\fIentityBeforeId\fP Id of before entity 
.br
\fItime\fP simulation time of operation 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBModelException\fP\fP 
.RE
.PP

.SS "boolean desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.List\&.containsInContainer (StringentityId)"
check if it contains a entity with entityId 
.PP
\fBParameters:\fP
.RS 4
\fIentityId\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "\fBGrafic\fP desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.List\&.createGrafic (StringviewId, intx, inty, StringdefaultEntityTypeId, intanzVisible, booleanhorizontal)"
create a ListGrafic instance 
.PP
\fBParameters:\fP
.RS 4
\fIviewId\fP Id of view 
.br
\fIx\fP x-coordinate of middlepoint 
.br
\fIy\fP y-coordinate of middlepoint 
.br
\fIdefaultEntityTypeId\fP for sizing 
.br
\fIanzVisible\fP nr of visible entities 
.br
\fIhorizontal\fP 'horizontal' or 'vertical' 
.RE
.PP
\fBReturns:\fP
.RS 4
ListGrafic 
.RE
.PP

.SS "\fBGrafic\fP desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.List\&.createGrafic (StringviewId, intx, inty, StringdefaultEntityTypeId, intanzVisible, booleanhorizontal, DimensiondeltaSize)"
create a ListGrafic instance 
.PP
\fBParameters:\fP
.RS 4
\fIviewId\fP Id of view 
.br
\fIx\fP x-coordinate of middlepoint 
.br
\fIy\fP y-coordinate of middlepoint 
.br
\fIdefaultEntityTypeId\fP for sizing 
.br
\fIanzVisible\fP nr of visible entities 
.br
\fIhorizontal\fP 'horizontal' or 'vertical' 
.RE
.PP
\fBReturns:\fP
.RS 4
ListGrafic 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIdeltaSize\fP increment/decrement size of grafic [in pixel] 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "String [] desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.List\&.getAllContentFromContainer ()"
get an array with id's of all entities in container 
.PP
\fBReturns:\fP
.RS 4
array with id's 
.RE
.PP

.SS "String [][] desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.List\&.getContent ()"
get content of list 
.PP
\fBReturns:\fP
.RS 4
(entity-id, rank) 
.RE
.PP

.SS "\fBGrafic\fP desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.List\&.getGrafic ()"
get a ListGrafic instance, created before 
.PP
Implements \fBdesmoj\&.extensions\&.visualization2d\&.engine\&.model\&.Basic\fP\&.
.SS "boolean desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.List\&.removeFromContainer (StringentityId, longtime) throws \fBModelException\fP"
remove entity from list entityId time operation-time 
.SS "void desmoj\&.extensions\&.visualization2d\&.engine\&.model\&.List\&.setName (Stringname)"
set list-name 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
