.TH "desmoj.extensions.visualEvents.VisualEventTransmitter" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desmoj.extensions.visualEvents.VisualEventTransmitter \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBaddVisualEventListener\fP (\fBVisualEventListener\fP listener)"
.br
.ti -1c
.RI "void \fBremoveVisualEventListener\fP (\fBVisualEventListener\fP listener)"
.br
.ti -1c
.RI "void \fBfireVisualEvent\fP (\fBVisualEvent\fP evt)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBVisualEventTransmitter\fP \fBgetVisualEventTransmitter\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is responsible for firing the SpatialEvents\&. It is a singleton, so every listener only have to be assigned once\&. 
.PP
\fBAuthor:\fP
.RS 4
Fred Sun 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void desmoj\&.extensions\&.visualEvents\&.VisualEventTransmitter\&.addVisualEventListener (\fBVisualEventListener\fPlistener)"
Registers a new \fBVisualEventListener\fP to the SpatialMovementManager\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlistener\fP The listener to be registered\&. 
.RE
.PP

.SS "void desmoj\&.extensions\&.visualEvents\&.VisualEventTransmitter\&.fireVisualEvent (\fBVisualEvent\fPevt)"
Fires a \fBVisualEvent\fP\&.
.PP
\fBParameters:\fP
.RS 4
\fIevt\fP The \fBVisualEvent\fP to be fired\&. 
.RE
.PP

.SS "static \fBVisualEventTransmitter\fP desmoj\&.extensions\&.visualEvents\&.VisualEventTransmitter\&.getVisualEventTransmitter ()\fC [static]\fP"
The static get method for the \fBVisualEventTransmitter\fP 
.PP
\fBReturns:\fP
.RS 4
The singleton \fBVisualEventTransmitter\fP 
.RE
.PP

.SS "void desmoj\&.extensions\&.visualEvents\&.VisualEventTransmitter\&.removeVisualEventListener (\fBVisualEventListener\fPlistener)"
Removes a registered \fBVisualEventListener\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlistener\fP The listener to be removed\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
