.TH "org.apache.commons.math.distribution.GammaDistribution" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.apache.commons.math.distribution.GammaDistribution \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.apache\&.commons\&.math\&.distribution\&.ContinuousDistribution\fP\&.
.PP
Inherited by \fBorg\&.apache\&.commons\&.math\&.distribution\&.GammaDistributionImpl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetAlpha\fP (double alpha)"
.br
.ti -1c
.RI "double \fBgetAlpha\fP ()"
.br
.ti -1c
.RI "void \fBsetBeta\fP (double beta)"
.br
.ti -1c
.RI "double \fBgetBeta\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The Gamma \fBDistribution\fP\&.
.PP
References: 
.PD 0

.IP "\(bu" 2
\fCGamma Distribution\fP 
.PP
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision:\fP
.RS 4
545192 
.RE
.PP
\fBDate:\fP
.RS 4
2007-06-07 07:35:04 -0700 (Thu, 07 Jun 2007) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "double org\&.apache\&.commons\&.math\&.distribution\&.GammaDistribution\&.getAlpha ()"
Access the shape parameter, alpha 
.PP
\fBReturns:\fP
.RS 4
alpha\&. 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.GammaDistributionImpl\fP\&.
.SS "double org\&.apache\&.commons\&.math\&.distribution\&.GammaDistribution\&.getBeta ()"
Access the scale parameter, beta 
.PP
\fBReturns:\fP
.RS 4
beta\&. 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.GammaDistributionImpl\fP\&.
.SS "void org\&.apache\&.commons\&.math\&.distribution\&.GammaDistribution\&.setAlpha (doublealpha)"
Modify the shape parameter, alpha\&. 
.PP
\fBParameters:\fP
.RS 4
\fIalpha\fP the new shape parameter\&. 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.GammaDistributionImpl\fP\&.
.SS "void org\&.apache\&.commons\&.math\&.distribution\&.GammaDistribution\&.setBeta (doublebeta)"
Modify the scale parameter, beta\&. 
.PP
\fBParameters:\fP
.RS 4
\fIbeta\fP the new scale parameter\&. 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.GammaDistributionImpl\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
