.TH "org.apache.commons.math.analysis.NevilleInterpolator" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.apache.commons.math.analysis.NevilleInterpolator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.apache\&.commons\&.math\&.analysis\&.UnivariateRealInterpolator\fP, and Serializable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnivariateRealFunction\fP \fBinterpolate\fP (double x[], double y[])  throws MathException "
.br
.in -1c
.SH "Detailed Description"
.PP 
Implements the \fCNeville's Algorithm\fP for interpolation of real univariate functions\&. For reference, see \fBIntroduction to Numerical Analysis\fP, ISBN 038795452X, chapter 2\&. 
.PP
The actual code of Neville's evalution is in \fBPolynomialFunctionLagrangeForm\fP, this class provides an easy-to-use interface to it\&.
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision:\fP
.RS 4
620312 
.RE
.PP
\fBDate:\fP
.RS 4
2008-02-10 12:28:59 -0700 (Sun, 10 Feb 2008) 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.2 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBUnivariateRealFunction\fP org\&.apache\&.commons\&.math\&.analysis\&.NevilleInterpolator\&.interpolate (doublex[], doubley[]) throws \fBMathException\fP"
Computes an interpolating function for the data set\&.
.PP
\fBParameters:\fP
.RS 4
\fIx\fP the interpolating points array 
.br
\fIy\fP the interpolating values array 
.RE
.PP
\fBReturns:\fP
.RS 4
a function which interpolates the data set 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBMathException\fP\fP if arguments are invalid 
.RE
.PP

.PP
Implements \fBorg\&.apache\&.commons\&.math\&.analysis\&.UnivariateRealInterpolator\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
