.TH "org.apache.commons.math.distribution.WeibullDistribution" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.apache.commons.math.distribution.WeibullDistribution \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.apache\&.commons\&.math\&.distribution\&.ContinuousDistribution\fP\&.
.PP
Inherited by \fBorg\&.apache\&.commons\&.math\&.distribution\&.WeibullDistributionImpl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBgetShape\fP ()"
.br
.ti -1c
.RI "double \fBgetScale\fP ()"
.br
.ti -1c
.RI "void \fBsetShape\fP (double alpha)"
.br
.ti -1c
.RI "void \fBsetScale\fP (double beta)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Weibull \fBDistribution\fP\&. This interface defines the two parameter form of the distribution as defined by \fCWeibull Distribution\fP, equations (1) and (2)\&.
.PP
References: 
.PD 0

.IP "\(bu" 2
\fCWeibull Distribution\fP 
.PP
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision:\fP
.RS 4
613570 
.RE
.PP
\fBDate:\fP
.RS 4
2008-01-20 08:03:24 -0700 (Sun, 20 Jan 2008) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "double org\&.apache\&.commons\&.math\&.distribution\&.WeibullDistribution\&.getScale ()"
Access the scale parameter\&. 
.PP
\fBReturns:\fP
.RS 4
the scale parameter\&. 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.WeibullDistributionImpl\fP\&.
.SS "double org\&.apache\&.commons\&.math\&.distribution\&.WeibullDistribution\&.getShape ()"
Access the shape parameter\&. 
.PP
\fBReturns:\fP
.RS 4
the shape parameter\&. 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.WeibullDistributionImpl\fP\&.
.SS "void org\&.apache\&.commons\&.math\&.distribution\&.WeibullDistribution\&.setScale (doublebeta)"
Modify the scale parameter\&. 
.PP
\fBParameters:\fP
.RS 4
\fIbeta\fP The new scale parameter value\&. 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.WeibullDistributionImpl\fP\&.
.SS "void org\&.apache\&.commons\&.math\&.distribution\&.WeibullDistribution\&.setShape (doublealpha)"
Modify the shape parameter\&. 
.PP
\fBParameters:\fP
.RS 4
\fIalpha\fP The new shape parameter value\&. 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.WeibullDistributionImpl\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
