.TH "org.apache.commons.collections.IterableMap" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.apache.commons.collections.IterableMap \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Map\&.
.PP
Inherited by \fBorg\&.apache\&.commons\&.collections\&.map\&.AbstractHashedMap\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMapIterator\fP \fBmapIterator\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines a map that can be iterated directly without needing to create an entry set\&. 
.PP
A map iterator is an efficient way of iterating over maps\&. There is no need to access the entry set or cast to Map Entry objects\&. 
.PP
.nf

\fBIterableMap\fP map = new HashedMap();
\fBMapIterator\fP it = map\&.mapIterator();
while (it\&.hasNext()) {
  Object key = it\&.next();
  Object value = it\&.getValue();
  it\&.setValue('newValue');
}
.fi
.PP
.PP
\fBSince:\fP
.RS 4
Commons Collections 3\&.0 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision:\fP
.RS 4
646777 
.RE
.PP
\fBDate:\fP
.RS 4
2008-04-10 13:33:15 +0100 (Thu, 10 Apr 2008) 
.RE
.PP
.PP
\fBAuthor:\fP
.RS 4
Stephen Colebourne 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBMapIterator\fP org\&.apache\&.commons\&.collections\&.IterableMap\&.mapIterator ()"
Obtains a \fC\fBMapIterator\fP\fP over the map\&. 
.PP
A map iterator is an efficient way of iterating over maps\&. There is no need to access the entry set or cast to Map Entry objects\&. 
.PP
.nf

\fBIterableMap\fP map = new HashedMap();
\fBMapIterator\fP it = map\&.mapIterator();
while (it\&.hasNext()) {
  Object key = it\&.next();
  Object value = it\&.getValue();
  it\&.setValue('newValue');
}
.fi
.PP
.PP
\fBReturns:\fP
.RS 4
a map iterator 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.collections\&.map\&.AbstractHashedMap\fP, and \fBorg\&.apache\&.commons\&.collections\&.map\&.AbstractReferenceMap\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
