.TH "org.apache.commons.math.distribution.ChiSquaredDistribution" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.apache.commons.math.distribution.ChiSquaredDistribution \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.apache\&.commons\&.math\&.distribution\&.ContinuousDistribution\fP\&.
.PP
Inherited by \fBorg\&.apache\&.commons\&.math\&.distribution\&.ChiSquaredDistributionImpl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetDegreesOfFreedom\fP (double degreesOfFreedom)"
.br
.ti -1c
.RI "double \fBgetDegreesOfFreedom\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The Chi-Squared \fBDistribution\fP\&.
.PP
References: 
.PD 0

.IP "\(bu" 2
\fCChi-Squared Distribution\fP 
.PP
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision:\fP
.RS 4
545192 
.RE
.PP
\fBDate:\fP
.RS 4
2007-06-07 07:35:04 -0700 (Thu, 07 Jun 2007) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "double org\&.apache\&.commons\&.math\&.distribution\&.ChiSquaredDistribution\&.getDegreesOfFreedom ()"
Access the degrees of freedom\&. 
.PP
\fBReturns:\fP
.RS 4
the degrees of freedom\&. 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.ChiSquaredDistributionImpl\fP\&.
.SS "void org\&.apache\&.commons\&.math\&.distribution\&.ChiSquaredDistribution\&.setDegreesOfFreedom (doubledegreesOfFreedom)"
Modify the degrees of freedom\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdegreesOfFreedom\fP the new degrees of freedom\&. 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.ChiSquaredDistributionImpl\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
