.TH "org.apache.commons.math.distribution.DiscreteDistribution" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.apache.commons.math.distribution.DiscreteDistribution \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.apache\&.commons\&.math\&.distribution\&.Distribution\fP\&.
.PP
Inherited by \fBorg\&.apache\&.commons\&.math\&.distribution\&.IntegerDistribution\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBprobability\fP (double x)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base interface for discrete distributions\&.
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision:\fP
.RS 4
480440 
.RE
.PP
\fBDate:\fP
.RS 4
2006-11-29 00:14:12 -0700 (Wed, 29 Nov 2006) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "double org\&.apache\&.commons\&.math\&.distribution\&.DiscreteDistribution\&.probability (doublex)"
For a random variable X whose values are distributed according to this distribution, this method returns P(X = x)\&. In other words, this method represents the probability mass function, or PMF for the distribution\&.
.PP
\fBParameters:\fP
.RS 4
\fIx\fP the value at which the probability mass function is evaluated\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
the value of the probability mass function at x 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.AbstractIntegerDistribution\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
