.TH "org.apache.commons.collections.OrderedIterator" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.apache.commons.collections.OrderedIterator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Iterator\&.
.PP
Inherited by org\&.apache\&.commons\&.collections\&.list\&.TreeList\&.TreeListIterator\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBhasPrevious\fP ()"
.br
.ti -1c
.RI "Object \fBprevious\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines an iterator that operates over an ordered collection\&. 
.PP
This iterator allows both forward and reverse iteration through the collection\&.
.PP
\fBSince:\fP
.RS 4
Commons Collections 3\&.0 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision:\fP
.RS 4
1\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
2008/02/19 16:57:08 
.RE
.PP
.PP
\fBAuthor:\fP
.RS 4
Stephen Colebourne 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "boolean org\&.apache\&.commons\&.collections\&.OrderedIterator\&.hasPrevious ()"
Checks to see if there is a previous element that can be iterated to\&.
.PP
\fBReturns:\fP
.RS 4
\fCtrue\fP if the iterator has a previous element 
.RE
.PP

.SS "Object org\&.apache\&.commons\&.collections\&.OrderedIterator\&.previous ()"
Gets the previous element from the collection\&.
.PP
\fBReturns:\fP
.RS 4
the previous element in the iteration 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIjava\&.util\&.NoSuchElementException\fP if the iteration is finished 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
