.TH "org.apache.commons.collections.keyvalue.DefaultMapEntry" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.apache.commons.collections.keyvalue.DefaultMapEntry \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.apache\&.commons\&.collections\&.keyvalue\&.AbstractMapEntry\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDefaultMapEntry\fP (final Object \fBkey\fP, final Object \fBvalue\fP)"
.br
.ti -1c
.RI "\fBDefaultMapEntry\fP (final \fBKeyValue\fP pair)"
.br
.ti -1c
.RI "\fBDefaultMapEntry\fP (final Map\&.Entry entry)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A restricted implementation of \fBjava\&.util\&.Map\&.Entry\fP that prevents the \fCMap\&.Entry\fP contract from being broken\&.
.PP
\fBSince:\fP
.RS 4
Commons Collections 3\&.0 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision:\fP
.RS 4
646777 
.RE
.PP
\fBDate:\fP
.RS 4
2008-04-10 13:33:15 +0100 (Thu, 10 Apr 2008) 
.RE
.PP
.PP
\fBAuthor:\fP
.RS 4
James Strachan 
.PP
Michael A\&. Smith 
.PP
Neil O'Toole 
.PP
Stephen Colebourne 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.apache\&.commons\&.collections\&.keyvalue\&.DefaultMapEntry\&.DefaultMapEntry (final Objectkey, final Objectvalue)"
Constructs a new entry with the specified key and given value\&.
.PP
\fBParameters:\fP
.RS 4
\fIkey\fP the key for the entry, may be null 
.br
\fIvalue\fP the value for the entry, may be null 
.RE
.PP

.SS "org\&.apache\&.commons\&.collections\&.keyvalue\&.DefaultMapEntry\&.DefaultMapEntry (final \fBKeyValue\fPpair)"
Constructs a new entry from the specified \fC\fBKeyValue\fP\fP\&.
.PP
\fBParameters:\fP
.RS 4
\fIpair\fP the pair to copy, must not be null 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fINullPointerException\fP if the entry is null 
.RE
.PP

.SS "org\&.apache\&.commons\&.collections\&.keyvalue\&.DefaultMapEntry\&.DefaultMapEntry (final Map\&.Entryentry)"
Constructs a new entry from the specified \fCMap\&.Entry\fP\&.
.PP
\fBParameters:\fP
.RS 4
\fIentry\fP the entry to copy, must not be null 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fINullPointerException\fP if the entry is null 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
