.TH "org.apache.commons.math.distribution.ExponentialDistribution" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.apache.commons.math.distribution.ExponentialDistribution \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.apache\&.commons\&.math\&.distribution\&.ContinuousDistribution\fP\&.
.PP
Inherited by \fBorg\&.apache\&.commons\&.math\&.distribution\&.ExponentialDistributionImpl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetMean\fP (double mean)"
.br
.ti -1c
.RI "double \fBgetMean\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The Exponential \fBDistribution\fP\&.
.PP
References: 
.PD 0

.IP "\(bu" 2
\fCExponential Distribution\fP 
.PP
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision:\fP
.RS 4
545192 
.RE
.PP
\fBDate:\fP
.RS 4
2007-06-07 07:35:04 -0700 (Thu, 07 Jun 2007) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "double org\&.apache\&.commons\&.math\&.distribution\&.ExponentialDistribution\&.getMean ()"
Access the mean\&. 
.PP
\fBReturns:\fP
.RS 4
the mean\&. 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.ExponentialDistributionImpl\fP\&.
.SS "void org\&.apache\&.commons\&.math\&.distribution\&.ExponentialDistribution\&.setMean (doublemean)"
Modify the mean\&. 
.PP
\fBParameters:\fP
.RS 4
\fImean\fP the new mean\&. 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.ExponentialDistributionImpl\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
