.TH "org.apache.commons.math.distribution.BinomialDistribution" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.apache.commons.math.distribution.BinomialDistribution \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.apache\&.commons\&.math\&.distribution\&.IntegerDistribution\fP\&.
.PP
Inherited by \fBorg\&.apache\&.commons\&.math\&.distribution\&.BinomialDistributionImpl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBgetNumberOfTrials\fP ()"
.br
.ti -1c
.RI "double \fBgetProbabilityOfSuccess\fP ()"
.br
.ti -1c
.RI "void \fBsetNumberOfTrials\fP (int trials)"
.br
.ti -1c
.RI "void \fBsetProbabilityOfSuccess\fP (double p)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The Binomial \fBDistribution\fP\&.
.PP
References: 
.PD 0

.IP "\(bu" 2
\fCBinomial Distribution\fP 
.PP
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision:\fP
.RS 4
545192 
.RE
.PP
\fBDate:\fP
.RS 4
2007-06-07 07:35:04 -0700 (Thu, 07 Jun 2007) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "int org\&.apache\&.commons\&.math\&.distribution\&.BinomialDistribution\&.getNumberOfTrials ()"
Access the number of trials for this distribution\&. 
.PP
\fBReturns:\fP
.RS 4
the number of trials\&. 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.BinomialDistributionImpl\fP\&.
.SS "double org\&.apache\&.commons\&.math\&.distribution\&.BinomialDistribution\&.getProbabilityOfSuccess ()"
Access the probability of success for this distribution\&. 
.PP
\fBReturns:\fP
.RS 4
the probability of success\&. 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.BinomialDistributionImpl\fP\&.
.SS "void org\&.apache\&.commons\&.math\&.distribution\&.BinomialDistribution\&.setNumberOfTrials (inttrials)"
Change the number of trials for this distribution\&. 
.PP
\fBParameters:\fP
.RS 4
\fItrials\fP the new number of trials\&. 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.BinomialDistributionImpl\fP\&.
.SS "void org\&.apache\&.commons\&.math\&.distribution\&.BinomialDistribution\&.setProbabilityOfSuccess (doublep)"
Change the probability of success for this distribution\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp\fP the new probability of success\&. 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.BinomialDistributionImpl\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
