.TH "org.apache.commons.math.analysis.RiddersSolver" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.apache.commons.math.analysis.RiddersSolver \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.apache\&.commons\&.math\&.analysis\&.UnivariateRealSolverImpl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRiddersSolver\fP (\fBUnivariateRealFunction\fP \fBf\fP)"
.br
.ti -1c
.RI "double \fBsolve\fP (double min, double max, double initial)  throws MaxIterationsExceededException, FunctionEvaluationException "
.br
.ti -1c
.RI "double \fBsolve\fP (double min, double max)  throws MaxIterationsExceededException,          FunctionEvaluationException "
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Implements the \fCRidders' Method\fP for root finding of real univariate functions\&. For reference, see C\&. Ridders, \fIA new algorithm for computing a single root of a real continuous function \fP, IEEE Transactions on Circuits and Systems, 26 (1979), 979 - 980\&. 
.PP
The function should be continuous but not necessarily smooth\&.
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision:\fP
.RS 4
620312 
.RE
.PP
\fBDate:\fP
.RS 4
2008-02-10 12:28:59 -0700 (Sun, 10 Feb 2008) 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.2 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.apache\&.commons\&.math\&.analysis\&.RiddersSolver\&.RiddersSolver (\fBUnivariateRealFunction\fPf)"
Construct a solver for the given function\&.
.PP
\fBParameters:\fP
.RS 4
\fIf\fP function to solve 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "double org\&.apache\&.commons\&.math\&.analysis\&.RiddersSolver\&.solve (doublemin, doublemax, doubleinitial) throws \fBMaxIterationsExceededException\fP, \fBFunctionEvaluationException\fP"
Find a root in the given interval with initial value\&. 
.PP
Requires bracketing condition\&.
.PP
\fBParameters:\fP
.RS 4
\fImin\fP the lower bound for the interval 
.br
\fImax\fP the upper bound for the interval 
.br
\fIinitial\fP the start value to use 
.RE
.PP
\fBReturns:\fP
.RS 4
the point at which the function value is zero 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBMaxIterationsExceededException\fP\fP if the maximum iteration count is exceeded 
.br
\fI\fBFunctionEvaluationException\fP\fP if an error occurs evaluating the function 
.br
\fIIllegalArgumentException\fP if any parameters are invalid 
.RE
.PP

.PP
Implements \fBorg\&.apache\&.commons\&.math\&.analysis\&.UnivariateRealSolver\fP\&.
.SS "double org\&.apache\&.commons\&.math\&.analysis\&.RiddersSolver\&.solve (doublemin, doublemax) throws \fBMaxIterationsExceededException\fP,          \fBFunctionEvaluationException\fP"
Find a root in the given interval\&. 
.PP
Requires bracketing condition\&.
.PP
\fBParameters:\fP
.RS 4
\fImin\fP the lower bound for the interval 
.br
\fImax\fP the upper bound for the interval 
.RE
.PP
\fBReturns:\fP
.RS 4
the point at which the function value is zero 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBMaxIterationsExceededException\fP\fP if the maximum iteration count is exceeded 
.br
\fI\fBFunctionEvaluationException\fP\fP if an error occurs evaluating the function 
.br
\fIIllegalArgumentException\fP if any parameters are invalid 
.RE
.PP

.PP
Implements \fBorg\&.apache\&.commons\&.math\&.analysis\&.UnivariateRealSolver\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
