.TH "org.apache.commons.math.distribution.HypergeometricDistribution" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.apache.commons.math.distribution.HypergeometricDistribution \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.apache\&.commons\&.math\&.distribution\&.IntegerDistribution\fP\&.
.PP
Inherited by \fBorg\&.apache\&.commons\&.math\&.distribution\&.HypergeometricDistributionImpl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract int \fBgetNumberOfSuccesses\fP ()"
.br
.ti -1c
.RI "abstract int \fBgetPopulationSize\fP ()"
.br
.ti -1c
.RI "abstract int \fBgetSampleSize\fP ()"
.br
.ti -1c
.RI "abstract void \fBsetNumberOfSuccesses\fP (int num)"
.br
.ti -1c
.RI "abstract void \fBsetPopulationSize\fP (int size)"
.br
.ti -1c
.RI "abstract void \fBsetSampleSize\fP (int size)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The Hypergeometric \fBDistribution\fP\&.
.PP
References: 
.PD 0

.IP "\(bu" 2
\fCHypergeometric Distribution\fP 
.PP
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision:\fP
.RS 4
545192 
.RE
.PP
\fBDate:\fP
.RS 4
2007-06-07 07:35:04 -0700 (Thu, 07 Jun 2007) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "abstract int org\&.apache\&.commons\&.math\&.distribution\&.HypergeometricDistribution\&.getNumberOfSuccesses ()\fC [pure virtual]\fP"
Access the number of successes\&. 
.PP
\fBReturns:\fP
.RS 4
the number of successes\&. 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.HypergeometricDistributionImpl\fP\&.
.SS "abstract int org\&.apache\&.commons\&.math\&.distribution\&.HypergeometricDistribution\&.getPopulationSize ()\fC [pure virtual]\fP"
Access the population size\&. 
.PP
\fBReturns:\fP
.RS 4
the population size\&. 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.HypergeometricDistributionImpl\fP\&.
.SS "abstract int org\&.apache\&.commons\&.math\&.distribution\&.HypergeometricDistribution\&.getSampleSize ()\fC [pure virtual]\fP"
Access the sample size\&. 
.PP
\fBReturns:\fP
.RS 4
the sample size\&. 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.HypergeometricDistributionImpl\fP\&.
.SS "abstract void org\&.apache\&.commons\&.math\&.distribution\&.HypergeometricDistribution\&.setNumberOfSuccesses (intnum)\fC [pure virtual]\fP"
Modify the number of successes\&. 
.PP
\fBParameters:\fP
.RS 4
\fInum\fP the new number of successes\&. 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.HypergeometricDistributionImpl\fP\&.
.SS "abstract void org\&.apache\&.commons\&.math\&.distribution\&.HypergeometricDistribution\&.setPopulationSize (intsize)\fC [pure virtual]\fP"
Modify the population size\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsize\fP the new population size\&. 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.HypergeometricDistributionImpl\fP\&.
.SS "abstract void org\&.apache\&.commons\&.math\&.distribution\&.HypergeometricDistribution\&.setSampleSize (intsize)\fC [pure virtual]\fP"
Modify the sample size\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsize\fP the new sample size\&. 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.HypergeometricDistributionImpl\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
