.TH "org.apache.commons.collections.KeyValue" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.apache.commons.collections.KeyValue \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBorg\&.apache\&.commons\&.collections\&.keyvalue\&.AbstractKeyValue\fP, and org\&.apache\&.commons\&.collections\&.map\&.AbstractHashedMap\&.HashEntry\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Object \fBgetKey\fP ()"
.br
.ti -1c
.RI "Object \fBgetValue\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines a simple key value pair\&. 
.PP
A Map Entry has considerable additional semantics over and above a simple key-value pair\&. This interface defines the minimum key value, with just the two get methods\&.
.PP
\fBSince:\fP
.RS 4
Commons Collections 3\&.0 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision:\fP
.RS 4
646777 
.RE
.PP
\fBDate:\fP
.RS 4
2008-04-10 13:33:15 +0100 (Thu, 10 Apr 2008) 
.RE
.PP
.PP
\fBAuthor:\fP
.RS 4
Stephen Colebourne 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "Object org\&.apache\&.commons\&.collections\&.KeyValue\&.getKey ()"
Gets the key from the pair\&.
.PP
\fBReturns:\fP
.RS 4
the key 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.collections\&.keyvalue\&.AbstractKeyValue\fP\&.
.SS "Object org\&.apache\&.commons\&.collections\&.KeyValue\&.getValue ()"
Gets the value from the pair\&.
.PP
\fBReturns:\fP
.RS 4
the value 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.collections\&.keyvalue\&.AbstractKeyValue\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
