.TH "org.apache.commons.math.MaxIterationsExceededException" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.apache.commons.math.MaxIterationsExceededException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.apache\&.commons\&.math\&.ConvergenceException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMaxIterationsExceededException\fP (int maxIterations)"
.br
.ti -1c
.RI "\fBMaxIterationsExceededException\fP (int maxIterations, String pattern, Object[] arguments)"
.br
.ti -1c
.RI "int \fBgetMaxIterations\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Error thrown when a numerical computation exceeds its allowed number of iterations\&.
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision:\fP
.RS 4
620312 
.RE
.PP
\fBDate:\fP
.RS 4
2008-02-10 12:28:59 -0700 (Sun, 10 Feb 2008) 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.2 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.apache\&.commons\&.math\&.MaxIterationsExceededException\&.MaxIterationsExceededException (intmaxIterations)"
Constructs an exception with specified formatted detail message\&. Message formatting is delegated to \fBjava\&.text\&.MessageFormat\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fImaxIterations\fP maximal number of iterations allowed 
.RE
.PP

.SS "org\&.apache\&.commons\&.math\&.MaxIterationsExceededException\&.MaxIterationsExceededException (intmaxIterations, Stringpattern, Object[]arguments)"
Constructs an exception with specified formatted detail message\&. Message formatting is delegated to \fBjava\&.text\&.MessageFormat\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fImaxIterations\fP the exceeded maximal number of iterations 
.br
\fIpattern\fP format specifier 
.br
\fIarguments\fP format arguments 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "int org\&.apache\&.commons\&.math\&.MaxIterationsExceededException\&.getMaxIterations ()"
Get the maximal number of iterations allowed\&. 
.PP
\fBReturns:\fP
.RS 4
maximal number of iterations allowed 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
