.TH "org.apache.commons.math.distribution.NormalDistribution" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.apache.commons.math.distribution.NormalDistribution \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.apache\&.commons\&.math\&.distribution\&.ContinuousDistribution\fP\&.
.PP
Inherited by \fBorg\&.apache\&.commons\&.math\&.distribution\&.NormalDistributionImpl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBgetMean\fP ()"
.br
.ti -1c
.RI "void \fBsetMean\fP (double mean)"
.br
.ti -1c
.RI "double \fBgetStandardDeviation\fP ()"
.br
.ti -1c
.RI "void \fBsetStandardDeviation\fP (double sd)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Normal (Gauss) \fBDistribution\fP\&.
.PP
References:
.PP
.PD 0
.IP "\(bu" 2
\fCNormal Distribution\fP 
.PP
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision:\fP
.RS 4
617953 
.RE
.PP
\fBDate:\fP
.RS 4
2008-02-02 22:54:00 -0700 (Sat, 02 Feb 2008) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "double org\&.apache\&.commons\&.math\&.distribution\&.NormalDistribution\&.getMean ()"
Access the mean\&. 
.PP
\fBReturns:\fP
.RS 4
mean for this distribution 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.NormalDistributionImpl\fP\&.
.SS "double org\&.apache\&.commons\&.math\&.distribution\&.NormalDistribution\&.getStandardDeviation ()"
Access the standard deviation\&. 
.PP
\fBReturns:\fP
.RS 4
standard deviation for this distribution 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.NormalDistributionImpl\fP\&.
.SS "void org\&.apache\&.commons\&.math\&.distribution\&.NormalDistribution\&.setMean (doublemean)"
Modify the mean\&. 
.PP
\fBParameters:\fP
.RS 4
\fImean\fP for this distribution 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.NormalDistributionImpl\fP\&.
.SS "void org\&.apache\&.commons\&.math\&.distribution\&.NormalDistribution\&.setStandardDeviation (doublesd)"
Modify the standard deviation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsd\fP standard deviation for this distribution 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.NormalDistributionImpl\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
