.TH "org.apache.commons.collections.ResettableIterator" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.apache.commons.collections.ResettableIterator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Iterator\&.
.PP
Inherited by \fBorg\&.apache\&.commons\&.collections\&.iterators\&.EmptyIterator\fP, and \fBorg\&.apache\&.commons\&.collections\&.iterators\&.EmptyMapIterator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBreset\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines an iterator that can be reset back to an initial state\&. 
.PP
This interface allows an iterator to be repeatedly reused\&.
.PP
\fBSince:\fP
.RS 4
Commons Collections 3\&.0 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision:\fP
.RS 4
646777 
.RE
.PP
\fBDate:\fP
.RS 4
2008-04-10 13:33:15 +0100 (Thu, 10 Apr 2008) 
.RE
.PP
.PP
\fBAuthor:\fP
.RS 4
Stephen Colebourne 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void org\&.apache\&.commons\&.collections\&.ResettableIterator\&.reset ()"
Resets the iterator back to the position at which the iterator was created\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
