.TH "org.apache.commons.math.analysis.UnivariateRealFunction" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.apache.commons.math.analysis.UnivariateRealFunction \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBdesmoj\&.core\&.dist\&.Function\fP, \fBorg\&.apache\&.commons\&.math\&.analysis\&.DifferentiableUnivariateRealFunction\fP, \fBorg\&.apache\&.commons\&.math\&.analysis\&.PolynomialFunctionLagrangeForm\fP, and \fBorg\&.apache\&.commons\&.math\&.analysis\&.PolynomialFunctionNewtonForm\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBvalue\fP (double x)  throws FunctionEvaluationException"
.br
.in -1c
.SH "Detailed Description"
.PP 
An interface representing a univariate real function\&.
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision:\fP
.RS 4
480440 
.RE
.PP
\fBDate:\fP
.RS 4
2006-11-29 00:14:12 -0700 (Wed, 29 Nov 2006) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "double org\&.apache\&.commons\&.math\&.analysis\&.UnivariateRealFunction\&.value (doublex) throws \fBFunctionEvaluationException\fP"
Compute the value for the function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP the point for which the function value should be computed 
.RE
.PP
\fBReturns:\fP
.RS 4
the value 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBFunctionEvaluationException\fP\fP if the function evaluation fails 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.analysis\&.PolynomialSplineFunction\fP, \fBorg\&.apache\&.commons\&.math\&.analysis\&.PolynomialFunctionNewtonForm\fP, \fBorg\&.apache\&.commons\&.math\&.analysis\&.PolynomialFunctionLagrangeForm\fP, \fBorg\&.apache\&.commons\&.math\&.analysis\&.PolynomialFunction\fP, and \fBdesmoj\&.core\&.dist\&.Function\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
