.TH "org.apache.commons.collections.keyvalue.AbstractMapEntry" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.apache.commons.collections.keyvalue.AbstractMapEntry \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.apache\&.commons\&.collections\&.keyvalue\&.AbstractKeyValue\fP, and Entry\&.
.PP
Inherited by \fBorg\&.apache\&.commons\&.collections\&.keyvalue\&.DefaultMapEntry\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Object \fBsetValue\fP (Object \fBvalue\fP)"
.br
.ti -1c
.RI "boolean \fBequals\fP (Object obj)"
.br
.ti -1c
.RI "int \fBhashCode\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBAbstractMapEntry\fP (Object \fBkey\fP, Object \fBvalue\fP)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Abstract Pair class to assist with creating correct \fBMap\&.Entry\fP implementations\&.
.PP
\fBSince:\fP
.RS 4
Commons Collections 3\&.0 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision:\fP
.RS 4
646777 
.RE
.PP
\fBDate:\fP
.RS 4
2008-04-10 13:33:15 +0100 (Thu, 10 Apr 2008) 
.RE
.PP
.PP
\fBAuthor:\fP
.RS 4
James Strachan 
.PP
Michael A\&. Smith 
.PP
Neil O'Toole 
.PP
Stephen Colebourne 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.apache\&.commons\&.collections\&.keyvalue\&.AbstractMapEntry\&.AbstractMapEntry (Objectkey, Objectvalue)\fC [protected]\fP"
Constructs a new entry with the given key and given value\&.
.PP
\fBParameters:\fP
.RS 4
\fIkey\fP the key for the entry, may be null 
.br
\fIvalue\fP the value for the entry, may be null 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "boolean org\&.apache\&.commons\&.collections\&.keyvalue\&.AbstractMapEntry\&.equals (Objectobj)"
Compares this \fCMap\&.Entry\fP with another \fCMap\&.Entry\fP\&. 
.PP
Implemented per API documentation of \fBjava\&.util\&.Map\&.Entry#equals(Object)\fP
.PP
\fBParameters:\fP
.RS 4
\fIobj\fP the object to compare to 
.RE
.PP
\fBReturns:\fP
.RS 4
true if equal key and value 
.RE
.PP

.SS "int org\&.apache\&.commons\&.collections\&.keyvalue\&.AbstractMapEntry\&.hashCode ()"
Gets a hashCode compatible with the equals method\&. 
.PP
Implemented per API documentation of \fBjava\&.util\&.Map\&.Entry#hashCode()\fP
.PP
\fBReturns:\fP
.RS 4
a suitable hash code 
.RE
.PP

.SS "Object org\&.apache\&.commons\&.collections\&.keyvalue\&.AbstractMapEntry\&.setValue (Objectvalue)"
Sets the value stored in this \fCMap\&.Entry\fP\&. 
.PP
This \fCMap\&.Entry\fP is not connected to a Map, so only the local data is changed\&.
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP the new value 
.RE
.PP
\fBReturns:\fP
.RS 4
the previous value 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
