.TH "org.apache.commons.math.distribution.ContinuousDistribution" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.apache.commons.math.distribution.ContinuousDistribution \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.apache\&.commons\&.math\&.distribution\&.Distribution\fP\&.
.PP
Inherited by \fBorg\&.apache\&.commons\&.math\&.distribution\&.AbstractContinuousDistribution\fP, \fBorg\&.apache\&.commons\&.math\&.distribution\&.CauchyDistribution\fP, \fBorg\&.apache\&.commons\&.math\&.distribution\&.ChiSquaredDistribution\fP, \fBorg\&.apache\&.commons\&.math\&.distribution\&.ExponentialDistribution\fP, \fBorg\&.apache\&.commons\&.math\&.distribution\&.FDistribution\fP, \fBorg\&.apache\&.commons\&.math\&.distribution\&.GammaDistribution\fP, \fBorg\&.apache\&.commons\&.math\&.distribution\&.NormalDistribution\fP, \fBorg\&.apache\&.commons\&.math\&.distribution\&.TDistribution\fP, and \fBorg\&.apache\&.commons\&.math\&.distribution\&.WeibullDistribution\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBinverseCumulativeProbability\fP (double p)  throws MathException"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base interface for continuous distributions\&.
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision:\fP
.RS 4
480440 
.RE
.PP
\fBDate:\fP
.RS 4
2006-11-29 00:14:12 -0700 (Wed, 29 Nov 2006) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "double org\&.apache\&.commons\&.math\&.distribution\&.ContinuousDistribution\&.inverseCumulativeProbability (doublep) throws \fBMathException\fP"
For this disbution, X, this method returns x such that P(X < x) = p\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp\fP the cumulative probability\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
x\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBMathException\fP\fP if the inverse cumulative probability can not be computed due to convergence or other numerical errors\&. 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.ExponentialDistributionImpl\fP, \fBorg\&.apache\&.commons\&.math\&.distribution\&.CauchyDistributionImpl\fP, and \fBorg\&.apache\&.commons\&.math\&.distribution\&.WeibullDistributionImpl\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
