.TH "org.apache.commons.math.distribution.PoissonDistribution" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.apache.commons.math.distribution.PoissonDistribution \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.apache\&.commons\&.math\&.distribution\&.IntegerDistribution\fP\&.
.PP
Inherited by \fBorg\&.apache\&.commons\&.math\&.distribution\&.PoissonDistributionImpl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBgetMean\fP ()"
.br
.ti -1c
.RI "void \fBsetMean\fP (double p)"
.br
.ti -1c
.RI "double \fBnormalApproximateProbability\fP (int x)  throws MathException"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface representing the Poisson \fBDistribution\fP\&.
.PP
References: 
.PD 0

.IP "\(bu" 2
\fCPoisson distribution\fP 
.PP
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision:\fP
.RS 4
480440 
.RE
.PP
\fBDate:\fP
.RS 4
2006-11-29 00:14:12 -0700 (Wed, 29 Nov 2006) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "double org\&.apache\&.commons\&.math\&.distribution\&.PoissonDistribution\&.getMean ()"
Get the mean for the distribution\&.
.PP
\fBReturns:\fP
.RS 4
the mean for the distribution\&. 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.PoissonDistributionImpl\fP\&.
.SS "double org\&.apache\&.commons\&.math\&.distribution\&.PoissonDistribution\&.normalApproximateProbability (intx) throws \fBMathException\fP"
Calculates the Poisson distribution function using a normal approximation\&.
.PP
\fBParameters:\fP
.RS 4
\fIx\fP the upper bound, inclusive 
.RE
.PP
\fBReturns:\fP
.RS 4
the distribution function value calculated using a normal approximation 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBMathException\fP\fP if an error occurs computing the normal approximation 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.PoissonDistributionImpl\fP\&.
.SS "void org\&.apache\&.commons\&.math\&.distribution\&.PoissonDistribution\&.setMean (doublep)"
Set the mean for the distribution\&. The parameter value must be positive; otherwise an \fCIllegalArgument\fP is thrown\&.
.PP
\fBParameters:\fP
.RS 4
\fIp\fP the mean 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIIllegalArgumentException\fP if p  0 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.PoissonDistributionImpl\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
