.TH "org.apache.commons.math.MathConfigurationException" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.apache.commons.math.MathConfigurationException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.apache\&.commons\&.math\&.MathException\fP, and Serializable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMathConfigurationException\fP ()"
.br
.ti -1c
.RI "\fBMathConfigurationException\fP (String message)"
.br
.ti -1c
.RI "\fBMathConfigurationException\fP (String pattern, Object[] arguments)"
.br
.ti -1c
.RI "\fBMathConfigurationException\fP (String message, Throwable cause)"
.br
.ti -1c
.RI "\fBMathConfigurationException\fP (Throwable cause)"
.br
.ti -1c
.RI "\fBMathConfigurationException\fP (String pattern, Object[] arguments, Throwable cause)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Signals a configuration problem with any of the factory methods\&. 
.PP
\fBVersion:\fP
.RS 4

.RE
.PP
\fBRevision:\fP
.RS 4
620312 
.RE
.PP
\fBDate:\fP
.RS 4
2008-02-10 12:28:59 -0700 (Sun, 10 Feb 2008) 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.apache\&.commons\&.math\&.MathConfigurationException\&.MathConfigurationException ()"
Default constructor\&. 
.SS "org\&.apache\&.commons\&.math\&.MathConfigurationException\&.MathConfigurationException (Stringmessage)"
Construct an exception with the given message\&. 
.PP
\fBParameters:\fP
.RS 4
\fImessage\fP descriptive error message 
.RE
.PP
\fBDeprecated\fP
.RS 4
as of 1\&.2, replaced by \fBMathConfigurationException(String, Object[])\fP 
.RE
.PP

.SS "org\&.apache\&.commons\&.math\&.MathConfigurationException\&.MathConfigurationException (Stringpattern, Object[]arguments)"
Constructs an exception with specified formatted detail message\&. Message formatting is delegated to \fBjava\&.text\&.MessageFormat\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpattern\fP format specifier 
.br
\fIarguments\fP format arguments 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.2 
.RE
.PP

.SS "org\&.apache\&.commons\&.math\&.MathConfigurationException\&.MathConfigurationException (Stringmessage, Throwablecause)"
Construct an exception with the given message and root cause\&. 
.PP
\fBParameters:\fP
.RS 4
\fImessage\fP descriptive error message 
.br
\fIcause\fP the exception or error that caused this exception to be thrown 
.RE
.PP
\fBDeprecated\fP
.RS 4
as of 1\&.2, replaced by \fBMathConfigurationException(String, Object[], Throwable)\fP 
.RE
.PP

.SS "org\&.apache\&.commons\&.math\&.MathConfigurationException\&.MathConfigurationException (Throwablecause)"
Create an exception with a given root cause\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcause\fP the exception or error that caused this exception to be thrown 
.RE
.PP

.SS "org\&.apache\&.commons\&.math\&.MathConfigurationException\&.MathConfigurationException (Stringpattern, Object[]arguments, Throwablecause)"
Constructs an exception with specified formatted detail message and root cause\&. Message formatting is delegated to \fBjava\&.text\&.MessageFormat\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpattern\fP format specifier 
.br
\fIarguments\fP format arguments 
.br
\fIcause\fP the exception or error that caused this exception to be thrown 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.2 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
