.TH "org.apache.commons.math.ConvergenceException" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.apache.commons.math.ConvergenceException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.apache\&.commons\&.math\&.MathException\fP\&.
.PP
Inherited by \fBorg\&.apache\&.commons\&.math\&.MaxIterationsExceededException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConvergenceException\fP ()"
.br
.ti -1c
.RI "\fBConvergenceException\fP (String pattern, Object[] arguments)"
.br
.ti -1c
.RI "\fBConvergenceException\fP (Throwable cause)"
.br
.ti -1c
.RI "\fBConvergenceException\fP (String pattern, Object[] arguments, Throwable cause)"
.br
.ti -1c
.RI "\fBConvergenceException\fP (String msg, Throwable rootCause)"
.br
.ti -1c
.RI "\fBConvergenceException\fP (String msg)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Error thrown when a numerical computation can not be performed because the numerical result failed to converge to a finite value\&.
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision:\fP
.RS 4
620312 
.RE
.PP
\fBDate:\fP
.RS 4
2008-02-10 12:28:59 -0700 (Sun, 10 Feb 2008) 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.apache\&.commons\&.math\&.ConvergenceException\&.ConvergenceException ()"
Default constructor\&. 
.SS "org\&.apache\&.commons\&.math\&.ConvergenceException\&.ConvergenceException (Stringpattern, Object[]arguments)"
Constructs an exception with specified formatted detail message\&. Message formatting is delegated to \fBjava\&.text\&.MessageFormat\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpattern\fP format specifier 
.br
\fIarguments\fP format arguments 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.2 
.RE
.PP

.SS "org\&.apache\&.commons\&.math\&.ConvergenceException\&.ConvergenceException (Throwablecause)"
Create an exception with a given root cause\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcause\fP the exception or error that caused this exception to be thrown 
.RE
.PP

.SS "org\&.apache\&.commons\&.math\&.ConvergenceException\&.ConvergenceException (Stringpattern, Object[]arguments, Throwablecause)"
Constructs an exception with specified formatted detail message and root cause\&. Message formatting is delegated to \fBjava\&.text\&.MessageFormat\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpattern\fP format specifier 
.br
\fIarguments\fP format arguments 
.br
\fIcause\fP the exception or error that caused this exception to be thrown 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.2 
.RE
.PP

.SS "org\&.apache\&.commons\&.math\&.ConvergenceException\&.ConvergenceException (Stringmsg, ThrowablerootCause)"
Constructs a new \fC\fBConvergenceException\fP\fP with specified detail message and nested \fCThrowable\fP root cause\&.
.PP
\fBParameters:\fP
.RS 4
\fImsg\fP the error message\&. 
.br
\fIrootCause\fP the exception or error that caused this exception to be thrown\&. 
.RE
.PP
\fBDeprecated\fP
.RS 4
as of 1\&.2, replaced by \fBConvergenceException(String, Object[], Throwable)\fP 
.RE
.PP

.SS "org\&.apache\&.commons\&.math\&.ConvergenceException\&.ConvergenceException (Stringmsg)"
Constructs a new \fC\fBConvergenceException\fP\fP with specified detail message\&.
.PP
\fBParameters:\fP
.RS 4
\fImsg\fP the error message\&. 
.RE
.PP
\fBDeprecated\fP
.RS 4
as of 1\&.2, replaced by \fBConvergenceException(String, Object[])\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
