.TH "org.apache.commons.math.analysis.DifferentiableUnivariateRealFunction" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.apache.commons.math.analysis.DifferentiableUnivariateRealFunction \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.apache\&.commons\&.math\&.analysis\&.UnivariateRealFunction\fP\&.
.PP
Inherited by \fBorg\&.apache\&.commons\&.math\&.analysis\&.PolynomialFunction\fP, and \fBorg\&.apache\&.commons\&.math\&.analysis\&.PolynomialSplineFunction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnivariateRealFunction\fP \fBderivative\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Extension of \fBUnivariateRealFunction\fP representing a differentiable univariate real function\&.
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision:\fP
.RS 4
480440 
.RE
.PP
\fBDate:\fP
.RS 4
2006-11-29 00:14:12 -0700 (Wed, 29 Nov 2006) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBUnivariateRealFunction\fP org\&.apache\&.commons\&.math\&.analysis\&.DifferentiableUnivariateRealFunction\&.derivative ()"
Returns the derivative of the function
.PP
\fBReturns:\fP
.RS 4
the derivative function 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.analysis\&.PolynomialFunction\fP, and \fBorg\&.apache\&.commons\&.math\&.analysis\&.PolynomialSplineFunction\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
