.TH "org.apache.commons.math.distribution.GammaDistributionImpl" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.apache.commons.math.distribution.GammaDistributionImpl \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.apache\&.commons\&.math\&.distribution\&.AbstractContinuousDistribution\fP, \fBorg\&.apache\&.commons\&.math\&.distribution\&.GammaDistribution\fP, and Serializable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGammaDistributionImpl\fP (double alpha, double beta)"
.br
.ti -1c
.RI "double \fBcumulativeProbability\fP (double x)  throws MathException"
.br
.ti -1c
.RI "double \fBinverseCumulativeProbability\fP (final double p)  throws MathException "
.br
.ti -1c
.RI "void \fBsetAlpha\fP (double alpha)"
.br
.ti -1c
.RI "double \fBgetAlpha\fP ()"
.br
.ti -1c
.RI "void \fBsetBeta\fP (double beta)"
.br
.ti -1c
.RI "double \fBgetBeta\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "double \fBgetDomainLowerBound\fP (double p)"
.br
.ti -1c
.RI "double \fBgetDomainUpperBound\fP (double p)"
.br
.ti -1c
.RI "double \fBgetInitialDomain\fP (double p)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The default implementation of \fBGammaDistribution\fP\&.
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision:\fP
.RS 4
617953 
.RE
.PP
\fBDate:\fP
.RS 4
2008-02-02 22:54:00 -0700 (Sat, 02 Feb 2008) 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.apache\&.commons\&.math\&.distribution\&.GammaDistributionImpl\&.GammaDistributionImpl (doublealpha, doublebeta)"
Create a new gamma distribution with the given alpha and beta values\&. 
.PP
\fBParameters:\fP
.RS 4
\fIalpha\fP the shape parameter\&. 
.br
\fIbeta\fP the scale parameter\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "double org\&.apache\&.commons\&.math\&.distribution\&.GammaDistributionImpl\&.cumulativeProbability (doublex) throws \fBMathException\fP"
For this disbution, X, this method returns P(X < x)\&.
.PP
The implementation of this method is based on: 
.PD 0

.IP "\(bu" 2
\fCChi-Squared Distribution\fP, equation (9)\&. 
.IP "\(bu" 2
Casella, G\&., & Berger, R\&. (1990)\&. \fIStatistical Inference\fP\&. Belmont, CA: Duxbury Press\&. 
.PP
.PP
\fBParameters:\fP
.RS 4
\fIx\fP the value at which the CDF is evaluated\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
CDF for this distribution\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBMathException\fP\fP if the cumulative probability can not be computed due to convergence or other numerical errors\&. 
.RE
.PP

.PP
Implements \fBorg\&.apache\&.commons\&.math\&.distribution\&.Distribution\fP\&.
.SS "double org\&.apache\&.commons\&.math\&.distribution\&.GammaDistributionImpl\&.getAlpha ()"
Access the shape parameter, alpha 
.PP
\fBReturns:\fP
.RS 4
alpha\&. 
.RE
.PP

.PP
Implements \fBorg\&.apache\&.commons\&.math\&.distribution\&.GammaDistribution\fP\&.
.SS "double org\&.apache\&.commons\&.math\&.distribution\&.GammaDistributionImpl\&.getBeta ()"
Access the scale parameter, beta 
.PP
\fBReturns:\fP
.RS 4
beta\&. 
.RE
.PP

.PP
Implements \fBorg\&.apache\&.commons\&.math\&.distribution\&.GammaDistribution\fP\&.
.SS "double org\&.apache\&.commons\&.math\&.distribution\&.GammaDistributionImpl\&.getDomainLowerBound (doublep)\fC [protected]\fP, \fC [virtual]\fP"
Access the domain value lower bound, based on \fCp\fP, used to bracket a CDF root\&. This method is used by \fBinverseCumulativeProbability(double)\fP to find critical values\&.
.PP
\fBParameters:\fP
.RS 4
\fIp\fP the desired probability for the critical value 
.RE
.PP
\fBReturns:\fP
.RS 4
domain value lower bound, i\&.e\&. P(X < \fIlower bound\fP) < \fCp\fP 
.RE
.PP

.PP
Implements \fBorg\&.apache\&.commons\&.math\&.distribution\&.AbstractContinuousDistribution\fP\&.
.SS "double org\&.apache\&.commons\&.math\&.distribution\&.GammaDistributionImpl\&.getDomainUpperBound (doublep)\fC [protected]\fP, \fC [virtual]\fP"
Access the domain value upper bound, based on \fCp\fP, used to bracket a CDF root\&. This method is used by \fBinverseCumulativeProbability(double)\fP to find critical values\&.
.PP
\fBParameters:\fP
.RS 4
\fIp\fP the desired probability for the critical value 
.RE
.PP
\fBReturns:\fP
.RS 4
domain value upper bound, i\&.e\&. P(X < \fIupper bound\fP) > \fCp\fP 
.RE
.PP

.PP
Implements \fBorg\&.apache\&.commons\&.math\&.distribution\&.AbstractContinuousDistribution\fP\&.
.SS "double org\&.apache\&.commons\&.math\&.distribution\&.GammaDistributionImpl\&.getInitialDomain (doublep)\fC [protected]\fP, \fC [virtual]\fP"
Access the initial domain value, based on \fCp\fP, used to bracket a CDF root\&. This method is used by \fBinverseCumulativeProbability(double)\fP to find critical values\&.
.PP
\fBParameters:\fP
.RS 4
\fIp\fP the desired probability for the critical value 
.RE
.PP
\fBReturns:\fP
.RS 4
initial domain value 
.RE
.PP

.PP
Implements \fBorg\&.apache\&.commons\&.math\&.distribution\&.AbstractContinuousDistribution\fP\&.
.SS "double org\&.apache\&.commons\&.math\&.distribution\&.GammaDistributionImpl\&.inverseCumulativeProbability (final doublep) throws \fBMathException\fP"
For this distribution, X, this method returns the critical point x, such that P(X < x) = \fCp\fP\&. 
.PP
Returns 0 for p=0 and \fCDouble\&.POSITIVE_INFINITY\fP for p=1\&.
.PP
\fBParameters:\fP
.RS 4
\fIp\fP the desired probability 
.RE
.PP
\fBReturns:\fP
.RS 4
x, such that P(X < x) = \fCp\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBMathException\fP\fP if the inverse cumulative probability can not be computed due to convergence or other numerical errors\&. 
.br
\fIIllegalArgumentException\fP if \fCp\fP is not a valid probability\&. 
.RE
.PP

.SS "void org\&.apache\&.commons\&.math\&.distribution\&.GammaDistributionImpl\&.setAlpha (doublealpha)"
Modify the shape parameter, alpha\&. 
.PP
\fBParameters:\fP
.RS 4
\fIalpha\fP the new shape parameter\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIIllegalArgumentException\fP if \fCalpha\fP is not positive\&. 
.RE
.PP

.PP
Implements \fBorg\&.apache\&.commons\&.math\&.distribution\&.GammaDistribution\fP\&.
.SS "void org\&.apache\&.commons\&.math\&.distribution\&.GammaDistributionImpl\&.setBeta (doublebeta)"
Modify the scale parameter, beta\&. 
.PP
\fBParameters:\fP
.RS 4
\fIbeta\fP the new scale parameter\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIIllegalArgumentException\fP if \fCbeta\fP is not positive\&. 
.RE
.PP

.PP
Implements \fBorg\&.apache\&.commons\&.math\&.distribution\&.GammaDistribution\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
