.TH "org.apache.commons.math.special.Beta" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.apache.commons.math.special.Beta \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Serializable\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static double \fBregularizedBeta\fP (double x, double a, double b)  throws MathException     "
.br
.ti -1c
.RI "static double \fBregularizedBeta\fP (double x, double a, double b, double epsilon)  throws MathException     "
.br
.ti -1c
.RI "static double \fBregularizedBeta\fP (double x, double a, double b, int maxIterations)  throws MathException     "
.br
.ti -1c
.RI "static double \fBregularizedBeta\fP (double x, final double a, final double b, double epsilon, int maxIterations)  throws MathException     "
.br
.ti -1c
.RI "static double \fBlogBeta\fP (double a, double b)"
.br
.ti -1c
.RI "static double \fBlogBeta\fP (double a, double b, double epsilon, int maxIterations)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is a utility class that provides computation methods related to the \fBBeta\fP family of functions\&.
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision:\fP
.RS 4
549278 
.RE
.PP
\fBDate:\fP
.RS 4
2007-06-20 15:24:04 -0700 (Wed, 20 Jun 2007) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static double org\&.apache\&.commons\&.math\&.special\&.Beta\&.logBeta (doublea, doubleb)\fC [static]\fP"
Returns the natural logarithm of the beta function B(a, b)\&.
.PP
\fBParameters:\fP
.RS 4
\fIa\fP the a parameter\&. 
.br
\fIb\fP the b parameter\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
log(B(a, b)) 
.RE
.PP

.SS "static double org\&.apache\&.commons\&.math\&.special\&.Beta\&.logBeta (doublea, doubleb, doubleepsilon, intmaxIterations)\fC [static]\fP"
Returns the natural logarithm of the beta function B(a, b)\&.
.PP
The implementation of this method is based on: 
.PD 0

.IP "\(bu" 2
\fCBeta Function\fP, equation (1)\&. 
.PP
.PP
\fBParameters:\fP
.RS 4
\fIa\fP the a parameter\&. 
.br
\fIb\fP the b parameter\&. 
.br
\fIepsilon\fP When the absolute value of the nth item in the series is less than epsilon the approximation ceases to calculate further elements in the series\&. 
.br
\fImaxIterations\fP Maximum number of 'iterations' to complete\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
log(B(a, b)) 
.RE
.PP

.SS "static double org\&.apache\&.commons\&.math\&.special\&.Beta\&.regularizedBeta (doublex, doublea, doubleb) throws \fBMathException\fP\fC [static]\fP"
Returns the \fCregularized beta function\fP I(x, a, b)\&.
.PP
\fBParameters:\fP
.RS 4
\fIx\fP the value\&. 
.br
\fIa\fP the a parameter\&. 
.br
\fIb\fP the b parameter\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
the regularized beta function I(x, a, b) 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBMathException\fP\fP if the algorithm fails to converge\&. 
.RE
.PP

.SS "static double org\&.apache\&.commons\&.math\&.special\&.Beta\&.regularizedBeta (doublex, doublea, doubleb, doubleepsilon) throws \fBMathException\fP\fC [static]\fP"
Returns the \fCregularized beta function\fP I(x, a, b)\&.
.PP
\fBParameters:\fP
.RS 4
\fIx\fP the value\&. 
.br
\fIa\fP the a parameter\&. 
.br
\fIb\fP the b parameter\&. 
.br
\fIepsilon\fP When the absolute value of the nth item in the series is less than epsilon the approximation ceases to calculate further elements in the series\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
the regularized beta function I(x, a, b) 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBMathException\fP\fP if the algorithm fails to converge\&. 
.RE
.PP

.SS "static double org\&.apache\&.commons\&.math\&.special\&.Beta\&.regularizedBeta (doublex, doublea, doubleb, intmaxIterations) throws \fBMathException\fP\fC [static]\fP"
Returns the regularized beta function I(x, a, b)\&.
.PP
\fBParameters:\fP
.RS 4
\fIx\fP the value\&. 
.br
\fIa\fP the a parameter\&. 
.br
\fIb\fP the b parameter\&. 
.br
\fImaxIterations\fP Maximum number of 'iterations' to complete\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
the regularized beta function I(x, a, b) 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBMathException\fP\fP if the algorithm fails to converge\&. 
.RE
.PP

.SS "static double org\&.apache\&.commons\&.math\&.special\&.Beta\&.regularizedBeta (doublex, final doublea, final doubleb, doubleepsilon, intmaxIterations) throws \fBMathException\fP\fC [static]\fP"
Returns the regularized beta function I(x, a, b)\&.
.PP
The implementation of this method is based on: 
.PD 0

.IP "\(bu" 2
\fCRegularized Beta Function\fP\&. 
.IP "\(bu" 2
\fCRegularized Beta Function\fP\&. 
.PP
.PP
\fBParameters:\fP
.RS 4
\fIx\fP the value\&. 
.br
\fIa\fP the a parameter\&. 
.br
\fIb\fP the b parameter\&. 
.br
\fIepsilon\fP When the absolute value of the nth item in the series is less than epsilon the approximation ceases to calculate further elements in the series\&. 
.br
\fImaxIterations\fP Maximum number of 'iterations' to complete\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
the regularized beta function I(x, a, b) 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBMathException\fP\fP if the algorithm fails to converge\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
