.TH "org.apache.commons.math.distribution.CauchyDistribution" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.apache.commons.math.distribution.CauchyDistribution \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.apache\&.commons\&.math\&.distribution\&.ContinuousDistribution\fP\&.
.PP
Inherited by \fBorg\&.apache\&.commons\&.math\&.distribution\&.CauchyDistributionImpl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBgetMedian\fP ()"
.br
.ti -1c
.RI "double \fBgetScale\fP ()"
.br
.ti -1c
.RI "void \fBsetMedian\fP (double median)"
.br
.ti -1c
.RI "void \fBsetScale\fP (double s)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Cauchy \fBDistribution\fP\&.
.PP
References: 
.PD 0

.IP "\(bu" 2
\fCCauchy Distribution\fP 
.PP
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision:\fP
.RS 4
617953 
.RE
.PP
\fBDate:\fP
.RS 4
2008-02-02 22:54:00 -0700 (Sat, 02 Feb 2008) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "double org\&.apache\&.commons\&.math\&.distribution\&.CauchyDistribution\&.getMedian ()"
Access the median\&. 
.PP
\fBReturns:\fP
.RS 4
median for this distribution 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.CauchyDistributionImpl\fP\&.
.SS "double org\&.apache\&.commons\&.math\&.distribution\&.CauchyDistribution\&.getScale ()"
Access the scale parameter\&. 
.PP
\fBReturns:\fP
.RS 4
scale parameter for this distribution 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.CauchyDistributionImpl\fP\&.
.SS "void org\&.apache\&.commons\&.math\&.distribution\&.CauchyDistribution\&.setMedian (doublemedian)"
Modify the median\&. 
.PP
\fBParameters:\fP
.RS 4
\fImedian\fP for this distribution 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.CauchyDistributionImpl\fP\&.
.SS "void org\&.apache\&.commons\&.math\&.distribution\&.CauchyDistribution\&.setScale (doubles)"
Modify the scale parameter\&. 
.PP
\fBParameters:\fP
.RS 4
\fIs\fP scale parameter for this distribution 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.CauchyDistributionImpl\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
