.TH "org.apache.commons.collections.keyvalue.AbstractKeyValue" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.apache.commons.collections.keyvalue.AbstractKeyValue \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.apache\&.commons\&.collections\&.KeyValue\fP\&.
.PP
Inherited by \fBorg\&.apache\&.commons\&.collections\&.keyvalue\&.AbstractMapEntry\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Object \fBgetKey\fP ()"
.br
.ti -1c
.RI "Object \fBgetValue\fP ()"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBAbstractKeyValue\fP (Object \fBkey\fP, Object \fBvalue\fP)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "Object \fBkey\fP"
.br
.ti -1c
.RI "Object \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Abstract pair class to assist with creating \fC\fBKeyValue\fP\fP and \fBMap\&.Entry\fP implementations\&.
.PP
\fBSince:\fP
.RS 4
Commons Collections 3\&.0 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision:\fP
.RS 4
646777 
.RE
.PP
\fBDate:\fP
.RS 4
2008-04-10 13:33:15 +0100 (Thu, 10 Apr 2008) 
.RE
.PP
.PP
\fBAuthor:\fP
.RS 4
James Strachan 
.PP
Michael A\&. Smith 
.PP
Neil O'Toole 
.PP
Stephen Colebourne 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.apache\&.commons\&.collections\&.keyvalue\&.AbstractKeyValue\&.AbstractKeyValue (Objectkey, Objectvalue)\fC [protected]\fP"
Constructs a new pair with the specified key and given value\&.
.PP
\fBParameters:\fP
.RS 4
\fIkey\fP the key for the entry, may be null 
.br
\fIvalue\fP the value for the entry, may be null 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "Object org\&.apache\&.commons\&.collections\&.keyvalue\&.AbstractKeyValue\&.getKey ()"
Gets the key from the pair\&.
.PP
\fBReturns:\fP
.RS 4
the key 
.RE
.PP

.PP
Implements \fBorg\&.apache\&.commons\&.collections\&.KeyValue\fP\&.
.SS "Object org\&.apache\&.commons\&.collections\&.keyvalue\&.AbstractKeyValue\&.getValue ()"
Gets the value from the pair\&.
.PP
\fBReturns:\fP
.RS 4
the value 
.RE
.PP

.PP
Implements \fBorg\&.apache\&.commons\&.collections\&.KeyValue\fP\&.
.SS "String org\&.apache\&.commons\&.collections\&.keyvalue\&.AbstractKeyValue\&.toString ()"
Gets a debugging String view of the pair\&.
.PP
\fBReturns:\fP
.RS 4
a String view of the entry 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "Object org\&.apache\&.commons\&.collections\&.keyvalue\&.AbstractKeyValue\&.key\fC [protected]\fP"
The key 
.SS "Object org\&.apache\&.commons\&.collections\&.keyvalue\&.AbstractKeyValue\&.value\fC [protected]\fP"
The value 

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
