.TH "org.apache.commons.math.util.DefaultTransformer" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.apache.commons.math.util.DefaultTransformer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.apache\&.commons\&.math\&.util\&.NumberTransformer\fP, and Serializable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBtransform\fP (Object o)  throws MathException"
.br
.in -1c
.SH "Detailed Description"
.PP 
A Default \fBNumberTransformer\fP for java\&.lang\&.Numbers and Numeric Strings\&. This provides some simple conversion capabilities to turn any java/lang\&.Number into a primitive double or to turn a String representation of a Number into a double\&.
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision:\fP
.RS 4
506600 
.RE
.PP
\fBDate:\fP
.RS 4
2007-02-12 12:35:59 -0700 (Mon, 12 Feb 2007) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "double org\&.apache\&.commons\&.math\&.util\&.DefaultTransformer\&.transform (Objecto) throws \fBMathException\fP"

.PP
\fBParameters:\fP
.RS 4
\fIo\fP the object that gets transformed\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
a double primitive representation of the Object o\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBorg\&.apache\&.commons\&.math\&.MathException\fP\fP If it cannot successfully be transformed or is null\&. 
.RE
.PP
\fBSee Also:\fP
.RS 4
org\&.apache\&.commons\&.collections\&.Transformer::transform(java\&.lang\&.Object) 
.RE
.PP

.PP
Implements \fBorg\&.apache\&.commons\&.math\&.util\&.NumberTransformer\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
