.TH "org.apache.commons.math.distribution.PascalDistribution" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.apache.commons.math.distribution.PascalDistribution \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.apache\&.commons\&.math\&.distribution\&.IntegerDistribution\fP\&.
.PP
Inherited by \fBorg\&.apache\&.commons\&.math\&.distribution\&.PascalDistributionImpl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBgetNumberOfSuccesses\fP ()"
.br
.ti -1c
.RI "double \fBgetProbabilityOfSuccess\fP ()"
.br
.ti -1c
.RI "void \fBsetNumberOfSuccesses\fP (int successes)"
.br
.ti -1c
.RI "void \fBsetProbabilityOfSuccess\fP (double p)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The Pascal distribution\&. The Pascal distribution is a special case of the Negative Binomial distribution where the number of successes parameter is an integer\&.
.PP
There are various ways to express the probability mass and distribution functions for the Pascal distribution\&. The convention employed by the library is to express these functions in terms of the number of failures in a Bernoulli experiment [2]\&.
.PP
References: 
.PD 0

.IP "1." 4
\fCNegative Binomial Distribution\fP <oi>\fCWaiting Time in a Bernoulli Process\fP  
.PP
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision:\fP
.RS 4
613570 
.RE
.PP
\fBDate:\fP
.RS 4
2008-01-20 08:03:24 -0700 (Sun, 20 Jan 2008) 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.2 
.RE
.PP

.PP

.SH "Member Function Documentation"
.PP 
.SS "int org\&.apache\&.commons\&.math\&.distribution\&.PascalDistribution\&.getNumberOfSuccesses ()"
Access the number of successes for this distribution\&.
.PP
\fBReturns:\fP
.RS 4
the number of successes 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.PascalDistributionImpl\fP\&.
.SS "double org\&.apache\&.commons\&.math\&.distribution\&.PascalDistribution\&.getProbabilityOfSuccess ()"
Access the probability of success for this distribution\&.
.PP
\fBReturns:\fP
.RS 4
the probability of success 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.PascalDistributionImpl\fP\&.
.SS "void org\&.apache\&.commons\&.math\&.distribution\&.PascalDistribution\&.setNumberOfSuccesses (intsuccesses)"
Change the number of successes for this distribution\&.
.PP
\fBParameters:\fP
.RS 4
\fIsuccesses\fP the new number of successes 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.PascalDistributionImpl\fP\&.
.SS "void org\&.apache\&.commons\&.math\&.distribution\&.PascalDistribution\&.setProbabilityOfSuccess (doublep)"
Change the probability of success for this distribution\&.
.PP
\fBParameters:\fP
.RS 4
\fIp\fP the new probability of success 
.RE
.PP

.PP
Implemented in \fBorg\&.apache\&.commons\&.math\&.distribution\&.PascalDistributionImpl\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
