.TH "org.apache.commons.math.DimensionMismatchException" 3 "Wed Dec 4 2013" "Version 1.0" "Desmo-J" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.apache.commons.math.DimensionMismatchException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.apache\&.commons\&.math\&.MathException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDimensionMismatchException\fP (int dimension1, int dimension2)"
.br
.ti -1c
.RI "int \fBgetDimension1\fP ()"
.br
.ti -1c
.RI "int \fBgetDimension2\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Error thrown when two dimensions differ\&.
.PP
\fBSince:\fP
.RS 4
1\&.2 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBRevision:\fP
.RS 4
620312 
.RE
.PP
\fBDate:\fP
.RS 4
2008-02-10 12:28:59 -0700 (Sun, 10 Feb 2008) 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.apache\&.commons\&.math\&.DimensionMismatchException\&.DimensionMismatchException (intdimension1, intdimension2)"
Construct an exception from the mismatched dimensions 
.PP
\fBParameters:\fP
.RS 4
\fIdimension1\fP first dimension 
.br
\fIdimension2\fP second dimension 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "int org\&.apache\&.commons\&.math\&.DimensionMismatchException\&.getDimension1 ()"
Get the first dimension 
.PP
\fBReturns:\fP
.RS 4
first dimension 
.RE
.PP

.SS "int org\&.apache\&.commons\&.math\&.DimensionMismatchException\&.getDimension2 ()"
Get the second dimension 
.PP
\fBReturns:\fP
.RS 4
second dimension 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Desmo-J from the source code\&.
